JesusFilm/core

apps/api-journeys/prisma/migrations/20210810214902_init/migration.sql, apps/api-journeys/prisma/schema.prisma, apps/api-journeys/src/main.ts, apps/api-journeys/src/modules/journey/index.ts, package-lock.json, package.json
- use fastify
- use prisma UUID generator
- allow server to export as module for AWS Lambda
=> use fastify

apps/api-journeys/src/lib/db.ts, apps/api-journeys/types.d.ts
from https://github.com/prisma/prisma/issues/1983
=> reuse global prisma client in development

apps/api-journeys/prisma/seed.ts, apps/journeys/__generated__/GetJourneys.ts, apps/journeys/next.config.js, apps/journeys/pages/[journeyId].tsx, apps/journeys/pages/index.tsx
this is a developer improvement to see the list of journeys in the DB. Page will 404 if there are no journeys or the specified ID doesn't exist.
=> add journeys index page

.storybook/main.js, libs/shared/ui/.babelrc, libs/shared/ui/.eslintrc.json, libs/shared/ui/README.md, libs/shared/ui/jest.config.js, libs/shared/ui/src/components/Typography/Typography.spec.tsx, libs/shared/ui/src/components/Typography/Typography.stories.tsx, libs/shared/ui/src/components/Typography/Typography.tsx, libs/shared/ui/src/components/Typography/index.ts, libs/shared/ui/tsconfig.json, libs/shared/ui/tsconfig.lib.json, libs/shared/ui/tsconfig.spec.json, nx.json, tsconfig.base.json, workspace.json
I'm thinking we should house Text / Icon / Button in a common lib?
Keeping this basic so it can be quickly merged / John and I can use as a base for Text / Icon
This is literally just using the NX generator to create a new lib + giving it a basic component to test it works with storybook
=> Setup shared-ui library for common ui components

apps/journeys/__generated__/GetJourney.ts, apps/journeys/pages/[journeyId].tsx, apps/journeys/src/components/BlockRenderer/BlockRenderer.spec.tsx, apps/journeys/src/components/Conductor/Conductor.spec.tsx, apps/journeys/src/components/blocks/RadioOption/RadioOption.spec.tsx, apps/journeys/src/components/blocks/RadioOption/RadioOption.tsx, apps/journeys/src/components/blocks/Step/Step.spec.tsx, apps/journeys/src/components/blocks/Video/Video.spec.tsx, apps/journeys/src/libs/client/cache/blocks.ts, apps/journeys/src/libs/transformer/transformer.spec.ts
- fetch locked and nextBlockId on frontend
- fix type-check
- update action handling to new format
- add nextActiveBlock to block hook with locked and nextBlockId support
=> add locked and nextBlockId to journeys

apps/api-gateway/schema.graphql, apps/api-journeys/prisma/migrations/20210926224332_change_theme_to_theme_name_on_journey/migration.sql, apps/api-journeys/prisma/schema.prisma, apps/api-journeys/prisma/seed.ts, apps/api-journeys/schema.graphql, apps/api-journeys/src/__generated__/types.ts, apps/api-journeys/src/modules/block/__generated__/types.ts, apps/api-journeys/src/modules/block/index.spec.ts, apps/api-journeys/src/modules/journey/__generated__/types.ts, apps/api-journeys/src/modules/journey/index.spec.ts, apps/api-journeys/src/modules/journey/index.ts
- change default themeName to light
- change theme to themeName on journey
=> change theme to themeName

apps/journeys/src/components/blocks/Typography/Typography.stories.tsx, libs/shared/ui/src/libs/themes/base/theme.stories.tsx, libs/shared/ui/src/libs/themes/base/tokens/components.ts, libs/shared/ui/src/libs/themes/base/tokens/spacing.ts
`spacing: 4` in spacing design tokens on base.
=> change spacing to 4

apps/api-gateway/schema.graphql, apps/api-journeys/codegen.yml, apps/api-journeys/prisma/migrations/20210930223731_change_signup_to_sign_up/migration.sql, apps/api-journeys/prisma/schema.prisma, apps/api-journeys/prisma/seed.ts, apps/api-journeys/schema.graphql, apps/api-journeys/src/__generated__/types.ts, apps/api-journeys/src/modules/block/__generated__/types.ts, apps/api-journeys/src/modules/block/index.spec.ts, apps/api-journeys/src/modules/block/index.ts, apps/api-journeys/src/modules/response/__generated__/types.ts, apps/api-journeys/src/modules/response/index.spec.ts, apps/api-journeys/src/modules/response/index.ts, apps/journeys/__generated__/GetJourney.ts
- this will require devs to rerun `nx seed`
- change signup to signUp and Signup to SignUp
=> change signup to signUp

apps/journeys/src/components/blocks/Card/Card.stories.tsx, apps/journeys/src/components/blocks/Image/Image.stories.tsx
Current image is cropped incorrectly, use the full size image.
Should be using:
https://images.unsplash.com/photo-1521904764098-e4e0a87e3ce0?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1365&q=80
So it displays like:
﻿
=> Fix image source

tools/scripts/install-rover.sh
- Updated the command that installs rover
- Set the command to install a specific version of Rover
=> Rover Version Fix

apps/journeys/src/libs/client/cache/blocks.spec.ts, apps/journeys/src/libs/client/cache/blocks.ts
add function to check to see if descendants of active block include the provided id.
=> add isActiveBlockOrDescendant function

apps/journeys/src/components/blocks/Button/Button.spec.tsx, apps/journeys/src/components/blocks/Button/Button.tsx, apps/journeys/src/components/blocks/RadioOption/RadioOption.spec.tsx, apps/journeys/src/components/blocks/RadioOption/RadioOption.tsx, apps/journeys/src/components/blocks/SignUp/SignUp.spec.tsx, apps/journeys/src/components/blocks/SignUp/SignUp.tsx, apps/journeys/src/libs/action/handleAction.spec.ts, apps/journeys/src/libs/action/handleAction.ts
This will change page to the next journey.
We should wrap back at some point to add some fade out and in animation as the current transition will no doubt be pretty harsh.
=> navigate to journey action

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/__generated__/types.ts, apps/api-journeys/src/modules/action/action.ts, apps/api-journeys/src/modules/journey/__generated__/types.ts, apps/api-journeys/src/modules/journey/journey.spec.ts, apps/api-journeys/src/modules/journey/journey.ts, apps/journeys/__generated__/ActionFields.ts, apps/journeys/__generated__/ButtonFields.ts, apps/journeys/__generated__/GetJourney.ts, apps/journeys/__generated__/RadioOptionFields.ts, apps/journeys/__generated__/SignUpFields.ts, apps/journeys/src/libs/action/actionFields.ts, apps/journeys/src/libs/action/handleAction.spec.ts, apps/journeys/src/libs/action/handleAction.ts
- add journey to NavigateToJourneyAction
- refactor journey spec to more closely match typeDefs
- fetch journey slug on frontend when NavigateToJourneyAction
- ensure NavigateToJourneyAction doesn't throw error when journey is null
=> Add journey to navigate to journey action

apps/api-journeys/src/modules/journey/journey.spec.ts, apps/api-journeys/src/modules/journey/journey.ts
- test error throws BAD_USER_INPUT
- fix erroneous conditions
=> handle slug not unique error

apps/journeys/src/components/blocks/Video/Video.tsx
=> Video updates

apps/journeys/src/components/blocks/GridContainer/GridContainer.stories.tsx, apps/journeys/src/components/blocks/GridItem/GridItem.stories.tsx
put grid container and grid item in a folder
=> storybook changes for grid component

.storybook/preview.js, apps/journeys/src/components/Conductor/Conductor.stories.tsx, apps/journeys/src/components/Icon/Icon.stories.tsx, apps/journeys/src/components/JourneyProgress/JourneyProgress.stories.tsx, apps/journeys/src/components/blocks/Card/Card.stories.tsx, apps/journeys/src/components/blocks/RadioOption/RadioOption.stories.tsx, apps/journeys/src/components/blocks/RadioQuestion/RadioQuestion.stories.tsx, apps/journeys/src/components/blocks/SignUp/SignUp.stories.tsx, apps/journeys/src/components/blocks/SignUp/TextField/TextField.stories.tsx, apps/journeys/src/components/blocks/Typography/Typography.stories.tsx, apps/journeys/src/components/blocks/Video/Video.stories.tsx, apps/journeys/src/components/blocks/Video/Video.tsx, apps/journeys/src/libs/storybook/config.tsx, apps/journeys/src/libs/storybook/index.ts, libs/shared/ui/src/libs/storybook/config.tsx, libs/shared/ui/src/libs/storybook/decorators.tsx, libs/shared/ui/src/libs/themes/base/theme.stories.tsx
Make "all" mode stacked so it displays correctly for the 5 breakpoints in Chromatic
**Reminder that when manually testing components in the viewports, use either "light" or "dark".** 
"all" mode is for Chromatic testing or with default viewport (where height is variable).
https://3.basecamp.com/3105655/buckets/24865634/todos/4327677656
I've also tidied up the now redundant tests.
=> Storybook - stacked "all" mode

apps/api-gateway/schema.graphql, apps/api-journeys/prisma/factories/nua1.ts, apps/api-journeys/prisma/factories/nua2.ts, apps/api-journeys/prisma/factories/nua9.ts, apps/api-journeys/prisma/factories/nuaEp8.ts, apps/api-journeys/schema.graphql, apps/api-journeys/src/__generated__/types.ts, apps/api-journeys/src/modules/button/button.spec.ts, apps/api-journeys/src/modules/icon/__generated__/types.ts, apps/api-journeys/src/modules/icon/icon.ts, apps/api-journeys/src/modules/signUp/signUp.spec.ts, apps/journeys/__generated__/globalTypes.ts, apps/journeys/src/components/Conductor/data.ts, apps/journeys/src/components/Icon/Icon.spec.tsx, apps/journeys/src/components/Icon/Icon.stories.tsx, apps/journeys/src/components/Icon/Icon.tsx, apps/journeys/src/components/blocks/Button/Button.spec.tsx, apps/journeys/src/components/blocks/Button/Button.stories.tsx, apps/journeys/src/components/blocks/Card/Card.stories.tsx, apps/journeys/src/components/blocks/GridContainer/GridContainer.stories.tsx, apps/journeys/src/components/blocks/GridItem/GridItem.stories.tsx, apps/journeys/src/components/blocks/SignUp/SignUp.stories.tsx
- Update backend to support new icons introduced in NUA
- Update frontend to consume icon changes in the backend
- Update NUA seeds to use the right icons
=> Implement new icons introduced in NUA

CONTRIBUTING.md
Added instruction to make .env.local file in the journeys-admin
=> Add instruction for journeys-admin set up to CONTRIBUTING

apps/journeys-admin/__generated__/ActionFields.ts, apps/journeys-admin/__generated__/BlockFields.ts, apps/journeys-admin/__generated__/ButtonFields.ts, apps/journeys-admin/__generated__/CardFields.ts, apps/journeys-admin/__generated__/GetJourneyForEdit.ts, apps/journeys-admin/__generated__/GridContainerFields.ts, apps/journeys-admin/__generated__/GridItemFields.ts, apps/journeys-admin/__generated__/ImageFields.ts, apps/journeys-admin/__generated__/RadioOptionFields.ts, apps/journeys-admin/__generated__/RadioQuestionFields.ts, apps/journeys-admin/__generated__/RadioQuestionResponseCreate.ts, apps/journeys-admin/__generated__/SignUpFields.ts, apps/journeys-admin/__generated__/SignUpResponseCreate.ts, apps/journeys-admin/__generated__/StepFields.ts, apps/journeys-admin/__generated__/TypographyFields.ts, apps/journeys-admin/__generated__/VideoFields.ts, apps/journeys-admin/__generated__/VideoResponseCreate.ts, apps/journeys-admin/__generated__/VideoTriggerFields.ts, apps/journeys-admin/__generated__/globalTypes.ts, apps/journeys-admin/apollo.config.js, apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx, apps/journeys-admin/src/components/FramePortal/FramePortal.spec.tsx, apps/journeys-admin/src/components/FramePortal/FramePortal.stories.tsx, apps/journeys-admin/src/components/FramePortal/FramePortal.tsx, apps/journeys-admin/src/components/FramePortal/index.ts, apps/journeys-admin/src/components/index.ts, package-lock.json, package.json
- add FramePortal component
- add types for journeys-admin
=> FramePortal

apps/journeys-admin/src/components/ThemeProvider/ThemeProvider.tsx, apps/journeys-admin/src/components/ThemeProvider/index.ts, apps/journeys-admin/src/components/ThemeProvider/theme.ts, apps/journeys-admin/src/components/index.ts, apps/journeys-admin/src/libs/storybook/config.tsx
- add admin theme
- use admin theme in storybook
=> add admin theme

apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx, apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx, apps/journeys-admin/src/components/CardPreview/CardPreview.tsx, apps/journeys-admin/src/components/CardPreview/index.ts
- add CardPreview
- allow parent to control selected
- when selection changes trigger event
=> card preview

apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
Updated the size and spacing of preview card
=> updated sizing

apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx, apps/journeys-admin/src/components/CardPreview/CardPreview.tsx, apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.spec.tsx, apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.stories.tsx, apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx, apps/journeys-admin/src/components/HorizontalSelect/index.ts
The select with border is a common component used in a few places for the editor. This abstracts this component from the existing CardPreview into its own component.
=> HorizontalSelect component

apps/journeys/__generated__/GetJourneySlugs.ts, apps/journeys/pages/[journeySlug].tsx, apps/journeys/pages/index.tsx
- index should load props at build time
- journeySlug should load props at build time
=> speed up journey load time

apps/journeys-admin/.babelrc, apps/journeys-admin/jest.config.js, apps/journeys-admin/next-env.d.ts, apps/journeys-admin/pages/_app.tsx, apps/journeys-admin/pages/index.tsx, apps/journeys-admin/pages/journeys/[journeySlug].tsx, apps/journeys-admin/pages/journeys/index.tsx, apps/journeys-admin/src/components/Editor/Editor.spec.tsx, apps/journeys-admin/src/components/index.ts, apps/journeys-admin/src/libs/storybook/config.tsx, apps/journeys/src/components/blocks/Card/Card.tsx, libs/journeys/ui/src/components/Video/VideoTrigger/VideoTrigger.tsx, package-lock.json, package.json
- remove theme provider on each journeysAdmin page
- update nextjs to v12.0.7
- enable swc on journeysAdmin
- fix handleAction error
=> update imports so journeys-admin works locally

apps/api-journeys/db/seed.ts, apps/api-users/db/seed.ts
=> move user journey seed and remove double awaits

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attribute/Attribute.stories.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attribute/Attribute.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Button/Button.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Button/Button.stories.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Button/Button.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Button/index.ts, apps/journeys-admin/src/components/ThemeProvider/admin/tokens/components.ts
- use button in attribute component
=> add button to control panel

apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx, libs/journeys/ui/src/index.ts, libs/journeys/ui/src/libs/context/EditorContext.tsx, libs/journeys/ui/src/libs/context/index.ts, libs/journeys/ui/src/libs/index.ts
- Add Active Tab into Editor Context
=> Active Tab

apps/journeys/next-env.d.ts, apps/journeys/src/components/Conductor/Conductor.tsx, libs/journeys/ui/src/components/Card/Card.tsx, libs/journeys/ui/src/components/Video/Video.tsx, package-lock.json, package.json
- add Div100vh (this uses JS to determine the height. This is a `feature` of safari)
- use new height calculations in the conductor
- fix border-radius glitch on safari
=> fix card heights

libs/journeys/ui/src/components/Card/Cover/Cover.tsx, libs/journeys/ui/src/components/Video/Video.tsx
- Fix auto fullscreen when video gets autoplayed
- Add logic to prevent Iphone, Ipod, Ipad from auto-playing
=> Stop video going fullscreen on iOS

apps/journeys-admin/src/components/Editor/Editor.tsx
editor layout needs to think about toolbar being present at top of window.
=> fix editor height

libs/journeys/ui/src/libs/context/EditorContext.spec.tsx, libs/journeys/ui/src/libs/context/EditorContext.tsx
This should allow components when being updated for the UI to automatically change to reflect the new state.
=> SetStepsAction should set selectedStep and SelectedBlock

apps/api-journeys/src/app/modules/block/block.service.ts
- Fix the missing syntax in the getSiblings function
=> Fix missing syntax in getSiblings

apps/journeys-admin/pages/_app.tsx, apps/journeys-admin/pages/index.tsx, apps/journeys-admin/pages/journeys/[journeySlug].tsx, apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx, apps/journeys-admin/pages/users/sign-in.tsx, apps/journeys/pages/[journeySlug].tsx, apps/journeys/pages/_app.tsx, package-lock.json, package.json
this feature is being added to test vercel deployments.
This will replace our manual efforts to handle title and meta data additions to pages across journeys and journeys-admin.
=> add next-seo

apps/api-journeys/db/seeds/nua1.ts, apps/api-journeys/db/seeds/nua9.ts
Some parentOrder's missing, others miss a number
=> Fix seed data

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/card/card.graphql, apps/api-journeys/src/app/modules/block/card/card.resolvers.spec.ts, apps/api-journeys/src/app/modules/block/step/step.graphql, apps/api-journeys/src/app/modules/block/step/step.resolvers.spec.ts
- Remove parentOrder from card and step's create mutation
=> Remove parentOrder from create mutation

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/card/card.graphql, apps/api-journeys/src/app/modules/block/image/image.graphql, apps/api-journeys/src/app/modules/block/signUp/signUp.graphql, apps/api-journeys/src/app/modules/block/step/step.graphql, apps/api-journeys/src/app/modules/block/step/step.resolvers.spec.ts, apps/api-journeys/src/app/modules/block/step/step.resolvers.ts, apps/api-journeys/src/app/modules/block/typography/typography.graphql, apps/api-journeys/src/app/modules/block/video/video.graphql, apps/journeys-admin/__generated__/globalTypes.ts
- Make parentBlockID required for all the create mutations
- Removed parentBlockId from the StepBlock
=> Make parentBlockId required

.github/workflows/main.yml
Exit with status 0 (OK) once the build has been sent to Chromatic. Chromatic is connected to github so with report its status automatically.
=> speed up vr by adding exitOnceUploaded

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/action/action.graphql
- Fix the naming of navigate to journey action mutation
=> Fix the naming of navigate to journey action

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/video/video.graphql, apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts, apps/journeys-admin/__generated__/globalTypes.ts
- Implement fullsize prop into video
=> Added fullsize prop into video

.github/workflows/main.yml, tools/scripts/check-git-branch-name.sh
- https://3.basecamp.com/3105655/buckets/25678037/todos/4632501521
=> chore: add branch naming

.github/workflows/api-deploy-worker.yml, .github/workflows/api-gateway-worker.yml
Adds stage & main to current images in ECR for easier management
=> add stage & main tags to images

.github/workflows/api-deploy.yml
Add the 1 missing branch variable in api-deploy
=> fix: add branch to api-deploy

.github/workflows/api-deploy.yml, .github/workflows/api-gateway-worker.yml
ref was providing the full reference
ref_name should provide just the branch
=> fix: replace ref with ref_name in github actions

.github/workflows/api-deploy-worker.yml, .github/workflows/api-gateway-worker.yml
Switching to pushing multiple image tags needed a change in the syntax
=> fix: docker push all images for deployment

apps/api-gateway/schema.graphql, apps/api-journeys/db/seeds/nua1.ts, apps/api-journeys/db/seeds/nua2.ts, apps/api-journeys/db/seeds/nua8.ts, apps/api-journeys/db/seeds/nua9.ts, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/button/button.graphql, apps/journeys-admin/__generated__/globalTypes.ts, apps/journeys-admin/src/libs/apolloClient/cache.ts, apps/journeys/src/libs/client/cache/cache.ts
Icon isn't retrieved properly in main branch due to seed data error and not caching IconBlock.
Also updated ButtonBlockUpdate to be able to change start and endIconId
=> fix: icon display and seed data

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/signUp/signUp.graphql, apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts, apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts, apps/journeys-admin/__generated__/globalTypes.ts
Adds SignUpBlockUpdate so Siyang can update submit button Icon.
[Basecamp](https://3.basecamp.com/3105655/buckets/26244169/todos/4641364703)
=> feature: add SignUpBlockUpdate

apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx, apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx, apps/journeys-admin/src/components/CardPreview/CardPreview.tsx, apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx, apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx, apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx, apps/journeys-admin/src/components/JourneyView/CardView/CardView.spec.tsx, apps/journeys-admin/src/components/JourneyView/CardView/CardView.stories.tsx
Base Theme provider should use journey theme. At the moment it was hardcoded in.
=> fix: use journey theme for card

apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewImageButton/NewImageButton.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewVideoButton/NewVideoButton.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
Tons of parentOrder test warnings are clogging the test log, fixing some for easier debugging.
=> fix: parentOrder test warnings

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/action/action.graphql
Missed this first time round, update return type for updateAction mutations.
=> fix: fix updateAction return type

apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts, apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.spec.ts, apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts, apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.spec.ts, apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.ts
Parent block id is needed to update the cache for action on the front end
=> fix: added parentBlock id into the action API

apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx, apps/journeys-admin/src/components/Editor/Editor.spec.tsx, apps/journeys-admin/src/components/Editor/Editor.stories.tsx, apps/journeys-admin/src/components/Editor/Editor.tsx, apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx, apps/journeys-admin/src/components/Editor/JourneyEdit/index.ts
Need to give context to PageWrapper Menu
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26244167/todos/4670497756)
=> fix: refactored editor provider

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/modules/block/block.graphql, apps/api-journeys/src/app/modules/block/block.resolver.ts, apps/api-journeys/src/app/modules/block/block.service.spec.ts, apps/api-journeys/src/app/modules/block/block.service.ts, apps/journeys-admin/__generated__/BlockDeleteForBackgroundImage.ts, apps/journeys-admin/__generated__/BlockDeleteForBackgroundVideo.ts, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx, apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts, apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.ts
Changes output of blockDelete to be changed siblings on success. Includes new blockDeleteUpdate function to simplify block deletion and the cache. Does a better job of handling cache changes
https://3.basecamp.com/3105655/buckets/26244167/todos/4670496920
=> fix: blockDelete

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.tsx, apps/journeys-admin/src/components/Editor/Editor.stories.tsx
Allows the icon on signUp be edited
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26244169/todos/4632689918)
=> feature: edit signup icon

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/SignUp/SignUp.spec.tsx
Test on sign up wasn't correctly testing drawer is being opened for icon
](https://3.basecamp.com/3105655/buckets/26244169/todos/4632689918)
=> fix: Update signUp icon test

dangerfile.ts
This should fix the issue where main was not building on feature pushes to main. This matches our commitlint config for commit types with pr title and branch. 
=> style: match commitlint, pr branch and title

.github/workflows/api-deploy-worker.yml, .github/workflows/api-deploy.yml
Add arclight api key to github action for deploying api-languages and api-videos
=> ci: add arclight api key

.github/workflows/api-deploy-worker.yml, .github/workflows/api-gateway-worker.yml
Should fix github action conditionals that are firing improperly
=> fix: github action conditionals

package-lock.json, package.json
Locks the version of winston-cloudwatch in package.json
=> fix: version lock winston-cloudwatch

apps/api-gateway/supergraph-main.yml, apps/api-gateway/supergraph-stage.yml
=> fix: supergraph endpoint

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx, apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx, apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
This disables autoplay and mute controls on background videos
- https://3.basecamp.com/3105655/buckets/26244194/todolists/4636834221
View a background video
=> fix: disable background video autoplay & mute

apps/journeys-admin/setupTests.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Button/Size/Size.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardLayout/CardLayout.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/RadioOption/RadioOption.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx, apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.spec.tsx, libs/journeys/ui/src/components/Image/Image.tsx
While not explicitly failing, the test cases often spit out wads of warnings. This PR cleans many of them up
=> chore: fix test case warnings

libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.stories.tsx, libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
Fixes this issue:
[Basecamp](https://3.basecamp.com/3105655/buckets/26244194/todos/4743027954)
=> fix: add bottom margin to radio question

apps/api-videos/src/app/modules/video/video.resolver.ts, apps/api-videos/src/app/modules/video/video.service.ts
KeyAsId snuck into a resolver around the merge removing them
Handled by internal unit testing
=> fix: remove keyasid from resolver

apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.ts, apps/journeys/pages/[journeySlug].tsx
- bugfix to allow user to find newly published journeys
- allow primaryImageBlock to be visible
=> fix: allow not found journey

apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx, apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.stories.tsx, apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
Access button on journey menu now opens the access dialog
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752586399)
=> feat: link access button

apps/api-journeys/src/app/modules/block/block.service.spec.ts, apps/api-journeys/src/app/modules/block/block.service.ts
Fix to error in block delete
[-basecamp todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4761166148)
=> fix: sibling for block delete

apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx, apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx, apps/journeys-admin/src/components/ThemeProvider/admin/tokens/typography.ts
A collection of minor styling adjustments
[- Updated casing of starts at and ends at](https://3.basecamp.com/3105655/buckets/26787371/todos/4752780834)
[- Removed letter spacing for subtitle1 to match design](https://3.basecamp.com/3105655/buckets/26787371/todos/4752776062)
[- Added a fixed width for Cover Image dialog ](https://3.basecamp.com/3105655/buckets/26787371/todos/4752775524)
=> style: background video

apps/journeys-admin/setupTests.tsx, apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.spec.tsx, apps/journeys/setupTests.ts
Github Action tests are timing out, this is an attempt to rectify
=> fix: slow test timeout

tools/scripts/install-rover.sh
- download rover from github
- add to /home/node/.local/bin
=> chore: download rover from github on m1

.github/workflows/api-deploy-worker.yml, apps/api-journeys/db/seed.ts, apps/api-languages/db/seed.ts, apps/api-users/db/seed.ts, apps/api-videos/db/seed.ts
command should be `nx affected:apps plain --base HEAD~1 --head HEAD`
this is an urgent fix as prod is broken. Expecting build failures on this one.
=> fix: api deploy worker to compare previous head

.github/workflows/api-deploy-worker.yml, apps/api-journeys/db/seed.ts, apps/api-languages/db/seed.ts, apps/api-users/db/seed.ts, apps/api-videos/db/seed.ts
- plain not set properly
- affected with file name does not do what we think it should
=> fix: affected scripts for app seed and apps

apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts, apps/api-journeys/src/app/modules/block/video/video.resolver.ts
- don't try and get video on a video block if no language id set
=> fix: disable video if no language

apps/journeys-admin/src/components/ThemeProvider/admin/tokens/typography.ts
this letter-spacing does not match design.
=> fix: journeys-admin letter spacing

apps/api-gateway/schema.graphql, apps/api-languages/schema.graphql, apps/api-languages/src/app/__generated__/graphql.ts, apps/api-languages/src/app/modules/language/language.graphql, apps/api-languages/src/app/modules/language/language.resolver.ts, apps/api-languages/src/app/modules/language/language.service.ts, apps/api-videos/schema.graphql, apps/api-videos/src/app/__generated__/graphql.ts, apps/api-videos/src/app/modules/video/video.graphql, apps/api-videos/src/app/modules/video/video.resolver.spec.ts, apps/api-videos/src/app/modules/video/video.resolver.ts, apps/api-videos/src/app/modules/video/video.service.spec.ts, apps/api-videos/src/app/modules/video/video.service.ts
Apollo uses offset-based pagination. This changes from using page to offset in our API.
**Build failures are expected.**
=> fix: change page to offset

package-lock.json, package.json
add @storybook/jest to dev dependencies.
=> chore: add storybook jest

apps/journeys/src/components/Conductor/Conductor.tsx
Fade slide when navigating to next slide. Unmount on complete fade.
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752603982)
=> fix: fade previous slide

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/journey/journey.graphql, apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts, apps/journeys-admin/__generated__/globalTypes.ts
Extended the api-journeys with social title and social description
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752672406)
=> feat: added social title and description

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/journey/journey.graphql
Added seo title and seo description to journey.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752672406)
=> feat: add seo fields to journey

libs/journeys/ui/src/components/Card/Card.tsx, libs/journeys/ui/src/components/Card/Cover/Cover.tsx, libs/journeys/ui/src/index.ts, libs/journeys/ui/src/libs/blurImage/blurImage.spec.ts, libs/journeys/ui/src/libs/blurImage/blurImage.ts, libs/journeys/ui/src/libs/blurImage/index.ts, libs/journeys/ui/src/libs/index.ts
We want to reuse the logic to generate an image from the blurhash to be used in the video poster and image blocks
=> refactor: extract out blurImage to reuse in video and image

libs/journeys/ui/src/components/Video/Video.tsx
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4757625092)
=> fix: allow autoplay on safari

CONTRIBUTING.md
Updated docs to include set up instructions for new API projects
=> docs: added and refactored contributing for new api projects

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.tsx
Allows for feedback of video updates, and prevents errors from crashing the application
=> feat: video feedback

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Image/Options/ImageOptions.tsx
Allows for feedback of image updates, and prevents errors from crashing the application
=> feat: image feedback

CONTRIBUTING.md
Stop all these linting issues!
=> docs: pr naming

.github/workflows/main.yml
=> fix: update commitlint version

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Attributes.stories.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.stories.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/PaletteColorPicker/PaletteColorPicker.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/PaletteColorPicker/PaletteColorPicker.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/PaletteColorPicker/index.ts, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/Swatch/Swatch.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/Swatch/Swatch.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/Swatch/index.ts, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.stories.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx
- Selected color swatch now properly reflects Card
- Fixed choosing color via custom color picker (also switched to using HEX rather than RGB picker)
- Changed palette colors from theme colors to custom range
[Basecamp - selected color](https://3.basecamp.com/3105655/buckets/26787371/todos/4752754608)
[Basecamp - debounce color picker fix](https://3.basecamp.com/3105655/buckets/26787371/todos/4752753333)
Error handling incorrect typed colors can be done separately.
=> fix: background color selection and change

apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/block.service.spec.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts, apps/api-journeys/src/app/modules/userJourney/userJourney.service.spec.ts, apps/api-languages/src/app/modules/language/language.resolver.spec.ts, apps/api-languages/src/app/modules/language/language.resolver.ts
add language reference resolver to allow journeys api to render journeys.
=> fix: no language resolve reference

apps/journeys-admin/.env.example, apps/journeys-admin/pages/_app.tsx, apps/journeys/.env.example, apps/journeys/pages/_app.tsx, package-lock.json, package.json
- add https://www.npmjs.com/package/@datadog/browser-rum
- add journeys-admin rum configuration
- add journeys rum configuration
=> feat: add dd-rum-agent

apps/journeys-admin/next.config.js, apps/journeys/next.config.js
update next js configuration to enable source maps for better error troubleshooting.
=> feat: prod source maps

apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.spec.tsx, apps/journeys/pages/[journeySlug].tsx
Fix og url
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752672406#__recording_4863157551)
=> fix: og url

apps/journeys/pages/index.tsx
Shows only the journeys that are featured in journeys list on nextsteps.
=> feat: show featured on journeys list

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/video/video.graphql, apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts, apps/api-journeys/src/app/modules/block/video/video.resolver.ts
EndAt field on Admin currently does nothing. It is expected to go to the next step when it reaches the EndAt time. This is the backend changes for this ticket.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752798992)
=> fix: add action to video block

apps/watch/next.config.js
This enables base language routing in watch
=> feat: watch front end languages

apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewTypographyButton/index.ts, apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
Add typography blocks for title and description when a poll block is created.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4806098055)
=> fix: add radio question typography

apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
Add fonts to iframe card preview & canvas
=> fix: add fonts to iframe preview

apps/journeys/pages/api/revalidate.ts
use accessToken not secret in revalidate function.
=> fix: use access token not secret

apps/api-gateway/schema.graphql, apps/api-videos/db/seed.ts, apps/api-videos/schema.graphql, apps/api-videos/src/app/__generated__/graphql.ts, apps/api-videos/src/app/modules/video/video.graphql, apps/api-videos/src/app/modules/video/video.service.spec.ts, apps/api-videos/src/app/modules/video/video.service.ts, apps/watch/__generated__/GetVideo.ts, apps/watch/__generated__/GetVideoSiblings.ts, apps/watch/__generated__/GetVideos.ts, apps/watch/pages/[...slug].tsx, apps/watch/src/components/Videos/VideoList/Card/VideoListCard.tsx, apps/watch/src/components/Videos/VideoList/List/VideoListList.tsx, apps/watch/src/components/Videos/VideoList/VideoList.tsx, apps/watch/src/components/Videos/VideoList/testData.ts
This allows permalinks to exist for multiple languages. Additionally, it allows for use of old permalinks, without losing the reference in the case a new permalink is created.
=> feat: multi language permalink

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/response/response.module.ts, apps/api-journeys/src/app/modules/response/step/step.graphql, apps/api-journeys/src/app/modules/response/step/step.resolver.spec.ts, apps/api-journeys/src/app/modules/response/step/step.resolver.ts
Add step response to api-journey
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787374/todos/4816009972)
None, backend only
=> feat: add step response

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/response/step/step.graphql, apps/api-journeys/src/app/modules/response/step/step.resolver.spec.ts, apps/api-journeys/src/app/modules/response/step/step.resolver.ts
Removed fields as it can be referenced via blockId. Add userId via resolver.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787374/todos/4816009972)
=> refactor: remove fields, added userId

.devcontainer/devcontainer.json, .devcontainer/post-create-command.sh
This adds support for running docker on the host from inside the development environment as well as adding act github actions runner
=> feat: docker and act

.github/workflows/api-deploy-worker.yml, .github/workflows/api-gateway-worker.yml, .github/workflows/etl-deploy.yml
This should allow deployments to eks to function again
=> fix: add kubectl version

apps/api-journeys/db/seed.ts, apps/api-languages/db/seed.ts, apps/api-users/db/seed.ts, apps/api-videos/db/seed.ts
Project databases weren't getting created under certain circumstances.
=> fix: arango collection creation

apps/journeys-admin/src/components/LanguageSelect/LanguageSelect.tsx
languages are currently limited to the first 5000. Arclight currently has 1996 languages.
=> fix: show all languages

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/event/event.module.ts, apps/api-journeys/src/app/modules/event/journey/journey.graphql, apps/api-journeys/src/app/modules/event/journey/journey.resolver.spec.ts, apps/api-journeys/src/app/modules/event/journey/journey.resolver.ts
Created journey view event
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787374/todos/4816009837)
=> feat: add journey view event

apps/journeys-admin/__generated__/JourneyFields.ts, apps/journeys/__generated__/JourneyFields.ts, apps/watch-admin/__generated__/JourneyFields.ts, apps/watch/__generated__/JourneyFields.ts, libs/journeys/ui/src/libs/context/__generated__/JourneyFields.ts
URGENT update of journeyFields types preventing production deployment.
=> fix: update journey fields type

libs/journeys/ui/src/components/Image/Image.tsx
Memoize blurImage on ImageBlock to simplify calculations on each render
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4923485547)
=> perf: memoize blurImage on ImageBlock

apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewImageButton/NewImageButton.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestion.stories.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewRadioQuestionButton/NewRadioQuestionButton.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewTypographyButton/NewTypographyButton.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewVideoButton/NewVideoButton.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
Need to remove labels from radio question create - it's throwing warnings / not letting us create.
=> fix: radio question create

.github/workflows/main.yml, CONTRIBUTING.md
=> docs: fix fetch command

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/event/event.module.ts, apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.spec.ts, apps/api-journeys/src/app/modules/event/radioQuestion/radioQuestion.resolver.ts, apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.spec.ts, apps/api-journeys/src/app/modules/event/signUp/signUp.resolver.ts, apps/api-journeys/src/app/modules/event/step/step.resolver.spec.ts, apps/api-journeys/src/app/modules/event/step/step.resolver.ts, apps/api-journeys/src/app/modules/event/video/video.graphql, apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts, apps/api-journeys/src/app/modules/event/video/video.resolver.ts, apps/journeys-admin/__generated__/VideoPlayEventCreate.ts, apps/journeys-admin/__generated__/globalTypes.ts, apps/journeys/__generated__/VideoPlayEventCreate.ts, apps/journeys/__generated__/globalTypes.ts, apps/watch-admin/__generated__/VideoPlayEventCreate.ts, apps/watch-admin/__generated__/globalTypes.ts, apps/watch/__generated__/VideoPlayEventCreate.ts, apps/watch/__generated__/globalTypes.ts, libs/journeys/ui/__generated__/globalTypes.ts, libs/journeys/ui/src/components/Video/__generated__/VideoPlayEventCreate.ts
Refactor video events
- Removed play state enum
- Add new events (Start, Pause, Complete, Expand, Collapse, Progress")
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787374/todos/4816010650)
=> refactor: video event api

.github/workflows/main.yml, libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.tsx
=> fix: add good commit to fix command lint

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/event/video/video.graphql
Video position changed from Int to float. Fixed up spelling.
=> refactor: video position to float

apps/journeys-admin/next.config.js, apps/journeys/next.config.js
add image shack as image source
=> chore: add imageshack as image source

package-lock.json, package.json
Adds the dependency for react gtm module for managing the data layer.
=> chore: add react gtm module dependency

apps/journeys/pages/_app.tsx, apps/journeys/src/components/Conductor/Conductor.spec.tsx, apps/journeys/src/components/Conductor/Conductor.tsx, libs/journeys/ui/src/components/Button/Button.spec.tsx, libs/journeys/ui/src/components/Button/Button.tsx, libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx, libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx, libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx, libs/journeys/ui/src/components/SignUp/SignUp.tsx, libs/journeys/ui/src/components/Step/Step.spec.tsx, libs/journeys/ui/src/components/Step/Step.tsx, libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.spec.tsx, libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.tsx
Sends data custom event data to gtm
=> feat: add ga custom events

apps/journeys/src/components/Conductor/Conductor.spec.tsx, apps/journeys/src/components/Conductor/Conductor.tsx
JourneyView event now will also get the Journey Title
](https://3.basecamp.com/3105655/buckets/27717553/todos/4960673481)
=> feat: send title on journey view to ga

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/modules/event/video/video.graphql, apps/api-journeys/src/app/modules/event/video/video.resolver.spec.ts
Fix types on video events position
=> fix: video position type

.github/workflows/crowdin.yml
the PR the crowdin github action makes is not fomatted correctly. This fixes that.
=> fix: update crowdin pr format

.github/workflows/crowdin.yml
=> fix: update crowdin branch name

resources/kube/arangodb-bigquery-etl/Dockerfile, resources/kube/arangodb-bigquery-etl/bqexport.sh
adds events to BQ export
adds executable permission on bqexport.sh
=> feat: add events to bigquery

libs/journeys/ui/src/components/Video/Video.tsx, libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.spec.tsx, libs/journeys/ui/src/components/Video/VideoEvents/VideoEvents.tsx
Add video name and id to video events
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27717553/todos/4960674204)
=> feat: add video name and id to video events

apps/journeys-admin/i18next-parser.config.js, apps/journeys-admin/next-i18next.config.js, apps/journeys-admin/next.config.js, apps/journeys-admin/pages/_app.tsx, apps/journeys-admin/pages/index.tsx, apps/journeys-admin/pages/journeys/[journeySlug].tsx, apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx, apps/journeys-admin/pages/users/sign-in.tsx, apps/journeys-admin/project.json, libs/locales/en/apps-journeys-admin.json
add i18n to journeys admin
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27717553/todos/4974746607)
=> feat: add i18n to journeys admin

.gitignore, apps/journeys-admin/next-i18next.config.js, apps/journeys-admin/project.json, libs/locales/project.json, workspace.json
breaking production. This resolves the missing locales issue.
=> fix: copy locales on build

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/journey/journey.graphql, apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.ts, apps/api-journeys/src/app/modules/journey/journey.service.spec.ts, apps/api-journeys/src/app/modules/journey/journey.service.ts, apps/journeys-admin/__generated__/JourneyPublish.ts, apps/journeys-admin/__generated__/globalTypes.ts, apps/journeys/__generated__/globalTypes.ts, apps/watch-admin/__generated__/globalTypes.ts, apps/watch/__generated__/globalTypes.ts, libs/journeys/ui/__generated__/globalTypes.ts, libs/nest/database/src/lib/base.service.ts
This PR adds archive/delete/restore functionality to the journeys API
https://3.basecamp.com/3105655/buckets/27930172/todolists/5007994015
This will require UI components to fully test due to authentication. It should have full unit-test coverage and uses no new service calls.
=> feat: new journey statuses

apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts, apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Allowing videos to be created with a default action - navigate action
- Link to Basecamp Todo (no basecamp todo)
=> fix: video block default action

apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
=> fix: remove console log

.github/workflows/main.yml, apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
Linting is currently failing on main
Failing PR - #707 (270cf47)
Earliest good commit (used as reference) - #709 (5364963)
=> docs: updating commit lint

apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
This fixes the missing add button on journey overview
=> fix: missing add button on overview

dangerfile.ts
**Developer Convenience Feature** check PR title matches commitlint format
=> chore: add commitlint config to pr title

apps/journeys-admin/pages/_app.tsx, apps/journeys-admin/pages/index.tsx, apps/journeys-admin/pages/journeys/[journeySlug].tsx, apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx, libs/shared/ui/src/components/FlagsProvider/FlagsProvider.spec.tsx, libs/shared/ui/src/components/FlagsProvider/FlagsProvider.tsx, libs/shared/ui/src/components/FlagsProvider/index.ts, libs/shared/ui/src/libs/getLaunchDarklyClient/getLaunchDarklyClient.ts, libs/shared/ui/src/libs/getLaunchDarklyClient/index.ts, package-lock.json, package.json
- add FlagsProvider and useFlags to @core/shared/ui
- use FlagsProvider on journeys-admin
- pull flags object from launch darkly for firebase user
- add LAUNCH_DARKLY_SDK_KEY to doppler for all journeys-admin environments
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27931561/todos/5040917540)
Needs the embed reports PR to be completed using functionality from this PR to test. Should not change anything about the current production apps.
=> feat: add launch darkly and flags provider

resources/kube/arangodb/arangodb-stage-deployment.yaml, resources/kube/arangodb/arangodb-stage-service.yaml
Resource files for new stage db server
=> feat: stage db server resources

apps/journeys-admin/pages/index.tsx, apps/journeys-admin/pages/journeys/[journeySlug].tsx, apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx
Fixes JSON error in admin-journeys
=> fix: launchdarkly json

.github/workflows/main.yml, .husky/pre-commit, dangerfile.ts, package-lock.json, package.json, validate-branch-name.config.js
This is a quality of life update for developers. This will prevent commits to branches that don't meet our strict branch naming conventions
- validates branch name before allowing commits on the branch
- validates branch name in github actions
=> feat: validate branch name

resources/kube/arangodb-bigquery-etl/Dockerfile, resources/kube/arangodb-bigquery-etl/bqexport.sh
Fixes event table exports and allows for future dynamic fields
=> fix: events import schema

.github/merge-bot.yml
Adds a bot to manage merging to stage. All devs need to do now is add in the "on stage" label to their PRs. A bot will then merge the branch into the stage branch if no conflicts occur.
=> feat: add merge bot config

resources/kube/api/api-gateway-main-deployment.yaml, resources/kube/api/api-gateway-stage-deployment.yaml, resources/kube/api/api-journeys-main-deployment.yaml, resources/kube/api/api-journeys-stage-deployment.yaml, resources/kube/api/api-languages-main-deployment.yaml, resources/kube/api/api-languages-stage-deployment.yaml, resources/kube/api/api-users-main-deployment.yaml, resources/kube/api/api-users-stage-deployment.yaml, resources/kube/api/api-videos-main-deployment.yaml, resources/kube/api/api-videos-stage-deployment.yaml, resources/kube/doppler-secret/doppler-secret.yaml
Add doppler to kubernetes. Followed the instructions [here](https://docs.doppler.com/docs/kubernetes-operator).
For new api projects:
1. add service token to doppler-kubernetes-operator substituting the **NAME** and running for both stg and prd **ENV**.
```sh
kubectl create secret generic doppler-api-NAME-token-secret-ENV \
--namespace doppler-operator-system \
--from-literal=serviceToken=$(doppler configs tokens create doppler-kubernetes-operator --plain -p api-NAME -c ENV)
```
2. add new project with environments to resources/kube/doppler-secret/doppler-secret.yaml substituting the **NAME**
```YAML
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
name: dopplersecret-api-NAME-stg
namespace: doppler-operator-system
spec:
tokenSecret:
name: …
```
=> feat: add doppler to kubernetes

apps/api-gateway/src/environments/environment.prod.ts
Allow staging projects to connect to the API.
=> chore: update api-gateway cors

apps/api-gateway/src/environments/environment.prod.ts
Adds localhost cors ability to test api from local dev environment
=> feat: localhost cors

validate-branch-name.config.js
Stage branch should be recognised with correct branch name "stage"
=> fix: add stage branch validation

.storybook/main.js, package-lock.json, package.json
Some recent dependency change meant that storybook was not building locally. Following the error, polyfill was added for util/
=> fix: add polyfill to storybook

apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
Fix some of the tests that are failing on the backend. Image and Journeys have some failing tests.
=> fix: breaking backend tests

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/journey/journey.graphql
Extend journey with template field
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28496234/todos/5142564959)
=> feat: extend journey with template field

apps/api-gateway/schema.graphql, apps/api-users/schema.graphql, apps/api-users/src/app/__generated__/graphql.ts, apps/api-users/src/app/modules/user/user.graphql, apps/api-users/src/app/modules/user/user.resolver.spec.ts
Add publisher role to user
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28496234/todos/5146325444)
=> feat: add publisher role to user

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/journey/journey.graphql
Refactoring template field on journey to boolean from templateStatus
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28496234/todos/5142564959)
=> refactor: template field

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/event/event.module.ts, apps/api-journeys/src/app/modules/event/template/template.graphql, apps/api-journeys/src/app/modules/event/template/template.resolver.spec.ts, apps/api-journeys/src/app/modules/event/template/template.resolver.ts
Add templateLibraryViewEvent, templateUseEvent, templatePreviewEvent to custom events
- [templateLibraryViewEvent](https://3.basecamp.com/3105655/buckets/28496234/todos/5147265411)
- [templateUseEvent](https://3.basecamp.com/3105655/buckets/28496234/todos/5160247604)
- [templatePreviewEvent](https://3.basecamp.com/3105655/buckets/28496234/todos/5147267294)
=> feat: create template events

apps/api-journeys/src/app/app.module.ts, apps/api-journeys/src/app/lib/roleGuard/roleGuard.spec.ts, apps/api-journeys/src/app/lib/roleGuard/roleGuard.ts, apps/api-journeys/src/app/modules/action/action.resolver.spec.ts, apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts, apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.spec.ts, apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts, apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.spec.ts, apps/api-journeys/src/app/modules/block/block.module.ts, apps/api-journeys/src/app/modules/block/block.resolver.spec.ts, apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts, apps/api-journeys/src/app/modules/block/card/card.resolver.spec.ts, apps/api-journeys/src/app/modules/block/gridContainer/gridContainer.resolver.spec.ts, apps/api-journeys/src/app/modules/block/gridItem/gridItem.resolver.spec.ts, apps/api-journeys/src/app/modules/block/icon/icon.resolver.spec.ts, apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts, apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.spec.ts, apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts, apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts, apps/api-journeys/src/app/modules/block/typography/typography.resolver.spec.ts, apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts, apps/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.resolver.spec.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Added new roles to our role guard. We've added the ability to check if the user is currently a publisher and if a journey is currently a template.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28496234/todos/5168827856)
=> fix: extend role guard

apps/api-journeys/src/app/modules/journey/journey.service.spec.ts, apps/api-journeys/src/app/modules/journey/journey.service.ts
Fix service that wasn't getting featured journeys
=> fix: fetch public templates

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/journey/journey.graphql, apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.ts, apps/api-journeys/src/app/modules/journey/journey.service.spec.ts, apps/api-journeys/src/app/modules/journey/journey.service.ts
Gets all templates for any user with publisher role
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28496234/todos/5168910331)
=> feat: fetch publisher templates

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/journey/journey.graphql, apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.ts, libs/nest/database/src/lib/BaseService.ts
This updates template
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28496234/todos/5142646864)
=> feat: create journeyTemplate - makes a journey a template or not

apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Updated admin journey query to be checking if journey is a template and is userRole is publisher
=> fix: admin journey query

libs/journeys/ui/src/libs/action/action.spec.ts, libs/journeys/ui/src/libs/action/action.ts
=> fix: window external link

apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Updated journeyTemplates roleguard argument from using Ids to Id. This was causing the mutation to not work when called
=> fix: journey template roleguard argument

apps/journeys-admin/pages/library/[journeyId].tsx, apps/journeys-admin/pages/library/index.tsx, apps/journeys-admin/pages/templates/[journeyId].tsx, apps/journeys-admin/pages/templates/[journeyId]/edit.tsx, apps/journeys-admin/pages/templates/index.tsx
Refactors the structure of pages use by templates into: /library (for public) and /templates (for publishers)
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28980303/todos/5252812103)
> - /library
> - /library/[journeyId]
> - /templates
> - /templates/[journeyId]
> - /templates/[journeyId]/edit
=> refactor: template pages

apps/api-journeys/src/app/lib/roleGuard/roleGuard.ts
=> fix: role guard logic

apps/api-journeys/src/app/modules/action/action.resolver.ts, apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.ts, apps/api-journeys/src/app/modules/block/block.resolver.ts, apps/api-journeys/src/app/modules/block/button/button.resolver.ts, apps/api-journeys/src/app/modules/block/card/card.resolver.ts, apps/api-journeys/src/app/modules/block/icon/icon.resolver.ts, apps/api-journeys/src/app/modules/block/image/image.resolver.ts, apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.ts, apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts, apps/api-journeys/src/app/modules/block/step/step.resolver.ts, apps/api-journeys/src/app/modules/block/typography/typography.resolver.ts, apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Add the roleguard check for publishers
=> fix: mutations to do a roleguard publisher check

apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx, apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx, apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28980303/todos/5258047073)
=> refactor: nav menu icons

apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx, apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.spec.tsx, apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.stories.tsx, apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
Nav menu item takes selected prop to determine color
=> refactor: nav menu item select

apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx, apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.spec.tsx, apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationListItem/NavigationListItem.tsx
Add aria-selected to navigationListItem
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29147486/todos/5302095064)
=> feat: add aria selected to nav listitem

apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx, apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx, apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
Refactor to make the way we render loading cards more clean
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29147486/todos/5302094754)
=> refactor: journey lists loading cards

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/video/video.graphql, apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts, apps/api-journeys/src/app/modules/block/video/video.resolver.ts, apps/journeys-admin/__generated__/BlockFields.ts, apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts, apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts, apps/journeys-admin/__generated__/GetJourney.ts, apps/journeys-admin/__generated__/JourneyFields.ts, apps/journeys-admin/__generated__/VideoBlockCreate.ts, apps/journeys-admin/__generated__/VideoBlockUpdate.ts, apps/journeys-admin/__generated__/VideoFields.ts, apps/journeys-admin/__generated__/globalTypes.ts, apps/journeys/__generated__/BlockFields.ts, apps/journeys/__generated__/GetJourney.ts, apps/journeys/__generated__/JourneyFields.ts, apps/journeys/__generated__/VideoFields.ts, apps/watch-admin/__generated__/BlockFields.ts, apps/watch-admin/__generated__/JourneyFields.ts, apps/watch-admin/__generated__/VideoFields.ts, apps/watch/__generated__/BlockFields.ts, apps/watch/__generated__/JourneyFields.ts, apps/watch/__generated__/VideoFields.ts, libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts, libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts, libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
- [Video Block Query](https://3.basecamp.com/3105655/buckets/29264588/todos/5317253532)
- add videoUrl to videoBlock on api-journeys
- [Video Block Create and Update Mutations](https://3.basecamp.com/3105655/buckets/29264588/todos/5317344605)
- add videoUrl to VideoBlockCreateInput
- add videoUrl to VideoBlockUpdateInput
- validate videoUrl matches YouTube
=> feat: add video url to video block

apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx, apps/journeys-admin/src/components/JourneyList/JourneyCard/StatusChip/StatusChip.tsx
Fix chip style
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29147486/todos/5322145448)
=> fix: status chip style

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/textField/textField.graphql, apps/journeys-admin/__generated__/ActionDelete.ts, apps/journeys-admin/__generated__/BlockDelete.ts, apps/journeys-admin/__generated__/BlockDeleteForBackgroundImage.ts, apps/journeys-admin/__generated__/BlockDeleteForBackgroundVideo.ts, apps/journeys-admin/__generated__/BlockDeleteForPosterImage.ts, apps/journeys-admin/__generated__/BlockDeletePrimaryImage.ts, apps/journeys-admin/__generated__/BlockDuplicate.ts, apps/journeys-admin/__generated__/BlockFields.ts, apps/journeys-admin/__generated__/BlockOrderUpdate.ts, apps/journeys-admin/__generated__/DuplicatedBlock.ts, apps/journeys-admin/__generated__/GetJourney.ts, apps/journeys-admin/__generated__/JourneyFields.ts, apps/journeys-admin/__generated__/NewBlock.ts, apps/journeys-admin/__generated__/StepsOrderUpdate.ts, apps/journeys/__generated__/BlockFields.ts, apps/journeys/__generated__/GetJourney.ts, apps/journeys/__generated__/JourneyFields.ts, apps/watch-admin/__generated__/BlockFields.ts, apps/watch-admin/__generated__/JourneyFields.ts, apps/watch/__generated__/BlockFields.ts, apps/watch/__generated__/JourneyFields.ts, libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts, libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
[Model](https://3.basecamp.com/3105655/buckets/29284565/todos/5321894611)
=> feat: textfield block model

apps/journeys-admin/src/components/JourneyView/JourneyView.tsx, apps/journeys-admin/src/components/JourneyView/SocialImage/SocialImage.tsx
Currently, placeholder image is not rendering properly.
Follow the conversation at
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29147486/todos/5294620579#__recording_5331215871)
=> fix: placeholder image

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/event/event.module.ts, apps/api-journeys/src/app/modules/event/textField/textField.graphql, apps/api-journeys/src/app/modules/event/textField/textField.resolver.spec.ts, apps/api-journeys/src/app/modules/event/textField/textField.resolver.ts
[SubmissionEvent](https://3.basecamp.com/3105655/buckets/29284565/todos/5336193453)
=> feat: textfield submission event

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/textResponse/textResponse.graphql, apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.spec.ts, apps/api-journeys/src/app/modules/event/textResponse/textResponse.graphql, apps/api-journeys/src/app/modules/event/textResponse/textResponse.resolver.spec.ts
`content` not needed, renamed submission event `field` prop to `value`
=> fix: remodel text response

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/textResponse/textResponse.graphql, apps/api-journeys/src/app/modules/event/textResponse/textResponse.graphql
Updating the text response block to include minRows.
[TextResponseBlock](https://3.basecamp.com/3105655/buckets/29284565/todos/5321889127)
=> fix: text response minRows

.prettierignore, .storybook/static/mockServiceWorker.js
Prettier Linting error in main when installing msw.
CI should test this automatically.
=> fix: msw prettier error

.github/workflows/main.yml
=> ci: vr ignore translation files

apps/api-journeys/src/app/lib/roleGuard/roleGuard.ts, apps/api-journeys/src/app/modules/action/action.resolver.ts, apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.ts, apps/api-journeys/src/app/modules/block/block.resolver.ts, apps/api-journeys/src/app/modules/block/button/button.resolver.ts, apps/api-journeys/src/app/modules/block/card/card.resolver.ts, apps/api-journeys/src/app/modules/block/icon/icon.resolver.ts, apps/api-journeys/src/app/modules/block/image/image.resolver.ts, apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.ts, apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts, apps/api-journeys/src/app/modules/block/step/step.resolver.ts, apps/api-journeys/src/app/modules/block/textResponse/textResponse.resolver.ts, apps/api-journeys/src/app/modules/block/typography/typography.resolver.ts, apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Add back end changes to allow publishers to edit each others templates https://github.com/JesusFilm/core/pull/868
=> feat: update journey admin mutation guards

apps/journeys-admin/src/components/JourneyView/DatePreview/DatePreview.spec.tsx, apps/journeys-admin/src/components/JourneyView/DatePreview/DatePreview.tsx
Refactor to use next link to open in a new window
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29147486/todos/5355291937)
=> fix: preview button opens link in a new tab

apps/journeys-admin/pages/journeys/[journeyId].tsx, apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx, apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx, apps/journeys-admin/pages/publisher/[journeyId].tsx, apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx, apps/journeys-admin/pages/publisher/index.tsx, apps/journeys-admin/pages/reports.tsx, apps/journeys-admin/pages/templates/[journeyId].tsx, apps/journeys-admin/pages/templates/index.tsx, apps/journeys-admin/src/components/JourneyView/JourneyView.stories.tsx, apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx, apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.stories.tsx, apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx, apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
Used to be selected of page title. This PR changes it to select of the URL
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29147486/todos/5289546922)
=> refactor: nav menu item selection

apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.ts
Add text response block type to action resolvers
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29284565/todos/5369140822)
=> fix: add text response block type to action

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
Update action component for text response block
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29284565/todos/5369140822)
=> fix: update action component for text response (front end)

apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.stories.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/BlocksTab.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.stories.tsx, apps/journeys-admin/src/components/Editor/Editor.spec.tsx, apps/journeys-admin/src/components/Editor/Editor.stories.tsx
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29494894/todos/5383160568)
=> fix: remove text response block flag

apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts, apps/api-journeys/src/app/modules/block/video/video.resolver.ts
We're currently receiving the default quality of the image from YouTube. This fix should get the high res quality of the image
=> fix: high res youtube image

infracost.yaml
Add the infracost to PRs to get an idea of how much PRs which change our AWS billing. Great to have the visibilty.
=> feat: add infracost config

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundColor/BackgroundColor.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/Card.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/ColorDisplayIcon/ColorDisplayIcon.spec.tsx, apps/watch/src/components/ThemeProvider/ThemeProvider.stories.tsx, libs/journeys/ui/src/components/Card/Card.spec.tsx, libs/journeys/ui/src/components/Card/Card.tsx, libs/shared/ui/src/components/ThemeDecorator/ThemeDecorator.tsx, libs/shared/ui/src/components/ThemeProvider/ThemeProvider.spec.tsx, libs/shared/ui/src/components/ThemeProvider/ThemeProvider.tsx, libs/shared/ui/src/libs/themes/base/theme.stories.tsx, libs/shared/ui/src/libs/themes/index.ts
Refactor themes to be a function that accepts the theme name and theme mode. These changes are needed for RTL support, specifically for the typography fonts
=> refactor: themes to get theme

.storybook/preview-head.html, apps/journeys/pages/_document.tsx, libs/shared/ui/src/libs/themes/base/tokens/typography.ts
The typography issue turned out to be complicated. We came to a decision that uses Arial font as primary for Urdu. 
Please follow the conversation in this todo
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29688713/todos/5413251837#__recording_5466008250)
=> fix: update urdu typography

apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx, apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx, apps/journeys-admin/src/components/Editor/Canvas/Canvas.spec.tsx, apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx, apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Cards/Cards.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.spec.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx, apps/journeys-admin/src/components/Editor/Editor.stories.tsx, apps/journeys-admin/src/components/Editor/JourneyEdit/JourneyEdit.tsx, apps/journeys-admin/src/components/FramePortal/FramePortal.spec.tsx, apps/journeys-admin/src/components/FramePortal/FramePortal.stories.tsx, apps/journeys-admin/src/components/FramePortal/FramePortal.tsx, apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedCardPreview/EmbedCardPreview.tsx
RTL styling is not getting applied to our blocks within an iframe
](https://3.basecamp.com/3105655/buckets/29688713/todos/5431701777)
Check between Admin and Storybook
=> fix: canvas styling 

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/visitor/visitor.graphql, apps/api-journeys/src/app/modules/visitor/visitor.resolver.spec.ts
- Change visitor.messengerNetwork to visitor.messagePlatform
- Change visitor.messengerId to visitor.messagePlatformId
=> refactor: visitor change messenger network to message platform

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/event/button/button.graphql, apps/api-journeys/src/app/modules/event/button/button.resolver.spec.ts, apps/api-journeys/src/app/modules/event/button/button.resolver.ts, apps/api-journeys/src/app/modules/event/event.module.ts, apps/api-journeys/src/app/modules/visitor/visitor.graphql
- change ChatOpenedEvent to ChatOpenEvent
- update visitor messagePlatform field on ChatOpenEventResolver when null
=> refactor: change to chat open event

apps/api-journeys/src/app/modules/event/event.service.ts
fix getAllByVisitorId event service
=> fix: add key as id to get all by visitor id

apps/docs/docs/06-quick-links.md
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29689605/todos/5530799874)
- Links to core developer and production environments
- Links to github and basecamp
=> docs: add quick links

apps/watch/pages/index.tsx, apps/watch/src/components/IntroText/IntroText.spec.tsx, apps/watch/src/components/IntroText/IntroText.stories.tsx, apps/watch/src/components/IntroText/IntroText.tsx, apps/watch/src/components/IntroText/index.ts
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29689605/todos/5520704018)
=> feat: intro text

apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts, apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Enable videoId and videoVariantLanguageId to be nullable
=> fix: video block schema

apps/docs/docs/03-basics/03-frontend/04-storybook/index.md
Write some more about storybook naming
=> docs: add in about story naming

.github/workflows/main.yml
=> ci: vr fetch depth, remove redundant step

.github/workflows/main.yml, apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/video/video.graphql, apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts, apps/api-journeys/src/app/modules/block/video/video.resolver.ts, apps/journeys-admin/__generated__/globalTypes.ts
Adding the objectFit field to VideoBlock as part of this [ticket](https://3.basecamp.com/3105655/buckets/29689605/todos/5529329941).
=> fix: add objectFit to video block

apps/api-journeys/src/app/modules/visitor/visitor.service.spec.ts, apps/api-journeys/src/app/modules/visitor/visitor.service.ts
=> fix: visitor list pagination

apps/api-gateway/schema.graphql, apps/api-videos/db/seed.ts, apps/api-videos/schema.graphql, apps/api-videos/src/app/__generated__/graphql.ts, apps/api-videos/src/app/modules/video/video.graphql, apps/api-videos/src/app/modules/video/video.resolver.ts, apps/api-videos/src/app/modules/video/video.service.spec.ts, apps/api-videos/src/app/modules/video/video.service.ts, apps/arangodb-bigquery-etl/bqexport.sh, apps/journeys-admin/__generated__/globalTypes.ts, apps/watch/__generated__/globalTypes.ts
This is the first of many PRs for api-video changes. This PR adds the label (arclight subtype)
https://3.basecamp.com/3105655/buckets/30316909/todos/5574989750
https://3.basecamp.com/3105655/buckets/30316909/todos/5574991395
=> feat: add label to api-video

apps/watch/__generated__/GetHomeVideo.ts, apps/watch/__generated__/GetVideo.ts, apps/watch/__generated__/GetVideoSiblings.ts, apps/watch/__generated__/GetVideos.ts, apps/watch/pages/[...slug].tsx, apps/watch/pages/index.tsx, apps/watch/src/components/Hero/VideoHero/VideoHero.tsx, apps/watch/src/components/HomeVideos/Card/HomeVideoCard.tsx, apps/watch/src/components/HomeVideos/testData.ts, apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx, apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx, apps/watch/src/components/ShareDialog/ShareDialog.tsx, apps/watch/src/components/Video/VideoCard/VideoCard.tsx, apps/watch/src/components/Videos/Videos.tsx, apps/watch/src/components/Videos/testData.ts
This removes usage of the deprecated video.type field.
=> feat: remove video.type from frontend

apps/api-gateway/schema.graphql, apps/api-videos/db/seed.ts, apps/api-videos/schema.graphql, apps/api-videos/src/app/__generated__/graphql.ts, apps/api-videos/src/app/modules/video/video.graphql
Removes orphaned code from api-videos
=> feat: final api-video changes

apps/api-videos/src/libs/arclight/arclight.spec.ts, apps/api-videos/src/libs/arclight/arclight.ts
Fixes 2 null conditions from api-video seed refactor
=> fix: api video seed

apps/watch/src/components/HeroOverlay/HeroOverlay.stories.tsx, apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.stories.tsx
=> fix: hero story paths

apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.stories.tsx, apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.tsx
Add missing tests for Video Content
**Requirements:**
Please visit the VideoContent Story at : https://612c2a83fdc2b2003a5c2eb7-shdeqijlfs.chromatic.com/?path=/story/watch-videocontentpage-videocontent--default
=> test: add test video content

apps/watch/src/components/VideosPage/Hero/VideosHero.tsx, apps/watch/src/components/VideosPage/SubHero/VideosSubHero.tsx, apps/watch/src/components/VideosPage/VideosPage.tsx
- fix loading indicator on videos page
- fix hero spacing
- load background image using next image 
=> fix: load and spacing on collections

apps/watch/next.config.js, apps/watch/pages/[part1]/[part2].tsx, apps/watch/pages/[part1]/[part2]/[part3].tsx, apps/watch/pages/index.tsx, apps/watch/pages/videos.tsx, apps/watch/src/libs/apolloClient/apolloClient.ts
- cache pages at build time
- revalidate every hour
- remove non-english locales until needed
=> feat: cache pages at build time

apps/watch/src/components/VideoCard/VideoCard.tsx, apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx, apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.spec.tsx, apps/watch/src/components/VideoContentPage/VideoContentCarousel/VideoContentCarousel.tsx, apps/watch/src/libs/utils/getLabelDetails/getLabelDetails.spec.ts, apps/watch/src/libs/utils/getLabelDetails/getLabelDetails.ts
Add child count label to getLabelDetails
=> fix: label details

apps/watch/pages/videos.tsx
This PR pre-loads languages for videos page selector
=> feat: getstaticprops languages

apps/api-gateway/src/environments/environment.prod.ts
=> fix: gateway cors jesusfilm

apps/api-gateway/src/environments/environment.prod.ts
Update cors for internal jesusfilm dns as well
=> feat: gateway jesusfilm cors 2

package-lock.json, package.json
This PR is to bump firebase-admin. It is currently preventing builds of journeys-admin on vercel.
vercel stage builds
=> chore: bump firebase-admin

apps/api-gateway/infrastructure/locals.tf, apps/api-journeys/infrastructure/locals.tf, apps/api-languages/infrastructure/locals.tf, infrastructure/environments/stage/data.tf
This PR resizes existing ECS tasks based on existing usage metrics. The tfs are already applied
=> feat: service sizing

.github/workflows/api-deploy-worker.yml, .github/workflows/api-gateway-prod-worker.yml, .github/workflows/api-gateway-stage-worker.yml, .github/workflows/crowdin.yml, .github/workflows/danger.yml, .github/workflows/etl-deploy.yml, .github/workflows/main.yml
This PR updates base github deployment actions to avoid the upcoming deprecation of set-state, save-state, and node 12
Deployments build
=> ci: update github base actions

infrastructure/.terraform.lock.hcl, infrastructure/main.tf, infrastructure/modules/aws/datadog/data.tf, infrastructure/modules/aws/datadog/datadog.tf, infrastructure/modules/aws/datadog/main.tf, infrastructure/modules/aws/ecs-task/main.tf
Add [datadog aws integration](https://docs.datadoghq.com/integrations/amazon_web_services/) using role delegation.
=> feat: add datadog aws integration

apps/watch/src/components/VideosPage/Hero/VideosHero.tsx
Changed the homepage title from "Our Full Collection" to "Jesus Film Collection"
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/30278084/todos/5713519746)
=> refactor: renamed allvideos title

apps/api-journeys/src/main.ts, apps/api-languages/src/main.ts, apps/api-users/src/main.ts, apps/api-videos/src/main.ts
api listener should not allow dynamic port assignment.
=> fix: port assignment

.github/workflows/api-deploy-worker.yml
=> fix: typo in git deployment

.github/workflows/api-gateway-prod-worker.yml
Error in ECS restart code for main gateway
=> fix: ecs restart typo

.github/workflows/api-deploy-prod.yml, .github/workflows/api-deploy-stage.yml, .github/workflows/api-deploy-worker.yml, .github/workflows/api-gateway-prod-worker.yml, .github/workflows/api-gateway-stage-worker.yml
This PR cleans up old variables and removes dependencies from api-gateway that are no longer needed with managed federation
=> feat: github deploy cleanup

infrastructure/environments/prod/main.tf, infrastructure/environments/stage/main.tf, infrastructure/modules/aws/ecs-task/main.tf, infrastructure/modules/aws/main.tf, infrastructure/modules/aws/variables.tf
Remove active VPNs since they are not needed for managed federation deployments
=> feat: remove vpns

apps/api-gateway/Dockerfile, apps/api-journeys/Dockerfile, apps/api-languages/Dockerfile, apps/api-users/Dockerfile, apps/api-videos/Dockerfile
It seems we were missing a logging dependency in our dockerfile
=> fix: datadog

apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx, apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx, apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx, apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.tsx, apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx, apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
Revert #1136 that is causing issues with the slider on production
=> revert: 1136 difficulties editing text

apps/journeys-admin/src/libs/firebaseClient/initAuth.ts
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245893/todos/5759818644)
=> feat: prod url redirects

apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-languages/src/app/__generated__/graphql.ts, apps/api-users/src/app/__generated__/graphql.ts, apps/api-videos/src/app/__generated__/graphql.ts
=> chore: update graphql types

apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.spec.tsx, apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.stories.tsx, apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx, apps/journeys-admin/src/components/Editor/ImageLibrary/index.ts
Created the base image library component for image selection
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31265497/todos/5759712556)
**Requirements**
Visit ImageLibrary Story
=> feat: image library

apps/api-gateway/schema.graphql, apps/api-media/infrastructure/locals.tf, apps/api-media/schema.graphql, apps/api-media/src/app/__generated__/graphql.ts, apps/api-media/src/app/app.module.ts, apps/api-media/src/app/modules/unsplash/image/image.graphql, apps/api-media/src/app/modules/unsplash/image/image.module.ts, apps/api-media/src/app/modules/unsplash/image/image.resolver.spec.ts, apps/api-media/src/app/modules/unsplash/image/image.resolver.ts, apps/api-media/src/app/modules/unsplash/image/image.service.spec.ts, apps/api-media/src/app/modules/unsplash/image/image.service.ts, apps/api-media/src/app/modules/unsplash/image/testData.ts
This allows us to query unsplash with graphql while keeping unsplash secrets secret
=> feat: api-media unsplash

apps/watch/src/components/VideosPage/LanguagesFilter/LanguagesFilter.spec.tsx, apps/watch/src/components/VideosPage/LanguagesFilter/LanguagesFilter.tsx, apps/watch/src/components/VideosPage/VideosPage.spec.tsx, apps/watch/src/components/VideosPage/VideosPage.tsx, libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
- Link to Basecamp Todo https://3.basecamp.com/3105655/buckets/31274526/todos/5761846481
=> feat: limit subtitle count

apps/api-gateway/schema.graphql, apps/api-media/schema.graphql, apps/api-media/src/app/__generated__/graphql.ts, apps/api-media/src/app/modules/unsplash/image/image.graphql
Remove nulls from unsplash response schema for frontend typing
=> feat: api-media unsplash schema update

apps/watch/pages/_app.tsx
Add Datadog RUM and GTM to watch.
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31485426/todos/5818997790)
=> chore: add datadog and gtm to watch

apps/watch/pages/_app.tsx
=> fix: set pages to no index no follow

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx, apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.spec.tsx, apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx, apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/CustomUrl/CustomUrl.spec.tsx, apps/journeys-admin/src/components/Editor/ImageLibrary/CustomImage/CustomUrl/data.ts, apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
A few tests have been commented out as the corresponding components was being worked on. Now that it's fixed. We've now removed the comments. And fixed the tests
=> test: remove commented tests

apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.spec.tsx, apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.stories.tsx, apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx, apps/journeys-admin/src/components/Editor/ImageLibrary/ImageLibrary.tsx, apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashGallery.tsx, apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/UnsplashList/UnsplashList.tsx, apps/journeys-admin/src/components/Editor/ImageLibrary/UnsplashGallery/index.ts
When clicking on the Unsplash Author it should redirect to their referral page. 
=> fix: unsplash author redirect

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/journeys-admin/__generated__/globalTypes.ts
Fix schema that got undone somehow
=> fix: bad schema

apps/api-media/src/app/modules/cloudflare/image/image.resolver.ts
=> fix: api-media force rebuild

apps/api-media/src/app/modules/cloudflare/image/image.resolver.ts, package-lock.json, package.json
Adds missing form-data package to package json FE dependency
=> fix: api media

apps/api-media/Dockerfile
Adds form-data to api-media dockerfile
=> fix: api-media

apps/api-gateway/schema.graphql, apps/api-media/schema.graphql, apps/api-media/src/app/__generated__/graphql.ts, apps/api-media/src/app/modules/unsplash/image/image.graphql, apps/api-media/src/app/modules/unsplash/image/image.resolver.spec.ts, apps/api-media/src/app/modules/unsplash/image/image.resolver.ts, apps/api-media/src/app/modules/unsplash/image/image.service.spec.ts, apps/api-media/src/app/modules/unsplash/image/image.service.ts
This is needed for unsplash api approval
=> feat: api-media unsplash dl

apps/watch/src/components/FilterContainer/FilterContainer.stories.tsx, apps/watch/src/components/FilterContainer/FilterContainer.tsx, apps/watch/src/components/VideosPage/VideosPage.spec.tsx, apps/watch/src/components/VideosPage/VideosPage.tsx
- [Link to Basecamp Todo
](https://3.basecamp.com/3105655/buckets/31485426/todos/5845464184)
=> feat: use query params

apps/watch/src/components/Footer/Footer.tsx, apps/watch/src/components/VideosPage/SubHero/VideosSubHero.tsx
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31485426/todos/5822310351) and https://3.basecamp.com/3105655/buckets/31485426/todos/5847406467 <- for copywriter
=> fix: remove medias from videos page

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/image/image.graphql, apps/journeys-admin/__generated__/globalTypes.ts
Somehow this portion of the api-media schema was reverted in main. This PR re-establishes it.
=> fix: unsplash schema

apps/api-gateway/router.prod.yaml
This PR whitelists apps on the jesusfilm.org domain for the graphql router
=> feat: jesusfilm whitelist

apps/watch/pages/_app.tsx
=> feat: remove seo blocking

apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
PR #1362 had a bad condition, this resolves it.
=> fix: open user journey mutation

apps/journeys-admin/pages/_app.tsx, apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx, apps/journeys-admin/src/components/HelpScoutBeacon/index.ts
Add HelpScout Beacon pop up to all admin pages
](https://3.basecamp.com/3105655/buckets/31822575/todos/5909544254)
Beacon pop up displays on all pages:
.
=> feat: helpScout Beacon

package-lock.json, package.json
Add mui data grid package
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31822546/todos/5931097124)
=> feat: add mui data grid

apps/journeys-admin/public/robots.txt, apps/journeys/public/robots.txt, apps/watch-admin/public/robots.txt, apps/watch/public/robots.txt
The lack of robots.txt is flooding us with bad calls. This aims to reduce them greatly. It is likely we will need to further tune them based on the results from this update
=> feat: initial robots.txt

apps/api-journeys/src/main.ts, apps/api-languages/src/main.ts, apps/api-media/src/main.ts, apps/api-users/src/main.ts, apps/api-videos/src/main.ts
New fix for null responses sometimes providing 502 between nestjs and ecs
=> fix: ecs alb 502

apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx, apps/watch/src/components/ShareDialog/ShareDialog.tsx
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31739517/todos/5909784046)
=> fix: let embed code work

apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31739517/todos/5927953091)
=> feat: create analytics events

apps/watch/public/robots.txt
This prevents all search crawling on preview/stage/non-jesusfilm.org sites
=> feat: watch robots disallow all

apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx, apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx, apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx, apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx, apps/journeys-admin/src/components/CardPreview/CardPreview.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/Cards/Cards.tsx, apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx, apps/journeys-admin/src/components/Editor/Editor.tsx, apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx, apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
This PR updates the journey edit view switcher, along with support for card preview, journey detail page, Horizontal select highlighting, querystring support
https://3.basecamp.com/3105655/buckets/31822561/todolists/5915289443
=> feat: journey edit view update

apps/journeys-admin/src/components/MediaListItem/MediaListItem.spec.tsx, apps/journeys-admin/src/components/MediaListItem/MediaListItem.stories.tsx, apps/journeys-admin/src/components/MediaListItem/MediaListItem.tsx, apps/journeys-admin/src/components/MediaListItem/index.ts
Common Media list item to be later used in the templates panel on landing page.
[Basecamp Todo
](https://3.basecamp.com/3105655/buckets/31822575/todos/5935619497)
=> feat: media list item

apps/api-journeys/db/seed.ts, apps/api-journeys/db/seeds/onboardingTemplates.ts
Placeholder templates for the template panel in dev / stage environments
](https://3.basecamp.com/3105655/buckets/31822575/todos/5924291563)
=> feat: seed onboarding templates

apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
There is a condition which allows multiple route pushes to journey edit view. This corrects it.
Spec test for branch will be in social preview, as there are no ways to currently test implementation in main
=> fix: view update route

apps/journeys-admin/src/components/TermsAndConditions/TermsAndConditions.stories.tsx
=> fix: add flag provider to terms and condition story

apps/api-journeys/src/app/modules/visitor/visitor.service.spec.ts, apps/api-journeys/src/app/modules/visitor/visitor.service.ts
Fix get visitor with _key
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31822546/todos/5960124439)
=> fix: query visitor by key

apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx, apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.tsx
=> fix:  update gtm

apps/api-journeys/src/app/modules/visitor/visitor.service.ts
Fix filter logic for visitor pagination
=> fix: visitor pagination

apps/api-videos/src/app/modules/video/video.resolver.spec.ts, apps/api-videos/src/app/modules/video/video.resolver.ts
```gql
query {
video(id: "1_jf-0-0") {
id
variant(languageId: "3934") {
language {
id
}
}
}
}
```
this query works in production.
```gql
query($languageId: ID!) {
video(id:"1_jf-0-0") {
id
variant(languageId: $languageId) {
language {
id
}
}
}
}
```
```JSON
{"languageId": "3934"}
```
this query is broken in production but fixed by https://github.com/JesusFilm/core/pull/1436
```gql
query($customLanguageId: ID!) {
video(id:"1_jf-0-0") {
id
variant(languageId: $customLanguageId) {
language {
id
}
}
}
}
```
```JSON
{"customLanguageId": "3934"}
```
this query is broken in production and in https://github.com/JesusFilm/core/pull/1436.
```gql
query {
video(id: "jesus/english", id: slug) {
id
variant(languageId: "3934") {
language {
id
}
}
}
}
```
this query works in production and ignores …
=> fix: handle variable variant language id

apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx, apps/watch/src/components/ShareDialog/ShareDialog.tsx
Use ref id
Visit a video in different languages. Click embed. Copy/paste the url to the video into the browser. Ensure it plays.
=> fix: embed code respects language

apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
=> fix: remove watch prefix

apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
Journey lists and discovery journeys were taking up more width than intended. This PR limits the width
=> fix: journey list fixed width

apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
=> fix: sidescroll

tsconfig.base.json
Causing a lint error [here](https://github.com/JesusFilm/core/pull/1453#discussion_r1153814765) due to missing types from es2017, have verified on that PR that this will resolve the issue.
=> feat: update to es2020

apps/api-journeys/db/seed.ts, apps/api-journeys/db/seeds/nua1.ts
First card in nua is showing a block that was not intended to be there. The fix is to remove it from seed
=> fix: remove text response block in factorfiction card 1

apps/watch/src/components/VideosPage/VideosPage.spec.tsx
Test is timing out sometimes on github actions which is blocking a few PR's.
=> chore: skip flakey test

apps/api-gateway/schema.graphql, apps/api-languages/schema.graphql, apps/api-languages/src/app/__generated__/graphql.ts, apps/api-languages/src/app/app.graphql, apps/api-languages/src/app/app.module.ts, apps/api-languages/src/app/modules/country/country.graphql, apps/api-languages/src/app/modules/language/language.graphql, apps/api-videos/schema.graphql, apps/api-videos/src/app/__generated__/graphql.ts, apps/api-videos/src/app/app.graphql, apps/api-videos/src/app/app.module.ts, apps/api-videos/src/app/modules/video/video.graphql, package-lock.json, package.json
- add cache hints, response cache plugin, and cache control directives to api-languages
- add cache hints, response cache plugin, and cache control directives to api-video
=> feat: add apollo cache hints

libs/nest/database/src/lib/DatabaseModule.ts
Change serverside max sockets from 3 to 50.
=> fix: increase max sockets when connecting to arango

libs/nest/database/src/lib/DatabaseModule.ts
Reduce maxSockets until we have a better solution
=> feat: reduce max sockets

.devcontainer/post-create-command.sh, apps/api-gateway/Dockerfile, apps/api-gateway/router.prod.yaml
Add span tracing to api-gateway
=> chore: add datadog to router

apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx, apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
=> fix: show children on video content

apps/api-videos/src/app/modules/video/video.service.ts
=> fix: api-video cache fix

apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.handlers.ts, apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.spec.tsx, apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.stories.tsx, apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/VideoFromYouTube.tsx, apps/journeys-admin/src/components/Editor/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.tsx, apps/journeys-admin/src/components/Editor/VideoLibrary/VideoList/VideoListItem/VideoListItem.tsx
revert https://github.com/JesusFilm/core/pull/1507
=> revert: fix youtube recommended

apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx, apps/journeys-admin/src/components/NewPageWrapper/NavigationDrawer/NavigationDrawer.tsx, apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.spec.tsx, apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
Fix flag check for showing global reports
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/33281894/todos/6295904138)
=> fix: global reports flag

apps/api-journeys/db/seed.ts, apps/api-languages/db/seed.ts, apps/api-videos/db/seed.ts
redeploy api-journeys, api-languages, api-videos.
- update power bi token in api-journeys
- refresh cache of languages in api-videos
=> chore: trigger redeploy

apps/api-journeys/db/seed.ts
=> chore: redeploy api-journeys

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Footer/HostSidePanel/HostForm/HostForm.tsx, apps/journeys-admin/src/components/Editor/VideoLibrary/VideoDetails/VideoDetails.tsx, apps/journeys-admin/src/components/Editor/VideoLibrary/VideoLanguage/VideoLanguage.tsx
Fix z index of a drawer that opened over another drawer
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26802573/todos/6967665571)
=> fix: zindex for video details drawer

apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/CardStyling/CardStyling.tsx, apps/journeys-admin/src/components/JourneyFlow/JourneyFlow.tsx, apps/journeys-admin/src/components/JourneyFlow/edges/ButtonEdge.tsx, apps/journeys-admin/src/components/JourneyFlow/nodes/BaseNode.tsx
node button styling and drag anywhere to create node
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/35958553/todos/6968955588)
=> fix: node branching styling

libs/shared/ui/src/components/icons/GitBranch.tsx
added GitBranch icon required for journeyflow
=> feat: add branch icon

apps/journeys/src/components/Conductor/Conductor.tsx, apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx, apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx, apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx, libs/journeys/ui/src/components/Card/Card.tsx, libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx, package-lock.json, package.json
=> refactor: swipe

apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx, apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
Tests for `SwipeNavigation.tsx`
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/35958767/todos/7065655337)
=> test: swipe nav

apps/journeys/src/components/Conductor/Conductor.spec.tsx, apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRender.spec.tsx, apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx
Tests for `JourneyRenderer.tsx`
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/35958767/todos/7065648203)
=> test: journeyrenderer

libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx
Update broken test for `VideoEvents`
- [Link](https://3.basecamp.com/3105655/buckets/35958767/todos/7065664965) to BaseCamp Todo
=> test: video events

apps/journeys/src/components/EmbeddedPreview/EmbeddedPreview.spec.tsx, apps/journeys/src/components/VideoWrapperPaused/VideoWrapperPaused.spec.tsx, apps/journeys/src/components/VideoWrapperPaused/VideoWrapperPaused.tsx, libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.spec.tsx, libs/journeys/ui/src/components/Video/InitAndPlay/InitAndPlay.tsx, libs/journeys/ui/src/components/Video/Video.spec.tsx, libs/journeys/ui/src/components/Video/Video.stories.tsx
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/35958767/todos/7065664441)
=> test: initandplay

libs/journeys/ui/src/components/Step/Step.spec.tsx, libs/journeys/ui/src/components/Step/Step.tsx
- adds test to validate `stepViewEventCreate` only emits when `activeStep` is true
- adds tests to validate Seo changes based on `activeStep` and if first step
[Link](https://3.basecamp.com/3105655/buckets/35958767/todos/7065661942) to Basecamp Todo
=> test: step updates

apps/journeys-admin/src/components/CardPreview/CardList/CardWrapper/CardWrapper.spec.tsx, apps/journeys-admin/src/components/CardPreview/CardList/CardWrapper/CardWrapper.tsx, apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.tsx, apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx, apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx, apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx, apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx, apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.tsx, apps/journeys/src/components/Conductor/Conductor.spec.tsx, apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx, libs/journeys/ui/src/components/Card/Card.spec.tsx, libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx, libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx, libs/journeys/ui/src/components/Video/Video.spec.tsx, libs/journeys/ui/src/components/Video/Video.stories.tsx, libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx, libs/journeys/ui/src/components/VideoEvents/VideoEvents.spec.tsx, libs/locales/en/apps-journeys-admin.json
General types fixes
[- Conductor](https://3.basecamp.com/3105655/buckets/35958767/todos/7080144923)
[- misc fixes](https://3.basecamp.com/3105655/buckets/35958767/todos/7065656572)
=> test: misc fixes

apps/journeys/pages/embed/test/[journeySlug].tsx, apps/journeys/src/components/EmbeddedPreview/ClickableCard/ClickableCard.tsx, libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx, libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
iOS should still be able to interact with embed despite not being able to fullscreen.
=> fix: allow fullscreen video on ios

apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.spec.tsx
Fix cardwrapper tests
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/35958767/todos/7114365610)
=> fix: cardwrapper tests

apps/journeys-admin/src/components/CardPreview/CardList/CardWrapper/CardWrapper.spec.tsx, apps/journeys-admin/src/components/CardPreview/CardList/CardWrapper/CardWrapper.tsx, apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx, apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx, apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx, apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.spec.tsx, apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.tsx, apps/journeys/src/components/Conductor/Conductor.spec.tsx, apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.spec.tsx, apps/journeys/src/components/Conductor/JourneyRenderer/JourneyRenderer.tsx, apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx, libs/journeys/ui/src/components/Card/Card.spec.tsx, libs/journeys/ui/src/components/StepHeader/PaginationBullets/Bullet/Bullet.tsx, libs/journeys/ui/src/components/Video/VideoControls/PlaybackIcon/PlaybackIcon.tsx
=> fix: final tidy up

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx, apps/journeys-admin/test/mockReactFlow.ts
- Adds required mocks for React Flow
- Adds test suite for `BaseNode`
- [Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145947690) to Basecamp Todo
=> test: add tests for base node

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ButtonBlockNode/ButtonBlockNode.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ButtonBlockNode/ButtonBlockNode.tsx
- Adds tests for `ButtonBlockNode`
- [Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145947859) to Basecamp Todo
=> test: button block node

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/FormBlockNode/FormBlockNode.spec.tsx
- Add tests for `FormBlockNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145948150) to Basecamp Todo
=> test: add tests for FormBlockNode

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/RadioOptionBlockNode/RadioOptionBlockNode.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/RadioOptionBlockNode/RadioOptionBlockNode.tsx
- Add tests for `RadioOptionBlockNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145948371) to Basecamp Todo
=> test: radio option block node

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.tsx
- Add tests for `SignUpBlockNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145948548) to Basecamp Todo
=> test: sign up block node

apps/api-gateway/schema.graphql, apps/api-journeys/Dockerfile, apps/api-journeys/db/Dockerfile, apps/api-journeys/db/migrations/20240313235947_20240313235945/migration.sql, apps/api-journeys/db/schema.prisma, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/block/step/step.graphql, apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts, apps/api-languages/Dockerfile, apps/api-languages/db/Dockerfile, apps/api-media/Dockerfile, apps/api-tags/Dockerfile, apps/api-tags/db/Dockerfile, apps/api-users/Dockerfile, apps/api-videos/Dockerfile, apps/api-videos/db/Dockerfile, apps/journeys-admin/__generated__/globalTypes.ts
add xy to step block and allow create and update mutations to specify an xy coordinate.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7145236876)
=> feat: add xy to step block

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/VideoBlockNode/VideoBlockNode.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/VideoBlockNode/VideoBlockNode.tsx
- Add tests for `VideoBlockNode`
- [Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145949786) to Basecamp Todo
=> test: video block node

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ActionNode/ActionNode.spec.tsx
- Adds tests for `ActionNode`
- [Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145947300) to Basecamp Todo
=> test: action node

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx
- Adds tests for `SocialPreviewNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145948840) to Basecamp Todo
=> test: social preview node

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Button/Button.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Form.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Image.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/ImageOptions.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioOption/RadioOption.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/SignUp/SignUp.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Step/Step.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Typography.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Video.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/CardTemplateDrawer.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/Drawer.tsx
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7145961243)
=> test: canvas properties

apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
Fix failing CardPreview test. `Actions` was renamed to `Goals` to rename the test accordingly also.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7145964108)
Test should pass
=> test: fix card preview test

apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx
- Refactors tests for `SocialPreview`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145955438) to Basecamp Todo
=> test: social preview

apps/journeys-admin/src/components/ContainedIconButton/ContainedIconButton.spec.tsx
Add test for slots image thumbnail
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7145964108)
=> test: contained icon button

apps/journeys-admin/src/components/Editor/Slider/Settings/Settings.spec.tsx
- Removes old tests and adds relevant tests
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145956226) to Basecamp Todo
=> test: refactor and update tests for Settings

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/CanvasDetails.spec.tsx
- Adds tests for `CanvasDetails`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145956683) to Basecamp Todo
=> test: canvas details

libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
- Refactor tests ordering to match reducer switch statement
- Add missing reducer tests
- Add EditorProvider test
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7145966040)
=> fix: editor provider tests

libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.spec.tsx, libs/journeys/ui/src/components/StepFooter/HostAvatars/HostAvatars.stories.tsx
Fix tests and stories for `HostAvatars` + some minor refactoring
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7145965621)
=> fix: host avatars

apps/journeys-admin/infrastructure/main.tf, infrastructure/modules/aws/ecs-task/main.tf, infrastructure/modules/aws/ecs-task/variables.tf
remove nestjs from nextjs projects for datadog logging
=> fix: add dd-source to ecs task

apps/journeys-admin/project.json
include next-logger.config.js in docker container for dist builds of journeys-admin.
=> fix: include logging level config

apps/api-journeys/src/app/app.module.ts, apps/api-languages/src/app/app.module.ts, apps/api-media/src/app/app.module.ts, apps/api-tags/src/app/app.module.ts, apps/api-users/src/app/app.module.ts, apps/api-videos/src/app/app.module.ts
Make pino Log Messages Appear with the Correct Status in Datadog: https://benlimmer.com/2020/10/23/make-pino-log-messages-appear-with-the-correct-status-in-datadog/
=> fix: api logging level

apps/journeys-admin/public/robots.txt
Allow facebook to connect to journeys admin
=> chore: allow facebook to connect

libs/journeys/ui/src/components/Step/Step.tsx
Useeffect wasn't properly handling which step was currently active out of the pre-rendered steps.
=> fix: page title

apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsList.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsListItem/GoalListItem.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Content/Social/SocialPreview.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ActionNode/ActionNode.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Credentials/Credentials.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/GoalDetails.spec.tsx, apps/journeys-admin/src/components/Editor/Toolbar/Items/StrategyItem/StrategyItem.spec.tsx, apps/journeys-admin/src/libs/TestEditorState/TestEditorState.tsx
Refactor to test dispatches through `TestEditorState` instead of dispatch mocks
=> refactor: dispatch tests

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.stories.tsx
- Adds stories for `SocialPreviewNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7150977725) to Basecamp Todo
=> feat: social preview node stories

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/VideoBlockNode/VideoBlockNode.stories.tsx
- Adds stories for `VideoBlockNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7150978348) to Basecamp Todo
=> feat: video block node stories

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/RadioOptionBlockNode/RadioOptionBlockNode.stories.tsx
- Adds stories for `RadioOptionBlockNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7233302824) to Basecamp Todo
=> feat: add stories for RadioOptionBlockNode

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SignUpBlockNode/SignUpBlockNode.stories.tsx
- Add stories for `SignUpBlockNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7150977470) to Basecamp Todo
=> feat: add stories for SignUpBlockNode

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/FormBlockNode/FormBlockNode.stories.tsx
- Adds stories for `FormBlockNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7150975384) to Basecamp Todo
=> feat: form block node stories

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ButtonBlockNode/ButtonBlockNode.stories.tsx
- Adds stories for `ButtonBlockNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7150975228) to Basecamp Todo
=> feat: add stories for ButtonBlockNode

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/TextResponseBlockNode/TextResponseBlockNode.stories.tsx
- Adds stories for `TextResponseBlockNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7150978166) to Basecamp Todo
=> feat: text response block node stories

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
- Changes path for `ToggleButtonGroup` story
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7155985418) to Basecamp Todo
=> feat: update ToggleButtonGroup story path

.devcontainer/post-create-command.sh, apps/api-gateway/Dockerfile, apps/api-gateway/router.prod.yaml, apps/api-gateway/routerSchema.json, apps/api-gateway/schema.graphql
- update router to 1.43.1
- update rover to 0.23.0
Developers will need to rebuild or run:
```sh
curl -sSL https://router.apollo.dev/download/nix/v1.43.1 | sh
mv router apps/api-gateway/
npm install -g @apollo/rover@0.23.0
```
=> chore: update gateway

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/Action.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/EmailAction/EmailAction.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/LinkAction/LinkAction.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateAction/NavigateAction.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateToBlockAction/NavigateToBlockAction.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
- Fix broken `Action` stories
- Update story paths for `Action` and subcomponents
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todosets/7145202277)
=> fix: action stories

apps/journeys-admin/src/components/Editor/Editor.stories.tsx
- fix `Editor` stories
- Updated story paths for component and subcomponents
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7150915598)
=> fix: editor stories

apps/journeys-admin/src/components/Editor/Slider/Slider.stories.tsx
Add stories for editor slider
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7150972088)
=> test: add slider stories

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ColorDisplayIcon/ColorDisplayIcon.stories.tsx
- Updates story path
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7155980178) to Basecamp Todo
=> refactor: color display icon story

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Icon.stories.tsx
- Updates the path and variants
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7155983503) to Basecamp Todo
=> refactor: canvas detail icon story

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/ColorDisplayIcon/ColorDisplayIcon.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/VideoBlockEditor.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoDetails/VideoDetails.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/CloudflareDetails/CloudflareDetails.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromCloudflare/VideoFromCloudflare.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/VideoFromLocal.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/YouTubeDetails/YouTubeDetails.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLanguage/VideoLanguage.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoList/VideoList.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoList/VideoListItem/VideoListItem.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoSearch/VideoSearch.stories.tsx
- Updates `VideoBlockEditor` story
- Updates paths for `VideoLibrary` stories
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7156076000) to Basecamp Todo
=> refactor: video block editor stories

apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/SignUpEdit/SignUpEdit.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/MoveBlock/MoveBlock.stories.tsx
Update story paths
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7150990679)
=> fix: canvas stories

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx
- Adds stories for `StepBlockNode`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7150977911) to Basecamp Todo
=> feat: step block node stories

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Video.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Video.tsx
- Update story paths
- Refactor stories to match current style of writing them
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7155963446)
=> test: video property stories

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Typography.stories.tsx
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7155962267)
=> fix: typography stories

.github/pull_request_template.md
Add more detailed PR template
n/a
n/a
=> refactor: commit template

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/HostTab/HostList/HostListItem/HostListItem.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Align/Align.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Color/Color.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Typography.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Variant/Variant.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/CustomImage/ImageUpload/ImageUpload.stories.tsx
Updates the final incorrect story paths in the editor
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7282052354)
Pull and run locally and ensure all files paths in editor match its story path
=> fix: paths

apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.spec.tsx, apps/journeys-admin/src/components/LanguageSwitcher/LanguageSwitcher.tsx, libs/locales/en/apps-journeys-admin.json
changed text
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071027/todos/7292636856)
_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design …
=> fix: change language text

libs/shared/ui/src/components/LanguageAutocomplete/LanguageAutocomplete.tsx
[[Link to Basecamp Todo] ](https://3.basecamp.com/3105655/buckets/37071027/todos/7287142862)
_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design choices, …
=> fix: add id to langauge search

apps/api-gateway/router.yaml
Enable us to connect to api-gateway on developer computer on other devices (ie. mobile) via the network.
Setting allow_any_origin:true
=> build: changed cors settings

.github/workflows/app-deploy.yml, apps/arclight-e2e/playwright.config.ts, apps/docs-e2e/playwright.config.ts, apps/journeys-admin-e2e/src/e2e/lighthouse/homepage.spec.ts, apps/journeys-e2e/playwright.config.ts, apps/nexus-admin-e2e/playwright.config.ts, apps/watch-e2e/playwright.config.ts, apps/watch-e2e/src/e2e/chapter.spec.ts
Please see [this run](https://github.com/JesusFilm/core/actions/runs/8797420511/job/24142291235) where we can find that tests are run and passing  …
=> test: enable e2e tests(disable snapshot tests). retry only twice

apps/arclight/src/app/v2/media-component-links/route.ts
media-component-links endpoint
initial endpoint with available data
none
=> feat: arclight media-component-links

apps/arclight/src/app/v2/metadata-language-tags/route.ts
arclight metadata-language-tags endpoint
Nearly complete skeleton for facade
None
=> feat: arclight metadata-language-tags

apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/route.ts
arclight media-components/language route
skeleton mapping for conversion
None
=> feat: arclight media-components language

apps/arclight/src/app/v2/media-component-links/[mediaComponentId]/route.ts
arclight endpoint for media-component-links single result
skeleton endpoint for arclight facade
None
=> feat: arclight media-component-links single

apps/journeys-admin/pages/templates/[journeyId].tsx, apps/journeys-admin/pages/templates/index.tsx
Fix teams dropdown in templates on initial login
load teams after user login happens
=> fix: admin-template-teams

apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsListItem/GoalsListItem.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/isActionBlock/isActionBlock.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/isActionBlock/isActionBlock.ts, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashGallery.tsx, apps/journeys-admin/test/mockReactFlow.ts
Tests for isActionBlock helper
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7356069477)
I did modify the logic for the helper to increase the fault tolerance. The null and undefined tests were failing with the old logic. The only place it's currently being used, could not call it with null or undefined, but just helps to future proof in case it is used elsewhere.
N/A
N/A
=> test: isActionBlock helper

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance …
=> refactor: node styles

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
Adds tests for `transformSteps`
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7356069723)
=> test: transform steps

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeIcon/StepBlockNodeIcon.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeIcon/StepBlockNodeIcon.stories.tsx
Adds test and stories for `stepBlockNodeIcon`
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7342269543)
=> test: stepBlockNodeIcon

apps/journeys-admin/src/libs/blockDeleteUpdate/blockDeleteUpdate.spec.ts
Adds additional test for `blockDeleteUpdate`
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7342270219)
=> test: block delete update

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/filterActionBlocks/filterActionBlocks.spec.ts
Test for filterActionBlocks.ts
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7356069258)
=> test: filterActionBlocks test

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, apps/api-journeys/db/Dockerfile
Fix node 20 devcontainer
use internal devcontainer node feature instead of nvm commands
none
=> fix: node 20

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/arrangeSteps/arrangeSteps.spec.ts
_No tests for the function arrangeSteps_
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7356068908)
_Add tests for the function arrangeSteps_
=> test: arrange steps

.storybook/main.js, apps/nexus-admin/.eslintrc.json, apps/nexus-admin/src/libs/storybook/config.tsx, apps/nexus-admin/src/libs/storybook/index.tsx, libs/shared/storybook/project.json
Nexus-admin needs to be setup for storybook.
Add storybook config for nexus-admin.
=> chore: nexus-admin storybook config

apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DuplicateBlock/DuplicateBlock.spec.tsx
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7342266949)
Added tests for modifying the cache on block and card duplication in DuplicateBlock.spec.tsx
=> test: duplicate block cache update tests

apps/api-languages/db/migrations/20240510220947_20240510220946/migration.sql, apps/api-languages/db/migrations/20240514002827_20240514002819/migration.sql, apps/api-languages/db/schema.prisma, apps/api-languages/db/seed.ts, apps/api-languages/project.json, apps/api-languages/schema.graphql, apps/api-languages/src/app/modules/language/language.graphql, apps/api-languages/src/app/modules/language/language.resolver.spec.ts, apps/api-languages/src/app/modules/language/language.resolver.ts
name field is jsonb[]
Move field to table relationship
remove jsonb[] field, rename table relationship, update seed
=> feat: languages bq import support part 2

apps/watch/pages/[part1]/[part2].tsx, apps/watch/pages/[part1]/[part2]/[part3].tsx
Catch when video or video variant is not found and display 404 error page to the user.
=> fix: video not found error

apps/api-gateway/schema.graphql, apps/api-journeys/db/migrations/20240513223637_20240513223633/migration.sql, apps/api-journeys/db/schema.prisma, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.graphql, apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.spec.ts, apps/journeys-admin/__generated__/globalTypes.ts
Backend change for the "Back to map" button ticket
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7292062740)
Added journeyFlowBackButtonClicked boolean field to JourneyProfile
=> feat: added journeyFlowBackButtonClicked to JourneyProfile

apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx, apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx, libs/journeys/ui/src/components/Card/Card.tsx
This PR solves issues where if the user created a divergent branch and tried to connect it back to the main branch, the journey would not navigate there. 
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7405814288)
Changed the conditional logic for when the journey can navigate forwards or backwards:
- Forward: if activeBlock?.nextBlockId not null
- Backwards: if blockHistory.length > 1
=> fix: navigation ending connections logic

apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.spec.tsx, apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.tsx
Custom domains appears and disappears randomly for some people 
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071027/todos/7415146034)
Remove LD flag to isolate out launch darkly flags not being interpreted properly as they aren't needed for this feature anymore.
=> fix: remove ld flag

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.stories.tsx, apps/journeys-admin/src/libs/useStepAndCardBlockCreateMutation/useStepAndCardBlockCreateMutation.mock.ts
Needed tests and stories for `NewStepButton` component
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7390514826)
Added tests and stories for `NewStepButton`
N/A
N/A
=> test: new step button

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteEdge/useDeleteEdge.spec.tsx, apps/journeys-admin/src/libs/useBlockActionDeleteMutation/useBlockActionDeleteMutation.mock.ts, apps/journeys-admin/src/libs/useStepBlockNextBlockUpdateMutation/useStepBlockNextBlockUpdateMutation.mock.ts
Need tests for `useDeleteEdge` hook
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7390523395)
Create tests for `useDeleteEdge` hook and mock responses for `useBlockActionDeleteMutation` and `useStepBlockNextBlockUpdateMutation`
N/A
N/A
=> test: useDeleteEdge

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.spec.tsx
Add tests for social node changing active slide when clicked on while already selected
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7390572810)
At unit test
n/a
n/a
=> test: active slide dispatch

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
Add tests for StepBlockNodeCard
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7390526757)
- Add unit tests
- Add stories
n/a
n/a
=> test: stepblock node card

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useUpdateEdge/useUpdateEdge.spec.tsx, apps/journeys-admin/src/libs/useNavigateToBlockActionUpdateMutation/useNavigateToBlockActionUpdate.mock.ts
Need tests for `useUpdateEdge`
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7390523525)
Add tests for `useUpdateEdge` and a mock for `useNavigateToBlockActionUpdate`
N/A
N/A
=> test: use update edge

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useCreateStep/useCreateStep.spec.tsx
Needed tests for `useCreateStep`
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7390523100)
Added tests for `useCreateStep`
N/A
N/A
=> test: useCreateStep

apps/journeys-admin/__generated__/UpdateJourneyFlowBackButtonClicked.ts, apps/journeys-admin/src/components/Editor/Slider/Slider.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Add tests for slider back button text
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7405500311)
Add tests and minor refactors
n/a
n/a
=> test: slider back button text

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx, apps/journeys-admin/src/components/Editor/data.ts
Add tests for journey flow
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7342267813)
- Add unit tests
- Fix stories
n/a
Was not able to test actual graph functions, may be best to test in e2e
=> test: journeyflow

apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx, apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.spec.tsx, apps/journeys-admin/src/components/Team/TeamOnboarding/TeamOnboarding.spec.tsx
Fixed failing tests related to last pr.
_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design …
=> fix: failing mock tests

libs/shared/ui/src/components/icons/Calendar2.tsx, libs/shared/ui/src/components/icons/Icon.tsx, libs/shared/ui/src/components/icons/icon.stories.tsx
Adding the calendar-02 icon from the NS Design System stratis icon set, which will be used on the Calendar button on the Resources header
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663178/todos/7488250924)
=> feat: added calendar2 icon

apps/watch/pages/watch/[part1]/[part2].tsx, apps/watch/pages/watch/[part1]/[part2]/[part3].tsx, apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.spec.tsx, apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx, apps/watch/src/components/Header/Header.tsx, apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx, apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx, apps/watch/src/components/ShareDialog/ShareDialog.tsx, apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
links in the audio language dialog are not redirecting correctly
- add /watch to audio language dialog url
- add /watch to share url
- remove unnecessary router in video container
=> fix: update router push

apps/api-gateway/schema.graphql, apps/api-languages/schema.graphql, apps/api-languages/src/app/__generated__/graphql.ts
missing graphql generation in prod
ran codegen
=> fix: missing graphql schema

libs/journeys/ui/src/components/Video/Video.tsx
unwanted zoom crop on portrait videos
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663057/todos/7502377449)
Remove the 300% scale
n/a
This change was originally added to increase video quality for mobile devices, but does not seem to be having the same effect it originally did and is therefor redundant.
=> refactor: video 100

apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.spec.ts, apps/api-journeys/src/app/modules/userJourney/userJourney.resolver.ts
journeyNotification is returning null on userJourney
updated resolver field to return correct response
=> fix: resolver field journey notifications

apps/api-languages/db/migrations/20240615005514_20240615005513/migration.sql, apps/api-languages/db/schema.prisma
Schema for arclight language audio previews
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663169/todos/7506032072)
=> feat: audio preview schema

apps/api-videos/db/migrations/20240619213007_20240619213005/migration.sql, apps/api-videos/db/schema.prisma
bible book model did not match bq well enough
update the model
=> fix: biblebook schema

apps/journeys-admin/pages/templates/[journeyId].tsx
Get journeys query wasn't working.
Add IdType
n/a
You should now be able to
=> fix: journeys querys

apps/api-analytics/Dockerfile, apps/api-analytics/src/main.ts, apps/api-analytics/src/yoga.ts, package-lock.json, package.json
uws is having issues with yoga plugins. 
```
Warning: uWS.HttpResponse writes must be made from within a corked callback.
See documentation for uWS.HttpResponse.cork and consult the user manual.
```
remove uws for now and reinvestigate in future.
=> refactor: remove uws from analytics

apps/watch/src/components/Header/Header.stories.tsx
Header.stories needs updating as we have made significant changes to Header during this cycle(most notably, rendering HeaderTabButtons)
[Link to Basecamp Todo - Header](https://3.basecamp.com/3105655/buckets/37663178/todos/7529758481)
- Apply light theme to header story
- use FlagsProvider to create a story which includes all of the HeaderTabButtons
- Mocked useRouter on the story to show the videos button being selected
=> feat: watch header and headertabbuttons stories

apps/watch/pages/watch/index.tsx, apps/watch/pages/watch/videos.tsx
Add video to watch
Slack Convo
https://jfp-digital.slack.com/archives/C02T3E4FTQF/p1719323641797149
_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design …
=> feat: add new video to watch page

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx, apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Change the background color of journey flow when in analytics mode
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663055/todos/7544678413)
Conditionally added styles to the reactflow `Background` component when the editor is in analytics mode
=> feat: analytics background

apps/api-journeys/src/app/modules/journey/journey.module.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Site creation was failing due to required modules not being provided. Never was creating sites for journey duplicates
- Add required modules
- Add site creation on journey duplicate
- Add unit tests
n/a
n/a
=> fix: site creation

apps/journeys-admin-e2e/src/e2e/discover/active-archived-trash.spec.ts, apps/journeys-admin-e2e/src/e2e/discover/journey-level-actions.spec.ts, apps/journeys-admin-e2e/src/e2e/discover/teams.spec.ts, apps/journeys-admin/next.config.js
Test: skip the failed tests for now - will be fixed later.
These are passing:
_Provide any additional information that might be useful to the …
=> test: skip the failed tests for now

apps/api-videos/db/migrations/20240625154813_20240625154812/migration.sql, apps/api-videos/db/schema.prisma
Need to add keywords to api videos to support arclight features.
=> feat: add keyword schema

apps/journeys-admin-e2e/src/pages/card-level-actions.ts, apps/journeys-admin-e2e/src/pages/journey-page.ts
Make wait time longer, tests taking longer than expected.
Increase wait time to 60 seconds.
=> test: wait for 60seconds

apps/journeys-admin-e2e/playwright.config.ts, apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
Tests some time are showing different results as env not able to run 4 tests in parallel. This PR to run 2 tests in paralle.
_Provide any …
=> test: run 2 tests in parallel to reduce load on env so tests can be reliable

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCard.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyAnalyticsCard/JourneyAnalyticsCardStat/JourneyAnalyticsCardStat.tsx
Match the styles given for journey analytics
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663055/todos/7555380596)
Update styles to match given design
=> refactor: journey analytics styles

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsDataPoint/AnalyticsDataPoint.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
Match styles given from design for step analytics
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663055/todos/7546621377)
Updated styles to match given design
=> refactor: step analytics typography styles

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNodeAnalytics/LinkNodeAnalytics.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663055/todos/7556409729)
_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could …
=> refactor: remove hover styles in analytics mode

apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CanvasFooter.tsx, apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CardAnalytics/CardAnalytics.tsx
Styles for the canvas card analytic component does not match the given design
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663055/todos/7546531995)
Updated styles to match given design
=> refactor: card analytic styles

apps/docs/docs/03-basics/03-frontend/05-visual-testing/index.md
Udpate documentation for when developers ask for UI reviews
=> docs: update visual test

apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/VideoBlockEditorSettings.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/VideoBlockEditorSettings.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/VideoBlockEditor.stories.tsx, libs/locales/en/apps-journeys-admin.json
Needed to re-add the info message for muted videos
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7586160023)
Re-added previous work
=> feat: add info message when unmuting autoplay videos

apps/api-analytics/src/__generated__/graphql.ts, apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/__generated__/graphql.ts, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/modules/action/action.graphql, apps/api-journeys/src/app/modules/action/action.resolver.spec.ts, apps/api-journeys/src/app/modules/action/action.resolver.ts, apps/api-journeys/src/app/modules/action/emailAction/emailAction.resolver.spec.ts, apps/api-journeys/src/app/modules/action/emailAction/emailAction.resolver.ts, apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts, apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts, apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts, apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts, apps/api-languages/schema.graphql
add parentBlock field to action.
=> feat: allow parent block to be returned from action

apps/api-languages/db/migrations/20240713034153_20240713034151/migration.sql
Bad Prisma generated migration in api-language
Fix migration sql
=> fix: bad prisma migration

.github/workflows/visual-test.yml
=> ci: remove chromatic

apps/journeys/src/components/Conductor/Conductor.tsx, apps/journeys/src/components/Conductor/HotkeyNavigation/HotkeyNavigation.spec.tsx, apps/journeys/src/components/Conductor/HotkeyNavigation/HotkeyNavigation.tsx, apps/journeys/src/components/Conductor/HotkeyNavigation/index.ts, apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx, libs/journeys/ui/src/components/Card/Card.tsx
When running a Journey as a slide deck, its hard to navigate.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7609697559)
Add hotkeys for navigating a journey
n/a
n/a
=> feat: add hotkey navigation for journeys

libs/journeys/ui/src/components/TextResponse/TextResponse.spec.tsx, libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
Prevent Text Response from submitting the same value
=> fix: prevent same value submission

apps/journeys-admin/next.config.js
Update the environment variable used in journeys admin from `PLAUSIBLE_URL` to `NEXT_PUBLIC_PLAUSIBLE_URL`
=> fix: udpate env plausible variable name

apps/journeys-admin/next.config.js, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.tsx, libs/locales/en/apps-journeys-admin.json
Bounce rate initially looks quite wrong, removing it for now until we have a solution to show it.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7619066966)
Removes the bounce rate stat from step analytics (this PR should get reverted if we find a solution to show this)
n/a
n/a
=> refactor: remove bounce rate

.github/workflows/app-deploy.yml, .github/workflows/ecs-frontend-deploy-prod-worker.yml, .github/workflows/ecs-frontend-deploy-stage-worker.yml, apps/arclight/project.json, apps/journeys-admin/project.json, apps/journeys/project.json, apps/nexus-admin/project.json, apps/watch/project.json
sourcemaps on ecs frontend projects aren't correctly uploading their sourcemaps nor are preview environments on the alias domain matching uploaded sourcemaps.
- split sourcemap uploading from deployment task
- call sourcemap task from app deploy and ecs front end deploy workflow
- upload without domain specificity
=> fix: sourcemap uploading

apps/journeys-admin/__generated__/BlockRestore.ts, apps/journeys-admin/src/components/Editor/utils/useBlockDeleteCommand/useBlockDeleteCommand.tsx, apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.mock.ts, apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.spec.tsx, apps/journeys-admin/src/libs/useBlockRestoreMutation/useBlockRestoreMutation.tsx
=> fix: apollo cache changes

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Journey flow bg color different to design
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7585966928)
Update journey flow background color
n/a
n/a
=> refactor: flow bg color

apps/journeys-admin/src/components/OnboardingPanel/OnboardingPanel.tsx, libs/shared/ui/src/libs/themes/journeysAdmin/tokens/components.ts
Need update for global journeys-admin button style for small variant
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7587520395)
Update style for the small button variant in the admin theme
n/a
n/a
=> feat: add style for button small variant

apps/api-journeys/src/app/emails/templates/JourneyAccessRequest/JourneyAccessRequest.tsx, apps/api-journeys/src/app/emails/templates/JourneyShared/JourneyShared.tsx, apps/api-journeys/src/app/emails/templates/JourneyShared/JourneySharedNoAccount/JourneySharedNoAccount.tsx, libs/nest/common/src/lib/email/components/ActionCard/ActionJourneyView/ActionJourneyView.tsx
Add feature to make journey invite thumbnails to be clickable
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7597996124)
Add button around the thumbnail elements
n/a
n/a
=> feat: email thumbnail clickable

validate-branch-name.config.js
support the new linear branch names
[lowercasename]/[team-name-3-characters]-[ticket-number]-some-ticket-name
=> fix: linear branch name change

apps/docs/docs/02-getting-started/03-microservice-databases.mdx
Documentation for new bigquery ingests in development
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213807/todos/7643289751)
=> feat: new ingest docs

apps/api-gateway/router.prod.yaml
Enable stdout logging for the apollo router (api-gateway).
=> feat: gateway stdout logging

apps/journeys/pages/api/robots.ts
Facebook share links not display social share details
allow robots for facebook and twitter
n/a
n/a
=> fix: social media crawl

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/BaseNode.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/BaseNode/index.ts, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/LinkNode/LinkNode.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
Needed to update the styles for the social preview node when in analytics mode
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7584807182)
Updated styles for the social preview node
=> feat: social preview analytic styles

.devcontainer/post-create-command.sh, apps/api-gateway/Dockerfile, apps/api-gateway/router.prod.yaml, apps/api-gateway/router.yaml, apps/api-gateway/routerSchema.json
update router to 1.51.0
fix configuration
add logging on all requests
add datadog tracing
=> chore: update router

renovate.json
Enable dependency scanning with renovatebot
=> feat: renovate

apps/journeys-admin/src/components/Editor/Toolbar/Items/CommandRedoItem/CommandRedoItem.tsx, apps/journeys-admin/src/components/Editor/Toolbar/Items/CommandUndoItem/CommandUndoItem.tsx, apps/journeys-admin/src/components/Editor/Toolbar/Items/Items.tsx, apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.stories.tsx, apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx, libs/shared/ui/src/components/icons/FlipLeft.tsx, libs/shared/ui/src/components/icons/FlipRight.tsx, libs/shared/ui/src/components/icons/Icon.tsx, libs/shared/ui/src/components/icons/icon.stories.tsx
Adds new icons for undo redo as requested. Moves the buttons to the left of toolbar.
=> fix: update arrow icons for undo redo

dangerfile.ts
renovatebot needs dangerfile config
change dependabot to renovatebot in dangerfile
=> feat: dangerfile dependabot

package-lock.json, package.json
=> revert: fix(deps): update dependency express to v4.19.2 [security]

validate-branch-name.config.js
Validate branch name was set for dependabot, 
changed to renovatebot
=> feat: renovate validate branch name

apps/journeys-admin/pages/onboarding-form.tsx, apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.spec.tsx, apps/journeys-admin/src/libs/checkConditionalRedirect/checkConditionalRedirect.ts
Formium cert out of date
onboarding form page will redirect straight to `/` when the form fails to fetch
n/a
n/a
=> fix: hide onboarding form

infrastructure/environments/prod/main.tf, infrastructure/environments/stage/main.tf
Datadog aurora is not pointing at core cluster
Point dd aurora at core cluster
Remove old database clusters
Terraform data is currently out of sync. Must be run manually.
DO NOT APPLY with Atlantis
=> feat: change datadog aurora

apps/journeys-admin/__generated__/GetSSRAdminJourney.ts, apps/journeys-admin/pages/journeys/[journeyId].tsx, apps/journeys-admin/src/components/Editor/Editor.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/NewStepButton/NewStepButton.tsx
Running this query on the server is super slow so it looks like nothing is happening!
=> perf: make admin journey query run client side

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
The JFD is not showing up when creating a new journey.
=> fix: journey flow block positions

apps/journeys-admin/__generated__/CardQuoteDelete.ts, apps/journeys-admin/__generated__/CardQuoteRestore.ts, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardQuote/CardQuote.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardQuote/CardQuote.tsx
card quote form optimistic response + undo/redo
=> feat: card quote form optimistic cache updates

apps/journeys-admin/__generated__/CardFormDelete.ts, apps/journeys-admin/__generated__/CardFormRestore.ts, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardForm/CardForm.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardForm/CardForm.tsx
card form optimistic response + undo/redo
=> feat: card template form optimistic cache updates 

apps/journeys-admin/__generated__/CardIntroDelete.ts, apps/journeys-admin/__generated__/CardIntroRestore.ts, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardIntro/CardIntro.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/CardTemplates/Templates/CardIntro/CardIntro.tsx
card intro optimistic response + undo/redo
=> feat: card template intro optimistic cache updates

libs/journeys/ui/src/components/Card/Card.spec.tsx, libs/journeys/ui/src/components/Card/Card.tsx
=> fix: expanded card video

apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx, apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx, apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Hide popover notifications for helpscout
=> refactor: hide popover

apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.ts
Video Variant editions were not getting persisted to the database
_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include …
=> fix: add edition to the transform

apps/api-videos/src/app/modules/importer/importerVideoVariants/importerVideoVariants.service.spec.ts
Api videos has a broken test after PR
fix it
=> fix: api-videos test

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeAnalytics/StepBlockNodeAnalytics.tsx
Plausible threshold too high for too many users
Lower threshold to 10 to try it out
=> refactor: plausible threshold 10

apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
It is looking for last card's bubble to active however as it's using branching - hence it wasn't active. So skipping it for now to apply full fix later.
_If you have made changes to external services, need to add additional values to Doppler, or need to add something new to the database, explain it here. This may include updates to third-party services, changes to infrastructure configuration, integration with external APIs, …
=> test: skip the test for now

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.stories.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Accordion/Accordion.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioOption/RadioOption.tsx
Needed an additional variant in the `Accordion` component
[Link to Linear Issue](https://linear.app/jesus-film-project/issue/ENG-622/add-a-new-variant-to-custom-drawer-accordion)
Add a new variant to `Accordion` component
=> feat: add a new variant to custom accordion

apps/api-gateway/schema.graphql, apps/api-journeys/src/__generated__/graphql.ts, apps/api-videos/schema.graphql, apps/api-videos/src/schema/video/video.ts
api-videos not returning video with correct variant.
=> fix: missing primary language id

apps/api-videos/src/schema/video/video.spec.ts, apps/api-videos/src/schema/video/video.ts
order video children by child ids.
=> fix: order video children

libs/journeys/ui/src/components/SearchBar/LanguageButton/LanguageButton.tsx, libs/journeys/ui/src/components/SearchBar/LanguageButton/index.ts, libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
Update the language button according to the designs from figma
=> feat: language button styling

apps/watch/src/components/TextFormatter/TextFormatter.spec.tsx, apps/watch/src/components/TextFormatter/TextFormatter.tsx, apps/watch/src/components/TextFormatter/index.ts, apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx, apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.tsx
On Video & Collection Descriptions
- add paragraphs
- add new lines
- add url links (hiding protocol and www)
- add email links
=> fix: encode carriage return

apps/journeys-admin-e2e/src/e2e/lighthouse/homepage.spec.ts
Noticed PWA score reduced to around 43, so updating to to be 40.
_Provide any additional information that might be useful to the reviewer in …
=> test: reduce pwa to 40

apps/api-media/db/migrations/20240903021350_20240903021348/migration.sql, apps/api-media/db/schema.prisma, apps/api-media/src/__generated__/pothos-types.ts
start merging api-tags into api-media
=> chore: migrate tags db into api-media

apps/watch/src/components/StrategiesView/StrategySections/StrategySections.tsx
Update the indexes that the strategies page are currently using
=> fix: update strategies indexes

libs/journeys/ui/src/components/Typography/Typography.tsx
proper consumption of the component prop in Mui Typography to fix this bug: 
https://linear.app/jesus-film-project/issue/ENG-884/journey-builder-formatting-issues
=> fix: journey builder formatting issues

apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts, apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Return plausible token for journey members
=> fix: plausible token ability

apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/EmbedJourneyDialog/EmbedJourneyDialog.tsx
`EmbedJourneyDialog` layout needed to be updated.
- Get rid of space between the embed code and terms of agreement
- Change terms of agreement link to have red colour
=> fix: embed journey layout

apps/journeys-admin/src/components/Editor/Toolbar/TitleDescriptionDialog/TitleDescriptionDialog.tsx, libs/locales/en/apps-journeys-admin.json
Design for `TitleDescriptionDialog` needed to be updated with the labels inside the textfield.
=> fix: move labels inside textfield

libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.spec.tsx, libs/journeys/ui/src/components/StepHeader/PaginationBullets/PaginationBullets.tsx
Center the pagination bullets in admin
=> refactor: admin pagination bullets

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/SocialPreviewNode/SocialPreviewNode.tsx, apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
journey map should be draggable in analytics mode 
=> fix: enable journey map draggable in analytics mode

apps/watch/src/components/ResourcesView/ResourceSections/ResourceCard/ResourceCard.spec.tsx, apps/watch/src/components/ResourcesView/ResourceSections/ResourceCard/ResourceCard.tsx, libs/journeys/ui/src/components/TemplateGalleryCard/TemplateGalleryCard.tsx
optimise quality and performance of images in watch resources page
=> fix: image url quality and optimization

package-lock.json
=> Revert "fix(deps): update dependency @nestjs/graphql to v12.2.0"

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.tsx
- Disables the default next step action for step block nodes for website mode
=> feat: disable style for default next step

apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
=> fix: failing test for toolbar

apps/api-media/src/schema/video/video.spec.ts, apps/api-media/src/schema/video/video.ts
Video languages are not working in journeys
fix graphql info searching for Hive
=> fix: video language graphql info

apps/api-gateway/.eslintrc.json, apps/api-gateway/gateway.config.ts, apps/api-gateway/gateway.prod.config.ts, apps/api-gateway/project.json, apps/api-gateway/tsconfig.app.json, apps/api-gateway/tsconfig.json, apps/api-media/src/yoga.ts, apps/api-users/src/yoga.ts, libs/nest/common/src/lib/firebaseClient/firebaseClient.ts, libs/yoga/src/firebaseClient/firebaseClient.ts
This pull request includes several changes to the `api-gateway`, `api-media`, and `api-users` applications, focusing on configuration updates, JWT handling, and type-checking improvements. The most important changes are summarized below.
* [`apps/api-gateway/.eslintrc.json`](diffhunk://#diff-a4a2c74b9c45ae6dd806dd77f2e922b0639e8420d5a738c38fbc614db97f5a4eR1-R21): Added ESLint configuration specific to the `api-gateway` application.
* [`apps/api-gateway/tsconfig.json`](diffhunk://#diff-ab72965309bc7da79f856b3de0eb7df41da672701d014fc8a1abf199648710c2R1-R15): Extended the base TypeScript configuration and added project references for incremental builds.
* [`apps/api-gateway/tsconfig.app.json`](diffhunk://#diff-4f1ce5751447c4f802cb6138ab676f4219d214798b1c1a599ab3c60c333ea370R1-R22): Added …
=> feat: add jwt validation to gateway

dangerfile.ts
Danger now longer needs to check for basecamp ticket now that we have moved to Linear. 
Remove ᵕ̈
=> chore: remove basecamp check

apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromYouTube/VideoFromYouTube.tsx
=> revert: regex pattern for youtube video ids

apps/journeys-admin/pages/_app.tsx
=> Revert "fix: force prod rebuild"

apps/arclight/src/app/v2/media-components/[mediaComponentId]/route.ts, apps/arclight/src/app/v2/media-components/route.ts
Need to use cloudflare images going forward for videos
Swap original arclight fields for new cloudflare ones
=> feat: arclight cloudflare images

apps/journeys-admin/src/components/Editor/Toolbar/Items/AnalyticsItem/AnalyticsItem.tsx, apps/journeys-admin/src/components/Editor/Toolbar/Items/Item/Item.tsx, apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Small fixes to spacing in toolbar as requested by Lyuba.
=> fix: tidy up spacing for toolbar

apps/api-gateway/Dockerfile, package-lock.json, package.json
This reverts commit eaa263f8a5de84ca0a2dc5f530241fd4cfd349fb.
There is an issue building dev, as well as a possible issue authenticating plausible
=> revert: "chore(deps): update ghcr.io/ardatan/hive-gateway docker tag to v1.0.9"

apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/MoveBlock/MoveBlock.tsx, apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
poll options can now be re-ordered
=> fix: poll options reorder

package-lock.json, package.json
jsondiffpatch npm package is no longer used
remove it
=> chore: remove jsondiffpatch

apps/api-media/src/schema/video/videoStudyQuestion/updateOrder.spec.ts, apps/api-media/src/schema/video/videoStudyQuestion/updateOrder.ts
StudyQuestion sort order didn't quite work right.
Simplify, but have a few extra db calls
=> fix: really fix studyQuestion sort order

package-lock.json, package.json
eslint-plugin-node was abandoned
replaced with new eslint-plugin-n
=> chore: remove deprecated eslint-plugin-node

apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Increase min zoom size of journey flow
=> refactor: increase flow min zoom

apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/EditProvider.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/EditProvider.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/TestEditProvider/TestEditProvider.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/TestEditProvider/index.ts, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/index.ts, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/layout.tsx
need to add an editing mode for video view page
added a provider to easily pass prop to whole page
=> feat: add edit provider to get isedit value 

apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.stories.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/index.ts, apps/videos-admin/src/components/ResizableTextField/ResizableTextField.spec.tsx, apps/videos-admin/src/components/ResizableTextField/ResizableTextField.stories.tsx, apps/videos-admin/src/components/ResizableTextField/ResizableTextField.tsx, apps/videos-admin/src/components/ResizableTextField/index.ts, apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
Not able to save video snippet.
- Added ability to save video snippet
- Created `ResizableTextField` common component
=> fix: save video snippet

apps/docs/docs/03-basics/03-frontend/07-algolia/02-algolia-wordpress-plugin.md
Algolia serves as a key tool for ResourceHub. Documentation is needed to explain how the WordPress Plugin interacts with both Algolia and Core.
=> docs: algolia wordpress integration

apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/Metadata.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.stories.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/VideoDescription.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoDescription/index.ts, apps/videos-admin/src/components/ResizableTextField/ResizableTextField.tsx, apps/videos-admin/src/libs/useAdminVideo/useAdminVideo.mock.ts
Not able to save video description.
- Added ability to save video description
- Replaced `<Textarea />` with `ResizableTextField />`
=> fix: save button for video description

apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Tabs/TabLabel/TabLabel.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Tabs/TabLabel/TabLabel.stories.tsx
Missing tests for `Tablabel.tsx`
- Added tests and stories for `Tablabel.tsx`
=> test: add tests for tab label

apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Tabs/TabContainer/TabContainer.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Tabs/TabContainer/TabContainer.stories.tsx
Missing tests for `TabContainer.tsx`
- Added tests for `TabContainer.tsx`
- Added stories for `TabContainer.tsx`
=> test: add tests for tab container

apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_EditProvider/EditProvider.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoImageAlt/VideoImageAlt.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInformation.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoSnippet/VideoSnippet.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Section/Section.spec.tsx
No test for fallback behaviour of `Section.tsx`
- Added unit test for section fallback
=> test: add test for section fallback

apps/videos-admin/src/app/[locale]/(dashboard)/settings/_Settings/Settings.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/settings/_Settings/Settings.stories.tsx, apps/videos-admin/src/libs/storybookConfig/videosAdminConfig.tsx
Missing tests for `Settings.tsx`
- Added test for `Settings.tsx`
- Added story for `Settings.tsx`
=> test: add tests for settings

apps/videos-admin/src/app/[locale]/(dashboard)/_Dashboard/Dashboard.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/_Dashboard/Dashboard.stories.tsx
Missing tests for `Dashboard.tsx`
- Added test for `Dashboard.tsx`
- Added story for `Dashboard.tsx`
=> test: add tests for dashboard

apps/arclight/project.json
Arclight not deploying to ECR
Re-add empty extract-translation command to project.json
=> fix: arclight aws deploy

apps/watch/src/components/Header/Header.tsx, apps/watch/src/components/Header/HeaderTabButtons/HeaderTabButtons.tsx, apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.spec.tsx, apps/watch/src/components/VideoContainerPage/ContainerHero/ContainerHero.tsx, apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.tsx
Requested to add the language selector to the series/collection video pages
- Added `AudioLanguageButton` to `ContainerHero` component
- Joined video count with video label separated by bullet
- Refactors to watch header responsiveness
=> feat: add audio language button to PageContainerHero

apps/api-gateway/schema.graphql, apps/api-journeys/schema.graphql, apps/api-journeys/src/app/__generated__/graphql.ts, apps/api-journeys/src/app/federation.graphql, apps/api-journeys/src/app/modules/visitor/visitor.graphql
Nest projects are on federation v1, which prevents needed use of interfaces in other projects
Add federation v2 schema and update generated files
=> chore: nest federation v2

apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
variant and children sections need to be outlined variant 
changed to outlined variant
=> fix: change children and variants to outlined variant

apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInfomation.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInformation.spec.tsx, apps/videos-admin/src/components/PublishedChip/PublishedChip.spec.tsx, apps/videos-admin/src/components/PublishedChip/PublishedChip.tsx, libs/locales/en/apps-videos-admin.json
change unpublished label
changed unpublished label to draft
=> fix: change draft label

apps/watch/src/components/WatchHomePage/HomeHero/HomeHero.tsx
This pull request includes changes to the `HomeHero` component in the `WatchHomePage`. The updates primarily involve adjustments to the layout and styling properties to improve responsiveness and alignment.
Styling and layout adjustments:
* [`apps/watch/src/components/WatchHomePage/HomeHero/HomeHero.tsx`](diffhunk://#diff-c0f8826b0b1e45645e9b2f6828128dca7a80e1f4a5b9040836f33d68286924b3L19-R19): Changed the height property from fixed values to `'50svh'` for better responsiveness.
* [`apps/watch/src/components/WatchHomePage/HomeHero/HomeHero.tsx`](diffhunk://#diff-c0f8826b0b1e45645e9b2f6828128dca7a80e1f4a5b9040836f33d68286924b3L47-R49): Updated the `Stack` component's direction, alignment, and justification properties to improve layout on different screen sizes.
=> fix: change hero location

apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/VideoInformation/VideoInfomation.tsx
UI feedback for label.
- Changed label of `segment` to `clip`
=> fix: change segment to clip

libs/journeys/ui/src/components/Card/ContainedCover/BackgroundVideo/BackgroundVideo.tsx, libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.spec.tsx, libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx, libs/journeys/ui/src/components/CardWrapper/CardWrapper.spec.tsx, libs/journeys/ui/src/components/CardWrapper/CardWrapper.tsx, libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPreview.tsx, libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/data.ts, libs/journeys/ui/src/components/Video/Video.spec.tsx, libs/journeys/ui/src/components/Video/Video.tsx, libs/journeys/ui/src/components/VideoWrapper/VideoWrapper.spec.tsx, libs/journeys/ui/src/components/VideoWrapper/VideoWrapper.tsx
=> Revert "chore: swap journeys UI to mediavideo "

apps/api-gateway/schema.graphql, apps/api-journeys-modern/schema.graphql, apps/api-journeys-modern/src/schema/mediaVideo/mediaVideo.ts
MediaVideo unions were not working with null videoId (new video block)
Make videoId nullable
=> fix: mediaunion new video

apps/api-analytics/Dockerfile, apps/api-journeys-modern/Dockerfile, apps/api-journeys/Dockerfile, apps/api-languages/Dockerfile, apps/api-media/Dockerfile, apps/api-users/Dockerfile
api-media is giving prisma errors in stage. Trying to catch before it's an issue
Updating docker files
=> fix: prisma in docker

package-lock.json
=> Revert "fix(deps): update material-ui monorepo"

package-lock.json
=> Revert "fix(deps): update apollo graphql packages"

apps/api-analytics/Dockerfile, apps/api-journeys-modern/Dockerfile, apps/api-journeys/Dockerfile, apps/api-languages/Dockerfile, apps/api-media/Dockerfile, apps/api-users/Dockerfile
Prisma 6.1 broke builds
Force 5 for now
=> fix: wrong prisma version

apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts, apps/journeys-admin-e2e/src/e2e/users/existing-user.spec.ts, package-lock.json
Several playwright tests are failing. Add 'fixme' to each of them
=> fix: skip failing playwright tests

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Icon.spec.tsx, apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/controls/Icon/Icon.tsx, package-lock.json
Instead of reading "Select an icon..." when no icon is selected, it will just say "None".
=> fix: default icon text for button icon property

apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
=> fix: skip failing playwright test

apps/journeys-e2e/src/e2e/journeys.spec.ts
=> fix: skip playwright test 

libs/journeys/ui/src/components/Card/utils/getFooterElements/getFooterElements.ts, libs/journeys/ui/src/components/StepFooter/StepFooter.tsx
Frontend part of ticket for removing like / share buttons and moving relevant items downwards.
=> feat: footer ui improvements

libs/journeys/ui/src/components/Card/utils/getFooterElements/getFooterElements.ts
FIX: Bad copypasting from previous PR ruined syntax and broke the css code.
=> fix: bad syntax and semantics

apps/api-journeys/db/migrations/20241225003421_20241225003419/migration.sql
missing migration in main
add migration file
=> chore: api journeys migration

apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/VideoChildren.spec.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/VideoChildren.stories.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoChildren/VideoChildren.tsx, apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
Video Admin child order not updating
Fix query params to use parent id
=> fix: video-admin child Ids

apps/arclight/src/app/v2/media-components/[mediaComponentId]/languages/route.ts, apps/arclight/src/app/v2/media-components/route.ts, apps/arclight/src/app/v2/media-languages/route.ts, package-lock.json
Some Arclight calls appear to be timing out.
Increase the timeout.
=> feat: increase timeout for slow endpoints

package-lock.json
=> revert: algolia

package-lock.json, package.json
Remove unused package (was used in cloudflare videos)
=> chore: remove unused tus-js-client

package-lock.json
This reverts commit 25c4ceaeddce537c94c9a4f5bb39cd27a5fe2680.
_Provide any additional information that might be useful to the reviewer in …
=> revert: update graphql-hive-gateway monorepo (#5206)

.cursorrules, apps/journeys-admin-e2e/src/pages/card-level-actions.ts, apps/journeys-admin-e2e/src/pages/register-Page.ts, libs/journeys/ui/src/components/SignUp/SignUp.spec.tsx, libs/shared/ui/src/components/ThemeProvider/ThemeProvider.spec.tsx, package-lock.json
=> revert: fix(deps): update material-ui monorepo

apps/journeys-admin-e2e/src/e2e/publisher-and-templates/publisher-and-templates.spec.ts
=> ci: disable broken template e2e

apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/NewTextResponseButton/NewTextResponseButton.spec.tsx
Changed "Text Input" to "Response Field" on NewTextResponseButton.spec
=> fix: newtextresponsebutton tests

workers/arclight-canary/wrangler.toml
this will setup canary to run in production.
=> feat: canary to production

apps/watch/src/components/WatchHomePage/SeeAllVideos/SeeAllVideos.tsx
Co-authored-by: autofix-ci[bot] <114827586+autofix-ci[bot]@users.noreply.github.com>
=> fix: see all button width

package-lock.json
=> revert:  tailwindcss monorepo to v4.1.11

.github/workflows/app-deploy.yml
…n and matrix building"
This reverts commit c84c4bff4b9686f4d15d9f44b4311df54a019fd9.
=> revert: accidental push

.github/workflows/housekeeping-label-feature-pr.yml
https://til.simonwillison.net/github-actions/creating-github-labels
=> fix: add rest

apps/journeys/app/api/chat/suggestions/route.ts, apps/journeys/src/components/AiChat/AiChat.tsx, apps/journeys/src/components/Conversation/Conversation.tsx, apps/journeys/src/components/Drawer/index.ts, apps/journeys/src/utils/contextExtraction.ts, libs/locales/en/apps-journeys.json
- removes unnecessary code
- fixes lint
=> refactor: clean up feature
