JesusFilm/core

- apps/api-gateway/schema.graphql
- apps/api-journeys/prisma/migrations/20210927192249_add_theme_mode_on_journey/migration.sql
- apps/api-journeys/prisma/schema.prisma
- apps/api-journeys/prisma/seed.ts
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/__generated__/types.ts
- apps/api-journeys/src/modules/block/index.spec.ts
- apps/api-journeys/src/modules/journey/__generated__/types.ts
- apps/api-journeys/src/modules/journey/index.spec.ts
- apps/api-journeys/src/modules/journey/index.ts
journey will now have a themeName and a themeMode. This will be used later too on card component where that will also be able to override the default themeName and themeMode for that particular card.
> add themeName and themeMode to journeys

- apps/journeys/src/components/Conductor/Conductor.stories.tsx
- apps/journeys/src/components/Conductor/Conductor.tsx
We should now be able to see the top/bottom shadows on cards and see the right edge of the last card.
Issue:
Fix with 4px bottom padding:
Fix with 8px bottom padding:
> Update Conductor styling

- apps/api-gateway/schema.graphql
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/__generated__/types.ts
- apps/api-journeys/src/modules/block/__generated__/types.ts
- apps/api-journeys/src/modules/block/index.spec.ts
- apps/api-journeys/src/modules/block/index.ts
- apps/api-journeys/src/modules/response/index.spec.ts
- apps/api-journeys/src/modules/response/index.ts
- no longer need to define resolvers when part of the extraAttrs json object
- split large block test into independent tests for each block type
> Simplify Resolvers

- apps/journeys/src/components/blocks/Video/Video.tsx
- Remove the use of makeStyles as it is deprecated in MUI v5
https://mui.com/styles/basics/
Ended up removing the styling entirely as it's not getting used at the moment.
> Remove styling from Video

- .storybook/preview.js
Updated the mobile / tablet viewports to use our breakpoints. 
There is no desktop breakpoint as this is the default view (click reset viewport)
You can also toggle between portrait and landscape mode by pressing the arrows between the dimensions.
These dimensions were built for viewing light/dark modes separately. 
^ Don't do this, just use the default view and resize your browser to the appropriate width. 
Final breakpoints we've decided are:
xs, mobile portrait: 0
sm, mobile landscape: 568+ 
md, tablet portrait: 768+ 
lg,  tablet landscape: 1024+ 
xl, laptop/desktop: 1200+
> Update storybook viewport toggles

- .storybook/preview.js
- libs/shared/ui/src/libs/themes/base/theme.stories.tsx
- libs/shared/ui/src/libs/themes/base/theme.ts
- libs/shared/ui/src/libs/themes/base/tokens/breakpoints.ts
- libs/shared/ui/src/libs/themes/base/tokens/spacing.ts
Fix issue where large mobiles 540x960 held horizontally would adopt Tablet (P) styles.
This was done by checking for min-height.
As a result, I've constrained which APIs are callable from breakpoint. 
No more `.down` or `.between` as the same styling can be achieved using just `.up` and `.only`
I only made the fix for horizontal mobiles adopting the style of Tablet (P) because this is a common size of device looking a real user data. (sm -> md)
Data on real user mobile sizes showed we don't get such large phones that vertically held mobiles would adopt Mobile (L) styles. (xs -> sm)
Only the largest tablets - iPad Pro and Surface Pro 3, when held vertically would display Tablet (L) modes. Due to the change occurring within the same type of device, no fix was deemed necessary. (md -> lg) …
> Use custom breakpoints - large mobile fix

- apps/journeys/src/components/Conductor/Conductor.tsx
- libs/shared/ui/src/libs/themes/base/theme.stories.tsx
- libs/shared/ui/src/libs/useBreakpoints/useBreakpoints.ts
.up() is considerably more useful than .only().
Consider the case where we want a component to render only on tablet and above - this can be done easily if useBreakpoint uses the .up() method. And this would be the most common use case.
Any checks already styling a component based on the .only() method can also be easily rewritten using only .up() checks. See the Conductor file for an example of refactoring.
> Change useBreakpoint to use .up method over .only

- apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
- apps/journeys-admin/src/components/Editor/Canvas/Canvas.stories.tsx
- apps/journeys-admin/src/components/Editor/Editor.stories.tsx
- apps/journeys-admin/src/components/JourneyView/CardView/data.ts
Would be nice to keep the mock data for these card previews in a central place...
Also this just fixes the parentBlockId references for block selection to work. It'd be nice to have the consolidated format for id's / id naming fixes done once in a shared data file..
> Fix Journey data id references

- .github/workflows/api-deploy-worker.yml
- .github/workflows/api-deploy.yml
This uses the branch from the main github action, allowing stage api to deploy properly
> fix: add branch to worker deployment

- apps/api-journeys/src/app/modules/block/card/card.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/card/card.resolver.ts
- apps/api-journeys/src/app/modules/block/step/step.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/step/step.resolver.ts
- apps/journeys-admin/__generated__/StepAndCardBlockCreate.ts
- apps/journeys-admin/pages/journeys/[journeySlug]/edit.tsx
- apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
- apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
- apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.tsx
- apps/journeys-admin/src/components/Editor/Editor.spec.tsx
- apps/journeys-admin/src/components/Editor/Editor.tsx
- apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.spec.tsx
- apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
- apps/journeys-admin/src/components/JourneyView/CardView/CardView.spec.tsx
- apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
- CardPreview should optionally have an add button that allows you to add a card.
- CardView and ControlPanel should opt into having the add button visible.
- Clicking a card in CardView should reroute you to the edit page with the selected step highlighted.
- Add default for fullscreen in Card Resolver.
- Add default for locked in Step Resolver.
- [Basecamp Todo](https://3.basecamp.com/3105655/buckets/26244166/todolists/4637157436)
> feature: adding card block

- apps/api-gateway/schema.graphql
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/journey/journey.graphql
- apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
- apps/api-journeys/src/app/modules/journey/journey.resolver.ts
- slug shouldn't be required on journey create
- try use title as slug on create
- if slug not unique add id to end of slug on create
- if slug not unique throw error on update
- [Link to Basecamp Todo #1](https://3.basecamp.com/3105655/buckets/26244166/todos/4641516321)
- [Link to Basecamp Todo #2](https://3.basecamp.com/3105655/buckets/26244166/todos/4641532533)
> feature: add automatic slug creation to journey

- apps/api-journeys/src/app/modules/block/block.resolver.ts
- libs/nest/database/src/lib/base.service.spec.ts
- libs/nest/database/src/lib/base.service.ts
block reordering was passing ids to the service
- [ x I have commented my code, particularly in hard-to-understand areas
> fix: block reorder ids as _keys

- apps/api-gateway/schema.graphql
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/action/action.graphql
- apps/api-journeys/src/app/modules/action/action.resolver.spec.ts
- apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.spec.ts
- apps/api-journeys/src/app/modules/action/linkAction/linkAction.resolver.ts
- apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.spec.ts
- apps/api-journeys/src/app/modules/action/navigateAction/navigateAction.resolver.ts
- apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.spec.ts
- apps/api-journeys/src/app/modules/action/navigateToBlockAction/navigateToBlockAction.resolver.ts
- apps/api-journeys/src/app/modules/action/navigateToJourney/navigateToJourney.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/block.module.ts
- apps/api-journeys/src/app/modules/block/button/button.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/button/button.resolver.ts
- apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/radioQuestion/radioQuestion.resolver.ts
- apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/signUp/signUp.resolver.ts
- apps/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/videoTrigger/videoTrigger.resolver.ts
Add parentOrderId to action so we can used optimised response in editing actions. This unblocks Siyang
[Basecamp](https://3.basecamp.com/3105655/buckets/26244169/todos/4632617491)
> fix: Add parentBlockId to action in api-journeys

- apps/api-gateway/schema.graphql
- apps/api-journeys/db/seeds/nua1.ts
- apps/api-journeys/db/seeds/nua2.ts
- apps/api-journeys/db/seeds/nua8.ts
- apps/api-journeys/db/seeds/nua9.ts
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/block/icon/icon.graphql
- apps/journeys-admin/__generated__/BlockFields.ts
- apps/journeys-admin/__generated__/ButtonBlockCreate.ts
- apps/journeys-admin/__generated__/GetJourney.ts
- apps/journeys-admin/__generated__/IconFields.ts
- apps/journeys-admin/__generated__/SignUpBlockCreate.ts
- apps/journeys-admin/__generated__/globalTypes.ts
- apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.spec.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.stories.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewButtonButton/NewButtonButton.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.spec.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.stories.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/BlocksTab/NewSignUpButton/NewSignUpButton.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/ControlPanel.spec.tsx
- apps/journeys/__generated__/BlockFields.ts
- apps/journeys/__generated__/GetJourney.ts
- apps/journeys/__generated__/IconFields.ts
- apps/journeys/__generated__/globalTypes.ts
- libs/journeys/ui/__generated__/globalTypes.ts
- libs/journeys/ui/src/components/Icon/Icon.spec.tsx
- libs/journeys/ui/src/components/Icon/Icon.tsx
- libs/journeys/ui/src/components/Icon/__generated__/IconFields.ts
- libs/journeys/ui/src/libs/transformer/__generated__/BlockFields.ts
Make iconName nullable instead of adding in a new enum value. Needs to be reviewed before Siyang can start Icon work.
Needed to add both FE and api changes in one else we get a codegen linting error.
> fix: make iconName nullable

- libs/journeys/ui/src/components/Button/Button.tsx
- libs/journeys/ui/src/components/Image/Image.tsx
- libs/journeys/ui/src/components/RadioQuestion/RadioOption/RadioOption.tsx
- libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.tsx
- libs/journeys/ui/src/components/SignUp/SignUp.tsx
- libs/journeys/ui/src/components/Video/Video.tsx
Previous I added a fab "Done" state #324  &  implemented it with TypographyBlock. This switches between "Edit" and "Done" fab modes when clicking between the other blocks.
There should be no "Done" / Inline edit mode for Video or Image. 
Should be e2e tested later. Only VR changes are the randomly generated thumbnail image changes.
> fix: switch back to edit fab when selecting another block

- apps/journeys-admin/__generated__/ButtonBlockUpdateContent.ts
- apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.spec.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.stories.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/index.ts
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
- libs/journeys/ui/src/components/Button/Button.spec.tsx
- libs/journeys/ui/src/components/Button/Button.tsx
Allow inline editing of the button label. No new line characters allowed in label.
[Basecamp](https://3.basecamp.com/3105655/buckets/26244169/todos/4709748729)
**Manual testing**
> feat: Inline edit button

- apps/journeys-admin/__generated__/TypographyBlockUpdateContent.ts
- apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.spec.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.stories.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/index.ts
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/index.ts
- apps/journeys/src/components/Conductor/Conductor.stories.tsx
- libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
- libs/journeys/ui/src/components/BlockRenderer/index.ts
- libs/journeys/ui/src/components/Card/Cover/Cover.tsx
- libs/journeys/ui/src/components/Typography/Typography.spec.tsx
- libs/journeys/ui/src/components/Typography/Typography.tsx
- libs/journeys/ui/src/components/index.ts
- libs/journeys/ui/src/index.ts
This creates the editable Typography Textfield and inline edit wrapper which switches between the editable / non-editable text blocks. 
Out of scope / nice to have for this PR is making the caret appear at the end of the text and pausing the blinking so we can see its position in VR tests.
[Basecamp](https://3.basecamp.com/3105655/buckets/26244169/todos/4632657595)
- Tested that double click took us to edit mode
- Clicking on the card + clicking done saved the progress. Clicking outside the card cancelled changes.
- We can support paragraphs within a TypographyBlock but whitespace at the start/end is stripped.
- Styling for all Typography variants is correct …
> feature: InlineEditWrapper and TypographyEdit component

- apps/api-gateway/schema.graphql
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/block/block.graphql
- apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/block.resolver.ts
- apps/api-journeys/src/app/modules/block/block.service.spec.ts
- apps/api-journeys/src/app/modules/block/block.service.ts
This allows for deletion of blocks without parentBlockIds
- https://3.basecamp.com/3105655/buckets/26244194/todolists/4719368538
Delete a block without a parentBlockId (currently not available in UI)
> fix: blockDelete null parentBlockId

- apps/journeys-admin/setupTests.tsx
- apps/journeys-admin/src/components/HorizontalSelect/HorizontalSelect.tsx
Simple scroll to center Horizontal Select on selected Card. `scrollIntoView` works for all browsers except IE. 
But won't center on Safari (scrolls just into view see below). A while ago we determined that we weren't as concerned for Safari as it wasn't a common web browser our users used. 
Perhaps this is ok for MVP? I'm also aware that we want to avoid package bloat where we can so didn't go to a scrolling library
[Basecamp](https://3.basecamp.com/3105655/buckets/26244194/todos/4732680217)
> fix: Center selected card on Horizontal Select

- .github/workflows/danger.yml
- .github/workflows/main.yml
Allow danger to run on more pull request related events. Also moves it out into its own workflow to be run manually if needed.
> ci: split danger into its own workflow

- apps/api-videos/db/seed.ts
ap-videos seed updated to allow importing video variants. HLS values were not being returned if android wasn't being set as the platform.
> fix: languages endpoint needs platform parameter

- apps/journeys-admin/__generated__/GetLanguages.ts
- apps/journeys-admin/src/components/Editor/VideoLibrary/LanguageFilter/Drawer/Drawer.tsx
should not compare booleans to booleans. Initially when this code was pushed through translation object was optional. This has since been updated in api-journeys. This updates the codegen for journeys-admin and fixes the lint error created by that change.
> fix: journeys-admin linting

- dangerfile.ts
currently, if the reviewer already approves the PR before Danger runs, danger fails. This updates danger to check both requested reviews and completed reviews are 0 before throwing an error.
> ci: danger to check existing reviews too

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
Remove extra divider between the video/image and selected file
[Basecamp todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752761176)
> refactor: removed extra divider

- apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
URL now gets cleared when the cover image is deleted
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752777424)
> fix: clears url on delete

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/BackgroundMedia.tsx
Removed useEffect to let the image tab stay open when the background image is deleted
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752765438)
> fix: image tab stays open when background image is deleted

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToBlockAction/NavigateToBlockAction.spec.tsx
Test was sometimes failing, on github. Think the problem is the card was not clickable as the machine running it did not have enough screen width to click the card specified in the test. Updated so that the action is tested for the first card. 
Hard to test if this issue is actually resolved, so keep an eye on it for the future
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4761555684)
> fix: flakey navigateToBlockAction spec

- libs/journeys/ui/src/libs/action/handleAction.spec.ts
- libs/journeys/ui/src/libs/action/handleAction.ts
Link action was not working. Added Link Action to handle action, so links are handled now
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752644386)
> feat: fix link action

- .devcontainer/Dockerfile
change default base image to `typescript-node:${VARIANT}-bullseye`
> chore: update base image to typescript-node 16-bullseye

- .github/workflows/danger.yml
- .github/workflows/main.yml
Use cache npm. Should speed up CI builds dramatically.
> ci: use cache npm

- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
Currently clicking on the edit button redirects you to JourneyEdit where it should be redirected to the SingleJourney page. As when you click Edit you're not technically editing a card but you're editing the journey
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4757380004)
> refactor: edit redirect link

- .devcontainer/docker-compose.yml
https://github.com/arangodb/arangodb/issues/15742
Arango 3.9.0 crashes on M1 macs. This drops back to 3.8.6 until we can get a better arm64 container for arango.
> fix: revert arango to 3.8.6

- apps/journeys-admin/__generated__/StepBlockNextBlockIdUpdate.ts
- apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
- apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
The user having to manually connect the blocks up using next block id when creating a new card, is both confusing and unintuitive. This PR makes it so that when a new card is created, the card immediately before the created card (if it isn't already connected to a card) will get its nextBlockId set as the id of the newly created card.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752753075)
> feat: link new card to previous card

- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioQuestionEdit/RadioQuestionEdit.tsx
- apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.spec.tsx
- apps/journeys-admin/src/components/Editor/Canvas/SelectableWrapper/SelectableWrapper.tsx
Actions on buttons / sign up / radio option were still triggering on admin mode as stopPropogation on the SelectableWrapper didn't trigger before they are fired due to event bubbling.
This PR stops the propagation on event capture - before they are fired and reworks the logic so child blocks (RadioOption) still get selected/edited when container blocks (RadioQuestion) are clicked.
https://dev.to/eladtzemach/event-capturing-and-bubbling-in-react-2ffg
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4810871664)
> fix: button/radioOption/sign up link actions triggering onClick in admin

- apps/watch-admin/.env.production
- apps/watch-admin/pages/api/login.tsx
- apps/watch-admin/pages/api/logout.tsx
- apps/watch-admin/public/site.webmanifest
- apps/watch-admin/setupTests.tsx
- apps/watch-admin/src/libs/apolloClient/cache.ts
- apps/watch-admin/tsconfig.json
This fixes the missing watch-admin api pages for proper sign-in/out
> fix: watch admin api

- apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
- apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
- apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
- apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.test.tsx
- apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/CardWrapper.tsx
- apps/journeys-admin/src/components/Editor/Canvas/CardWrapper/index.ts
- apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.test.tsx
- apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/VideoWrapper.tsx
- apps/journeys-admin/src/components/Editor/Canvas/VideoWrapper/index.ts
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.stories.tsx
- apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
- libs/journeys/ui/src/components/Card/Cover/Cover.tsx
- libs/journeys/ui/src/components/Video/Video.tsx
Stop playing video in canvas and card preview components on admin. This should also fix background display of poster image on video blocks and video backgrounds for cards. Bug was also addressed where variant id was not set.
- https://3.basecamp.com/3105655/buckets/26787371/todos/4752783621
- https://3.basecamp.com/3105655/buckets/26787371/todos/4757471362
- https://3.basecamp.com/3105655/buckets/26787371/todos/4752784571
> fix: stop admin video playing

- apps/journeys/src/components/Conductor/Conductor.tsx
When content on mobile landscape is too much, the card height isn't being constrained.
Fix so it scrolls again
> fix: restrain card hight on mobile landscape

- libs/journeys/ui/src/components/Video/Video.spec.tsx
- libs/journeys/ui/src/components/Video/Video.tsx
Allowed mobile devices to use their native video player when playing videos.
_This is following the discussions within this thread_
[- Native Video Controls](https://3.basecamp.com/3105655/buckets/26787371/todos/4756530664)
> fix: add native controls to video

- libs/journeys/ui/src/libs/blurImage/blurImage.spec.ts
- libs/journeys/ui/src/libs/blurImage/blurImage.ts
BlurImage requires blurHash, but newly created imageBlocks do not have this. Added a check so blurImage returns undefined, if blurhash is empty string.
> fix: blurImage returns undefiend when creating new imageBlock

- apps/journeys-admin/pages/_app.tsx
- apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
- apps/journeys-admin/src/libs/apolloClient/index.ts
Remove SSR from journeys-admin. Recreate apollo client whenever firebase token changes.
> fix: apollo reload client on token change

- libs/journeys/ui/src/components/Card/Card.tsx
- libs/journeys/ui/src/components/Card/Cover/Cover.tsx
Fixes error where cover was receiving no cover image for video.
> fix: cover should allow for missing image block

- libs/shared/ui/src/components/CopyTextField/CopyTextField.spec.tsx
- libs/shared/ui/src/components/CopyTextField/CopyTextField.tsx
Makes journey link visible in copy link text.
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4856873151)
> fix: value in copy text field

- apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/DescriptionEdit/DescriptionEdit.tsx
- apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/TitleEdit/TitleEdit.tsx
- apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.spec.tsx
- apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
- apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.stories.tsx
- apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
- apps/journeys/.env.example
- apps/journeys/__generated__/GetJourney.ts
- apps/journeys/pages/[journeySlug].tsx
This PR is a collection of fixes for social share component:
- Added button to top bar menu do display social drawer on mobile
- Fixed a bug where initial values was not correctly getting loaded in
- SEO: Linked twitter account to [@YourNextStepIs](https://twitter.com/YourNextStepIs)
- SEO: Created a FB app id + instructions for developers to create their own
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4752672406)
> fix: social share

- apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/block.resolver.ts
- apps/api-journeys/src/app/modules/block/block.service.spec.ts
- apps/api-journeys/src/app/modules/block/block.service.ts
updateAll baseService doesn't properly update with objects with ids, only objects with keys. Currently the array we send from block.resolver have ids.
Refactored move logic to block.service. As Mike said "the KeyAsId/IdAsKey transformations are now handled in the services, instead of the resolvers. Keeping id in resolver and key in service."
-[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/26787371/todos/4786305141)
> fix: move blocks update all api

- apps/api-journeys/db/seeds/nua1.ts
- apps/api-journeys/db/seeds/nua2.ts
- apps/api-journeys/db/seeds/nua8.ts
- apps/api-journeys/db/seeds/nua9.ts
Removed Grid block and the label within a RadioQuestion block for our NUA journeys
> fix: removed grid and updated radio question label

- apps/api-gateway/schema.graphql
- apps/api-journeys/db/seeds/nua1.ts
- apps/api-journeys/db/seeds/nua2.ts
- apps/api-journeys/db/seeds/nua8.ts
- apps/api-journeys/db/seeds/nua9.ts
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/journey/journey.graphql
- apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
- apps/api-journeys/src/app/modules/journey/journey.resolver.ts
- apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
- apps/api-journeys/src/app/modules/journey/journey.service.ts
Adds a featured journey filter to journeys graphql query. This is a relatively pointless PR. It is designed to retrigger journeys seeds which are being reset today.
> feat: featured journeys

- libs/journeys/ui/src/components/Card/Card.tsx
- libs/journeys/ui/src/components/Card/Cover/Cover.tsx
- libs/journeys/ui/src/components/Video/Video.tsx
useMemo to cache blurImage results so don't need to rerun the calculation on every render. Fixes the performance issues.
> fix: cache blurImage url

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.tsx
Card media backgrounds weren't being created as covers with the updated api. Added the `isCover` prop to the api call now.
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4874291271#__recording_4874598010)
> fix: create card background as cover

- apps/journeys-admin/src/components/FramePortal/FramePortal.tsx
VR was not correctly adding the link to the iframe dom. This should fix that.
> fix: add fonts to iframe preview vr update

- libs/journeys/ui/src/components/BlockRenderer/BlockRenderer.tsx
- libs/journeys/ui/src/components/Card/Card.stories.tsx
- libs/journeys/ui/src/components/Card/Card.tsx
- libs/journeys/ui/src/components/Card/Cover/ContentOverlay/ContentOverlay.tsx
- libs/journeys/ui/src/components/Card/Cover/Cover.tsx
Problem 1:
When you have an existing cover background (eg image), and replace this with another cover of different type (eg video). The old cover is removed as a background but now appears as a regular block (with null parentOrder). This will disappear when you refresh the page. But we want to hide `parentOrder: null` blocks.
[Basecamp](https://3.basecamp.com/3105655/buckets/27244374/todos/4879140066) 
Problem 2: 
Cards with video backgrounds but no poster image don't display the content box correctly. This is now fixed.
> fix: card background cover display

- apps/journeys-admin/pages/api/preview.ts
Fixes error attached below.
```
{
"id": "AQAAAYBtlEpk_Enp8AAAAABBWUJ0bEZQZkFBQzViM096emxXZEN3QUE",
"content": {
"timestamp": "2022-04-28T00:31:16.580Z",
"tags": [
"source:vercel"
],
"host": "journeys-admin-esoo36ph2-jesusfilm.vercel.app",
"service": "admin.nextstep.is",
"message": "START RequestId: 674dab71-d49e-49aa-83a9-f08cc5bd45fc Version: $LATEST\n2022-04-28T00:31:17.356Z\t674dab71-d49e-49aa-83a9-f08cc5bd45fc\tERROR\tError [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client\n    at new NodeError (internal/errors.js:322:7)\n    at ServerResponse.setHeader (_http_outgoing.js:561:11)\n    at sendJson …
```
> fix: where headers were set after sent to client

- apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.spec.tsx
- apps/journeys-admin/src/components/Editor/EditToolbar/EditToolbar.tsx
- apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
- apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.spec.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/JourneyCardMenu.tsx
- apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
- apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
All Preview icons should be consistent and point to the newly created endpoint for viewing journeys while in admin.
- [Link to Basecamp Todo
](https://3.basecamp.com/3105655/buckets/27244374/todos/4883549626)
Setup described in https://github.com/JesusFilm/core/pull/535
> fix: update preview icons and href, update tests

- apps/journeys-admin/pages/api/preview.ts
node-fetch doesn't throw an error if the response is erroneous and not a network error. This passes the error up to the client.
> feat: preview return error state

- apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.spec.tsx
- apps/journeys-admin/src/components/Editor/ImageBlockEditor/ImageBlockEditor.tsx
Image can now be saved onPaste in addition to onBlur.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4874319622)
> feat: save image on paste

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
Video player not displayed correctly on next card properties
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4883168152)
> fix: video playing in next card properties

- apps/journeys/src/components/Conductor/Conductor.tsx
conductor journey progress was in the wrong place on lg resolutions because under SSR the styles were set incorrectly. This defers to CSS to position this correctly. 
> fix: journey progress at bottom on desktop

- apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
- apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.tsx
Default Journey creates a card with background image incorrectly. Fix this so it's a cover with parentOrder: null
](https://3.basecamp.com/3105655/buckets/27244374/todos/4879140066)
> fix: initial card background image parentOrder

- apps/journeys-admin/pages/_app.tsx
- apps/journeys-admin/pages/_document.tsx
- apps/journeys/pages/_app.tsx
- apps/journeys/pages/_document.tsx
- apps/watch-admin/pages/_app.tsx
- apps/watch-admin/pages/_document.tsx
- apps/watch/pages/_app.tsx
- apps/watch/pages/_document.tsx
- libs/shared/ui/src/index.ts
- libs/shared/ui/src/libs/emotion/cache.ts
This is causing a render reload on the frontend for SSR pages. This should stop that from happening as SSR rendered emotion css classes should now match the frontend.
https://github.com/mui/material-ui/blob/master/examples/nextjs/pages/_document.js
> fix: add emotion cache

- apps/api-gateway/schema.graphql
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/block/card/card.graphql
- apps/journeys-admin/__generated__/globalTypes.ts
We should no longer allow coverBlockId to be set by cardBlockUpdate and cardBlockCreate mutations. Rather, coverBlockId is set on cover ImageCreate or VideoCreate
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4888071920)
> refactor: deprecate coverblockid field on card mutations

- libs/journeys/ui/src/components/Video/Video.tsx
Had to remake because of #604 cause of commit naming issues
EndAt should pause the video when there's no action that is selected
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4927627955)
> fix: endat to pause video when no action

- apps/journeys-admin/__generated__/UpdateVideoBlockNextStep.ts
- apps/journeys-admin/__generated__/VideoBlockSetDefaultAction.ts
- apps/journeys-admin/src/components/CardPreview/CardPreview.spec.tsx
- apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.tsx
Had to remake #606 because of commit naming errors 
On video create or after selecting a video from the video library. Set the default action of that video to go to the next step
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4924125766)
Card A - previous card of the newly created card
Card B - newly created card
> fix: set default video action

- apps/journeys-admin/src/components/Editor/Canvas/Canvas.tsx
Editing a long journey (with like 10 cards), a noticeable delay occurs. Currently, there is about a 5-10 second delay between any action in the Editor. To help solve that issue we're only allowing the canvas to render one card
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4923485547)
A more detailed QA
1.  Open up google chrome
2. Visit journeys admin and go on a journey with lots of cards and images or create one
3. In the editor of journeys-admin right-click on the website and visit the performance tab
4. Click on the record button
5. In the editor, add a new block
6. Once block is added, stop the recording
7. Check the scripting information and see how long it took
> fix: canvas to only render current card

- apps/api-gateway/src/environments/environment.prod.ts
- apps/api-gateway/src/environments/environment.ts
- apps/api-gateway/src/environments/types.ts
- apps/api-gateway/src/main.ts
- package-lock.json
- package.json
This addresses a security concern that means that API requests from clients can only come from specific URLs under our control.
- update to apollo-server 3.7 to support csrfPrevention option in apollo server config.
> fix: add cors to gateway

- libs/journeys/ui/src/components/Card/Card.spec.tsx
- libs/journeys/ui/src/components/Card/Card.tsx
- libs/journeys/ui/src/components/Image/Image.spec.tsx
- libs/journeys/ui/src/components/Image/Image.tsx
- libs/journeys/ui/src/components/Video/Video.tsx
- libs/journeys/ui/src/libs/blurImage/blurImage.spec.ts
- libs/journeys/ui/src/libs/blurImage/blurImage.ts
Editing a long journey (with like 10 cards), a noticeable delay occurs. Currently, there is about a 5-10 second delay between any action in the Editor. To help solve that issue we lowered down the aspect ratio of the image so that the blurhash calculation is a lot faster
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27244374/todos/4923485547)
> fix: blurimage calculation

- apps/journeys-admin/pages/index.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
If a user doesn’t have any journey - don’t give them the permission/ability to make a new one.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27717553/todos/4960677527#__recording_4963953270)
> feat: prevent users from creating journeys unless invited

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
- libs/journeys/ui/src/components/Step/Step.spec.tsx
- libs/journeys/ui/src/components/Step/Step.tsx
- libs/journeys/ui/src/index.ts
- libs/journeys/ui/src/libs/getStepHeading/getStepHeading.spec.ts
- libs/journeys/ui/src/libs/getStepHeading/getStepHeading.ts
- libs/journeys/ui/src/libs/getStepHeading/index.ts
- libs/journeys/ui/src/libs/index.ts
- Extracted logic for getting stepHeading into own component
- Send step name with step view events to GA4.
- Test
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27717553/todos/4960673373)
> feat: add step name to step event

- resources/kube/arangodb-bigquery-etl/arangodb-bigquery-etl-deployment.yaml
- resources/kube/arangodb-bigquery-etl/bqexport.sh
This fixes the issue that arose with a new version of google cloud cli. Instead of passing the secret as an environment variable, it now passes it as a mounted secret file. 
Already working and implemented in deployed image
> fix: arangodb bigquery export secret

- apps/journeys-admin/project.json
Fixed the admins build target when running `nx run journeys-admin:serve`
> fix: admins build target

- apps/journeys/next-i18next.config.js
- apps/journeys/project.json
there are no locales present on the journey site. This means the api cannot refresh a page. See the datadog log error [here](https://app.datadoghq.com/logs?query=status%3Aerror&event=AQAAAYEdJd3KtL0OaQAAAABBWUVkSmZoaUFBQ0UwNzdSMUZicVZBQUE&index=%2A&from_ts=1654050575604&to_ts=1654051475604&live=true).
Two steps were taken:
- update build command for journeys
- update locales directory
> fix: copy locales to journeys build

- apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/utils/getSelected.spec.tsx
- apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/utils/getSelected.ts
Front end changes for updating step order on step delete
[- Link to Basecamp Todo - point 2](https://3.basecamp.com/3105655/buckets/27717553/todos/4985508524)
> fix: update step order on step delete

- package-lock.json
The package protobufjs before 6.11.3 are vulnerable to Prototype Pollution which can allow an attacker to add/modify properties of the Object.prototype.
This vulnerability can occur in multiple ways:
by providing untrusted user input to util.setProperty or to ReflectionObject.setParsedOption functions
by parsing/loading .proto files
```
firebase-admin@9.12.0 requires protobufjs@6.11.2 via a transitive dependency on google-gax@2.28.1
next-firebase-auth@1.0.0-canary.5 requires protobufjs@6.11.2 via a transitive dependency on google-gax@2.28.1
```
This PR update google-gax v2.30.5:
Bug Fixes
- deps: update dependency protobufjs to v6.11.3 (https://github.com/googleapis/gax-nodejs/issues/1272) ([6492a2c](https://github.com/googleapis/gax-nodejs/commit/6492a2cc55086439518dcb20cb6001c28e1d2bda)) …
> chore: bump google gax from 2.28.1 to 2.30.5

- apps/api-journeys/src/app/modules/block/block.service.spec.ts
- apps/api-journeys/src/app/modules/block/block.service.ts
As I write tests for the blockDuplicate, I've discovered we incorrectly type the return object for `getSiblingsInternal`. This matters I need to know when the `_key` property is present or not (arrango allows us to use a user defined `_key` to specify the `_id` - we cannot directly set `_id`). This is important for the duplication api since I'm generating id's for each block.
More accurately we get something like when we call `getSiblingsInternal`
> fix: More accurately type getSiblingsInternal return type

- apps/api-gateway/schema.graphql
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/journey/journey.graphql
- apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
- apps/api-journeys/src/app/modules/journey/journey.resolver.ts
- libs/nest/powerBi/.babelrc
- libs/nest/powerBi/.eslintrc.json
- libs/nest/powerBi/README.md
- libs/nest/powerBi/jest.config.js
- libs/nest/powerBi/project.json
- libs/nest/powerBi/src/lib/config.ts
- libs/nest/powerBi/src/lib/getPowerBiAccessToken/getPowerBiAccessToken.spec.ts
- libs/nest/powerBi/src/lib/getPowerBiAccessToken/getPowerBiAccessToken.ts
- libs/nest/powerBi/src/lib/getPowerBiAccessToken/index.ts
- libs/nest/powerBi/src/lib/getPowerBiEmbed/getPowerBiEmbed.spec.ts
- libs/nest/powerBi/src/lib/getPowerBiEmbed/getPowerBiEmbed.ts
- libs/nest/powerBi/src/lib/getPowerBiEmbed/index.ts
- libs/nest/powerBi/tsconfig.json
- libs/nest/powerBi/tsconfig.lib.json
- libs/nest/powerBi/tsconfig.spec.json
- package-lock.json
- package.json
- tsconfig.base.json
- workspace.json
Much of this work is based on the [NodeJS example app](https://github.com/microsoft/PowerBI-Developer-Samples/tree/master/NodeJS) from Microsoft.
- add new nest-specific library for creating embed tokens from power bi
- add new adminJourneysReport endpoint on api-journeys
- add necessary environment variables to doppler
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/27931561/todos/5008366837)
Please describe the QA tests that you ran to verify your changes. Please also note any relevant details for your test configuration. @csiyang to carry out this work in his branch.
> feat: embed power bi report and admin journeys report endpoint

- .github/workflows/main.yml
github action should only check branch name when in a PR. This check is not necessary on main branch.
> fix: only check branch name on pr

- validate-branch-name.config.js
allow @dependabot branch names like dependabot/npm_and_yarn/sharp-0.30.7
> fix: allow dependabot branch name

- apps/journeys-admin/pages/_document.tsx
- apps/watch-admin/pages/_document.tsx
- apps/watch/pages/_document.tsx
Sever-side Rendering was not injecting the emotion style tags. This was resulting in a flash of unstyled elements that were visible to the user before hydrating the page.
The reference code was provided by [material UI](https://github.com/mui/material-ui/blob/931facf2684f952b31d8c8ae163219a738260401/examples/nextjs-with-typescript/pages/_document.tsx#L20).
> fix: add css to head tag on ssr

- apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.spec.tsx
- apps/journeys-admin/src/components/JourneyList/AddJourneyButton/AddJourneyButton.tsx
This was a bug introduced with https://github.com/JesusFilm/core/pull/725. The add button was routing users to the journeys/[slug]/edit route which has since been updated to journeys/[id]/edit. This PR fixes that!
> fix: journey button to go to id instead of slug

- apps/journeys/pages/[journeySlug].tsx
- apps/journeys/pages/_app.tsx
- apps/journeys/pages/index.tsx
- apps/journeys/project.json
- apps/journeys/src/libs/apolloClient/apolloClient.ts
- apps/journeys/src/libs/apolloClient/index.ts
This should fix revalidating pages (clicking the preview button). The issue is that the SSR functions were using a shared apollo cache. This make is so that all journeys project usage of graphql is fresh on every SSR invocation.'
The changes in journeys mimics the apollo client in journeys-admin.
> fix: remove apollo client cache ssr

- apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.tsx
- apps/journeys-admin/src/components/JourneyView/Menu/Menu.tsx
- apps/journeys-admin/src/components/JourneyView/Properties/Properties.tsx
Instead of hardcoding https://your.nextstep.is this PR checks NEXT_PUBLIC_JOURNEYS_URL env first. This should allow staging environments to show staging links to journeys instead.
> chore: use env for journeys url on journeys-admin

- apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
- apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Previously duplicating "Journey copy" would result in ""Journey copy copy" , "Journey copy copy" ... aka it wouldn't increment if the title ended with "copy" this PR fixes that.
> fix: duplicate journey title, find difference between titles

- apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyList.stories.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.spec.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.stories.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.spec.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.stories.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.spec.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.stories.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.spec.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.stories.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.tsx
There was a conflict resolution with the PowerBI branch that caused batch actions on journeys to fail. Prop now required to prevent accidental deletion later
Batch actions create a modal again
> fix: batch events broken by conflict resolution

- apps/journeys-admin/src/components/CardPreview/CardList/CardList.tsx
- apps/journeys-admin/src/components/CardPreview/CardPreview.stories.tsx
- apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
Found that Firefox wasn't correctly scaling the iframes in card list, which then left the full height of the card on the y axis, then an overflow: hidden was positioning the cards so that any spacing on top of the card is lost.  The solution was to add an additional overflow: hidden so the full height is not passed to horizontal select.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28141725/todos/5055669888)
**This solution uses negative margins, so should thoroughly QA'd to ensure it is still working as intended**
> - [ ] on Chrome web view
> - [ ] on Chrome mobile view
> - [ ] on Firefox web view
> - [ ] on Firefox mobile view
> - [ ] on Safari web view
> - [ ] on Safari mobile view
> fix: firefox cardlist margin

- apps/journeys-admin/src/components/Editor/ImageBlockThumbnail/ImageBlockThumbnail.tsx
Video thumbnail wasn't showing up, because the img src was not in our next/image config. But since we cannot control those images and their sources, it was opted to refactor from using the next/image component to a regular img component.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28141725/todos/5097279310)
> fix: video thumbnail

- libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
This PR fixes the selection of selected block when it is included in the querystring
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28141725/todos/5055629370)
> fix: selected step in editor context

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.spec.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Typography.tsx
Reorder the typography properties from Color, Variant, and Alignment to Variant, Color, and Alignment
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28141725/todos/5056195152)
> fix: reorder typography properties

- libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
Revert changes from https://github.com/JesusFilm/core/pull/768. It unintentionally dispatched a card reselect after properties or blocks on a card change.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28141725/todos/5120221158)
> fix: card reselection on change

- apps/journeys-admin/src/components/JourneyList/JourneySort/utils/sortJourneys.spec.ts
- apps/journeys-admin/src/components/JourneyList/JourneySort/utils/sortJourneys.ts
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.spec.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.spec.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ArchivedStatusTab/ArchivedStatusTab.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.spec.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/TrashedStatusTab/TrashedStatusTab.tsx
Default sortBy from lodash is sorted by ASCII value, which meant that "a" comes after "Z". This PR fixes that by adding additional options to orderBy and extracting it as util function.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28141725/todos/5094342591)
> fix: journey sort order

- apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/SocialShareAppearance.spec.tsx
- apps/journeys-admin/src/components/JourneyView/Menu/Menu.spec.tsx
A recent change allowing links to use a localhost URL broke some tests when running `nx test journeys-admin`, this PR ensures the tests have the correct env keys
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28141725/todos/5097086540)
> fix: link tests using env failing on development

- libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
This resolves the issue of the url selected step loading again after block creation, while allowing the selected block to be selected from journey overview
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28141725/todos/5055629370)
> fix: selected step from journey view

- apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
- apps/journeys-admin/pages/reports.tsx
- apps/journeys-admin/src/components/DynamicPowerBiReport/DyanmicPowerBiReport.spec.tsx
- apps/journeys-admin/src/components/DynamicPowerBiReport/DynamicPowerBiReport.tsx
- apps/journeys-admin/src/components/DynamicPowerBiReport/index.ts
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.tsx
- apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
- apps/journeys-admin/src/components/MultipleSummaryReport/MultipleSummaryReport.tsx
Reports were re rendering each time a state changed on the page.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28141725/todos/5094429522)
> fix: unwanted report re renders

- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/StatusTabPanel.tsx
- apps/journeys-admin/src/components/PageWrapper/PageWrapper.tsx
Nav bar and sort chip elements layout was being calculated by javascript, this caused the element to appear before it gets hidden.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28141725/todos/5128964737)
> refactor: layout calculations from js to css

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.spec.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/SelectedCard/SelectedCard.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.spec.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/Step.tsx
How the default next card is calculated got refactored in a previous [PR](https://github.com/JesusFilm/core/commit/b1470484769e13acddbfe94bdaa7119999ad4c3a). This PR makes the same fix for the `NextCard` button in card properties. Also updated the remove action, so nextBlockId is removed instead of selecting itself.
> fix: next card property title and remove action

- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DuplicateJourneyMenuItem.tsx/DuplicateJourneyMenuItem.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/ActiveStatusTab.tsx
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/utils/getDuplicated.spec.ts
- apps/journeys-admin/src/components/JourneyList/StatusTabPanel/ActiveStatusTab/utils/getDuplicatedJourney.ts
If our users have a lot of journeys and they've decided to duplicate a journey at the very bottom of the list. Some of them might not be aware that they'll have to scroll to the duplicated journey. I've added the ability to automatically scroll to the duplicated journey
> fix: scrolls to the duplicated journey

- apps/journeys-admin/pages/templates/[journeyId].tsx
- apps/journeys-admin/pages/templates/index.tsx
Add /templates and /templates/[journeyId] page. These pages may have menus which can be added in a future PR.
[- /templates](https://3.basecamp.com/3105655/buckets/28496234/todos/5147213883)
[- /templates/[journeyId]](https://3.basecamp.com/3105655/buckets/28496234/todos/5147224256)
> feat: add templates page

- apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Enable journeys that have a status of drafts to be previewable. This is so that templates can be previewed even when their status is currently on draft. This change is only on the backend. On the frontend, if they're on a journey and have a status of draft, users still can't click on the preview button. 
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28496234/todos/5168859103)
Manual Checks
- removing the check on the front end for disabling the preview button. Then create a new journey and preview it.
- previewing a published journey and changing its status on the database to draft. The same link should still be working as intended
> fix: make drafts previewable

- apps/api-journeys/src/app/modules/block/block.service.spec.ts
- apps/api-journeys/src/app/modules/block/block.service.ts
videoId and videoVariantLanguageId were incorrectly set, fix this.
> fix: handling blockId duplication

- apps/api-journeys/src/app/modules/journey/journey.service.spec.ts
- apps/api-journeys/src/app/modules/journey/journey.service.ts
When fetch with `template: true` and user not a `publisher`, the query returns a list of journeys owned by the user. But it should not return anything 
> fix: publisher templates fetch

- apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.spec.tsx
- apps/journeys-admin/src/components/Editor/EditToolbar/Menu/Menu.tsx
Awhile back we updated the editor pages to use journeyId instead of journeySlug. This link was still yet to be updated to use id.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/28980303/todos/5269917082)
> fix: editor journey settings link

- .github/workflows/main.yml
- .storybook/main.js
- package.json
The `--preserve-missing` flag is now becoming deprecated for Chromatic. This left stories that weren't changed, untouched (instead of deleted). 
Now instead of manually building stories for affected libraries and using that flag, it's recommended we build all stories in a monorepo and use Turbosnap to build the affected stories only.
https://www.chromatic.com/docs/turbosnap#full-rebuilds
There are some caveats to using TurboSnap. See the documentation above.
[Link to Basecamp Todo
](https://3.basecamp.com/3105655/buckets/29147486/todos/5294405053)
> chore: use turbosnap for chromatic

- apps/journeys-admin/src/components/JourneyView/Menu/CreateTemplateMenuItem/CreateTemplateMenuItem.spec.tsx
- apps/journeys-admin/src/components/JourneyView/Menu/CreateTemplateMenuItem/CreateTemplateMenuItem.tsx
With the recent changes of the pages going from `/library` and `/templates` to `/templates` and `/publisher`. With the key changes of /publisher is now the new admin page/URL path. This updates the url that users get redirected to on create template click
Follow the discussions
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29147486/todos/5289546952#__recording_5301672806)
> fix: redirect url of create template

- apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
- apps/api-journeys/src/app/modules/journey/journey.resolver.ts
- apps/api-journeys/src/app/modules/journey/journey.service.ts
Removed userId and userJourney check for getAllByIds. Templates archive, trash, delete restore was failing because of the userJourney check. Since the addition to roleGuard, this check is also now not needed.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29147486/todos/5301698079)
> fix: remove user id and user journey check

- apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
- apps/journeys-admin/src/components/JourneyView/CardView/CardView.spec.tsx
- apps/journeys-admin/src/components/JourneyView/CardView/CardView.tsx
- apps/journeys-admin/src/components/JourneyView/JourneyView.tsx
Fix redirect issues when clicking on card view and clicking back on back href from the edit page
Journeys 
Templates
Publisher
> fix: redirect issues

- .github/workflows/main.yml
Unit tests and VR are isolated tests. We ran VR last to reduce snapshots taken unnecessarily, this is no longer needed with TurboSnap. We're currently under our snapshot limit - 45/80k with the month ending Sept 29th
> ci: remove dependency on test for vr

- apps/api-gateway/schema.graphql
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/block/video/video.graphql
- apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/video/video.resolver.ts
- apps/journeys-admin/__generated__/BlockFields.ts
- apps/journeys-admin/__generated__/CardBlockVideoBlockCreate.ts
- apps/journeys-admin/__generated__/CardBlockVideoBlockUpdate.ts
- apps/journeys-admin/__generated__/GetJourney.ts
- apps/journeys-admin/__generated__/JourneyFields.ts
- apps/journeys-admin/__generated__/VideoBlockCreate.ts
- apps/journeys-admin/__generated__/VideoBlockUpdate.ts
- apps/journeys-admin/__generated__/VideoFields.ts
- apps/journeys-admin/__generated__/globalTypes.ts
- apps/journeys/__generated__/BlockFields.ts
- apps/journeys/__generated__/GetJourney.ts
- apps/journeys/__generated__/JourneyFields.ts
- apps/journeys/__generated__/VideoFields.ts
- apps/watch-admin/__generated__/BlockFields.ts
- apps/watch-admin/__generated__/JourneyFields.ts
- apps/watch-admin/__generated__/VideoFields.ts
- apps/watch/__generated__/BlockFields.ts
- apps/watch/__generated__/JourneyFields.ts
- apps/watch/__generated__/VideoFields.ts
- libs/journeys/ui/src/components/Video/__generated__/VideoFields.ts
- libs/journeys/ui/src/libs/JourneyProvider/__generated__/JourneyFields.ts
- libs/journeys/ui/src/libs/block/__generated__/BlockFields.ts
- pull youtube video data into video block
- removes video URL from video block
- validate internal and youtube source video blocks
- don't break current functionality
- all future video blocks should use source set to internal
You will need to run `nx fetch-secrets api-journeys` before trying to QA this
> feat: video source and youtube values

- apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
- apps/journeys-admin/pages/publisher/[journeyId].tsx
- apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
- apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
- apps/journeys-admin/src/libs/apolloClient/index.ts
We found an issue where anyone can access `/journey/[journeyId]/edit` of a journey that is a template.
Users when visiting the edit page of a template but through the journeys URL, `/journey/[journeyId]/edit`, users should always be redirected to `/publisher/[journeyId]/edit`
This would allow the `/publisher/[journeyId]/edit` to handle permissions,
and not allow a template to be edited on `/journey/[journeyId]/edit`
Publishers are currently seeing the access denied componet for a short amount of time while the page is loading. Publishers don't need to see this component
> fix: template redirect and access issues

- .github/workflows/main.yml
- libs/shared/ui/src/libs/themes/base/theme.stories.tsx
We've used up 9k snapshots just from duplicate dependancy bot changes.
I'm going to:
- Ignore VR on dependabot branches. Turbosnap configured to always run full build on main so it has always has latest changes (as recommended).
> ci: prevent VR on dependabot branch

- apps/journeys-admin/pages/publisher/[journeyId].tsx
- apps/journeys-admin/pages/templates/[journeyId].tsx
fix back links
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29147486/todos/5355289714)
> fix: back link on template view pages

- apps/journeys-admin/pages/publisher/[journeyId]/edit.tsx
Update seo title
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29147486/todos/5297226886)
> fix: templates edit seo title

- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.spec.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
Should not be able to duplicate templates from template list 
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29147486/todos/5289546900)
> fix: remove template duplicate from template card

- apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/video/video.resolver.ts
- libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
Superceeds https://github.com/JesusFilm/core/pull/925
- [Updating youtube fields error](https://3.basecamp.com/3105655/buckets/29494894/todos/5377889516)
- [EndAt sometimes doesn't work](https://3.basecamp.com/3105655/buckets/29494894/todos/5378769580)
> fix: video block update without video id

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/LinkAction/LinkAction.tsx
The action link property field wasn't changing as you clicked between button blocks on admin.
[Basecamp Todo](https://3.basecamp.com/3105655/buckets/29494894/todos/5382588092)
Minimal to solve the issue:
Extra checks:
> fix: refresh form when changing blocks

- apps/api-journeys/src/app/modules/block/video/video.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Data from YouTube is still being stored in the same block after changing providers from YouTube to Internal. Which can cause a problem depending on how we use the data. 
> fix: video update mutation

- libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
- libs/journeys/ui/src/components/Video/Video.tsx
Image covering video when playing on journeys. Default images of internal and youtube videos are covering videos when they're playing on Journeys. 
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29494894/todos/5398088483)
Create a journey that has videos - including an internal and youtube video. And background videos - including an internal and youtube video. Then publish the journey and visit that journey
> fix: image covering video when playing

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Step/NextCard/NextCard.tsx
- apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.tsx
https://github.com/JesusFilm/core/pull/903 made a change where the card properties is getting selected as soon as a card is selected. This caused a crash when  a card is deleted with `Next Card` properties is open. Updating the selectedBlock before updating cache allows the `Next Card` properties have the correct id for the correct block before the old one is removed
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29494894/todos/5393397254)
> fix: card delete causing crash

- libs/shared/ui/src/libs/rtl/index.ts
- libs/shared/ui/src/libs/rtl/rtl.spec.tsx
- libs/shared/ui/src/libs/rtl/rtl.ts
Helper function to check that a locale is RTL.
[Basecamp Todo](https://3.basecamp.com/3105655/buckets/29688713/todos/5413370739)
See unit tests but in general:
> feat: rtl language check

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/Action.stories.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/Action/NavigateToJourneyAction/NavigateToJourneyAction.stories.tsx
- libs/journeys/ui/src/libs/rtl/index.ts
- libs/journeys/ui/src/libs/rtl/rtl.spec.tsx
- libs/journeys/ui/src/libs/rtl/rtl.ts
Helper function to use with journeys apps (journeys, journeys-admin). We can't use iso3 to retrieve locales (not on supported list), it's a pain to maintain if every dev needs to remember this - `getJourneyRtl` can be the single point for controlling this logic if it changes in the future.
[Basecamp Todo
](https://3.basecamp.com/3105655/buckets/29688713/todos/5413370739)
> fix: add journey rtl check

- libs/shared/ui/src/libs/getLaunchDarklyClient/getLaunchDarklyClient.ts
LaunchDarkly was not calling identify function when LaunchDarkly was already initialized. This meant within a single lambda function multiple users were only being identified
> fix: launch darkly to run identify every time

- libs/journeys/ui/src/components/Card/ContainedCover/ContainedCover.tsx
- libs/journeys/ui/src/components/Video/Video.tsx
Youtube videos are not loading on journeys, and cannot be played. This happens on both iPhone and iPad, for both regular video blocks and background videos. The card will either display an infinite spinning animation or just display the thumbnail image.
**The current fix is temporary** and will further look into it during this cycle's (Cycle 8) cooldown. The current fix is to disable autoplay for youtube videos and card background videos on iOS devices. On a card background, an image should be rendered instead of a video. 
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29689605/todos/5431672006)
1. View the [Video QA Journey](https://journeys-git-22-08-jg-fix-youtube-autoplay-jesusfilm.vercel.app/video-qa)
2. Run through each step and check off relevant tasks
> fix: youtube videos not playing

- apps/api-journeys/db/seeds/jfpTeam.ts
> fix: set key on seed for visitors and members

- .github/workflows/main.yml
- .storybook/main.js
Full rebuilds are chewing through our Chromatic usage
See issue here:
https://jfp-digital.slack.com/archives/C041QM21FDL/p1667327141049819
https://www.chromatic.com/build?appId=612c2a83fdc2b2003a5c2eb7&number=3324
> ci: vr test ignore full rebuilds

- apps/journeys-admin/src/components/AccessDialog/AccessDialog.tsx
- apps/journeys-admin/src/components/Editor/Drawer/SocialShareAppearance/ImageEdit/ImageEdit.tsx
- apps/journeys-admin/src/components/Editor/EditToolbar/DeleteBlock/DeleteBlock.tsx
- apps/journeys-admin/src/components/Editor/VideoBlockEditor/Settings/Poster/Dialog/VideoBlockEditorSettingsPosterDialog.tsx
- apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActiveJourneyList.tsx
- apps/journeys-admin/src/components/JourneyList/ArchivedJourneyList/ArchivedJourneyList.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DeleteJourneyDialog/DeleteJourneyDialog.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/RestoreJourneyDialog/RestoreJourneyDialog.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/TrashJourneyDialog/TrashJourneyDialog.tsx
- apps/journeys-admin/src/components/JourneyList/TrashedJourneyList/TrashedJourneyList.tsx
- apps/journeys-admin/src/components/JourneyView/JourneyLink/EmbedJourneyDialog/EmbedJourneyDialog.tsx
- apps/journeys-admin/src/components/JourneyView/JourneyLink/SlugDialog/SlugDialog.tsx
- apps/journeys-admin/src/components/JourneyView/Menu/DescriptionDialog/DescriptionDialog.tsx
- apps/journeys-admin/src/components/JourneyView/Menu/LanguageDialog/LanguageDialog.tsx
- apps/journeys-admin/src/components/JourneyView/Menu/TitleDialog/TitleDialog.tsx
- apps/journeys-admin/src/components/JourneyView/TitleDescription/TitleDescriptionDialog/TitleDescriptionDialog.tsx
- apps/journeys-admin/src/components/TemplateList/ActiveTemplates/ActiveTemplates.tsx
- apps/journeys-admin/src/components/TemplateList/ArchivedTemplates/ArchivedTemplates.tsx
- apps/journeys-admin/src/components/TemplateList/TrashedTemplates/TrashedTemplates.tsx
- libs/shared/ui/src/components/Dialog/Dialog.spec.tsx
- libs/shared/ui/src/components/Dialog/Dialog.stories.tsx
- libs/shared/ui/src/components/Dialog/Dialog.tsx
We use on_ as prop names on components. handle_ are internal functions
> refactor: use onClose instead of handleClose

- .github/workflows/main.yml
Original main and all other branches used TurboSnap and triggered rebuilds on all config files. We later (in this current build) made all TurboSnap branches skip rebuilds on the config files so removed main from using TurboSnap.
This branch turns TurboSnap on main but runs a seperate VR step for non-main branches so they will not rebuild on storybook config files.
I'm not sure if there was a simpler way to toggle `untraced` to be on or off based on which branch we're on...
Adding in this change to slightly decrease the number of snapshots we chew through
> ci: use turbosnap on main

- .github/workflows/main.yml
- .storybook/main.js
Untraced configuration was set incorrectly and there were bugs with older versions of Chromatic so we were still getting full rebuilds for storybook
For commit https://github.com/JesusFilm/core/pull/1068/commits/37e7d42ac1a87834018e5663ffdf2a93cf1dac77
We changed `storybook/main.js` and `main.yml` files. Only yml files detected
For commit https://github.com/JesusFilm/core/pull/1068/commits/c49cffcc67cf11b878f6b7fa052b06f410ef53c9
The same change to `storybook/main.js` and `main.yml` triggered Turbosnap to be disabled.
> ci: fix chromatic untraced

- .github/workflows/main.yml
- .storybook/main.js
Turbosnap continues to pick up package.json changes from main. Always ignore these changes by default and manually rebuild the entire project when we expect it (or storybook config changes) to cause a story update.
I have exhausted all other options on our end that we know could possibly be causing the issue... fixing git history errors (via incorrect branch fetching), incorrect configurations...
#1071 #1072 #1068 
Tatai has suggested building only the affected libraries. I've added back the previous logic + steps we used in #856 
But first we're testing that untraced works in all circumstances (even when merging in latest main + package.json changes)
To test after merged in.
> ci: build only affected libraries so full rebuilds have less impact

- package-lock.json
Update the dependency for cypress that was causing npm to fail
Dependency update, no qa
> fix: update cypress request dependency 

- libs/shared/ui/src/libs/themes/website/tokens/components.stories.tsx
- libs/shared/ui/src/libs/themes/website/tokens/components.tsx
Styling the default MuiAutocomplete and TextFields so they display like the designs
Default MuiAutocomplete
Designs
[Basecamp Todo](https://3.basecamp.com/3105655/buckets/30317529/todos/5570931464)
> feat: style mui autocomplete & other textfields

- libs/shared/ui/src/libs/themes/base/theme.stories.tsx
- libs/shared/ui/src/libs/themes/base/tokens/breakpoints.ts
Really wide screens with height < 600px render as `sm`
Adding this fix now since it affects watch page layout.
Now looks like
> fix: breakpoints on sm

- apps/api-videos/src/app/modules/video/video.service.spec.ts
- apps/api-videos/src/app/modules/video/video.service.ts
This PR addresses the out of memory issue when searching for large sets of child data in videos
> fix: oom children search

- libs/shared/ui/src/components/Dialog/Dialog.spec.tsx
- libs/shared/ui/src/components/Dialog/Dialog.stories.tsx
- libs/shared/ui/src/components/Dialog/Dialog.tsx
Added the ability to add icon in shared dialog
**Requirements**
Visit [Storybook](https://612c2a83fdc2b2003a5c2eb7-egaratpisu.chromatic.com/?path=/story/shared-ui-dialog--icon-title)
> fix: icon in shared dialog

- apps/watch/pages/[part1]/[part2].tsx
- apps/watch/pages/[part1]/[part2]/[part3].tsx
- apps/watch/src/components/Hero/VideoHero/VideoHero.tsx
- apps/watch/src/components/ShareDialog/ShareDialog.spec.tsx
- apps/watch/src/components/ShareDialog/ShareDialog.stories.tsx
- apps/watch/src/components/ShareDialog/ShareDialog.tsx
- apps/watch/src/components/VideoContainerPage/VideoContainerPage.spec.tsx
- apps/watch/src/components/VideoContainerPage/VideoContainerPage.stories.tsx
- apps/watch/src/components/VideoContainerPage/VideoContainerPage.tsx
- apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
- apps/watch/src/components/VideoContentPage/VideoContentPage.stories.tsx
- apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
- apps/watch/src/libs/videoContext/VideoContext.spec.tsx
- apps/watch/src/libs/videoContext/VideoContext.tsx
- apps/watch/src/libs/videoContext/index.ts
Use VideoProvider to get values of video content and video container instead of prop drilling. Using render props pattern here would make each page too large so not appropriate here.
[Basecamp Todo](https://3.basecamp.com/3105655/buckets/30300130/todos/5616332686)
> feat: create video context

- apps/journeys/pages/[journeySlug].tsx
Should only ever show SEO Title and Description
> fix: only show seo title and description

- apps/watch/next.config.js
- apps/watch/pages/_app.tsx
- apps/watch/pages/index.tsx
- apps/watch/public/fonts/fonts.css
- apps/watch/src/components/Header/Header.tsx
- apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
- apps/watch/src/components/HomePage/HomeVideos/Card/HomeVideoCard.spec.tsx
- apps/watch/src/components/HomePage/HomeVideos/Card/HomeVideoCard.tsx
- apps/watch/src/components/HomePage/HomeVideos/Card/index.ts
- apps/watch/src/components/HomePage/HomeVideos/HomeVideos.tsx
- libs/shared/ui/src/libs/timeFormat/timeFormat.ts
- increase performance by using next image
- handle all widths with varying heights
- use ellipses where possible to enable small presentation of boxes
- use full width of container
- border of card should now take into consideration gradient
> fix: home grid to match designs

- apps/watch/src/components/Header/Header.tsx
- apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
- apps/watch/src/components/HomePage/HomeHero/HomeHero.tsx
- apps/watch/src/components/VideoContainerPage/ContainerDescription/ContainerDescription.tsx
- apps/watch/src/components/VideoContentPage/VideoContent/VideoContent.tsx
- center header
- descriptions should now break urls into multiple lines
- background home page should be black on header
> fix: home background, header and description

- apps/watch/src/components/VideoCard/VideoCard.spec.tsx
- apps/watch/src/components/VideoCard/VideoCard.tsx
series should hide video container slug on video card
> fix: video card hide slug link when video is series

- apps/watch/src/components/AudioDialog/AudioLanguageDialog.tsx
- apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.tsx
Updated language null check for audio dialog
> fix: audio dialog language null check

- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/TrashJourneyDialog/TrashJourneyDialog.tsx
Change the journey-delete-dialog message box text 
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29689605/todos/5533245318)
Going to the Journey-admin panel, click on the journey`s card option button at the right bottom corner, click on trash menu option,
> fix: change the copy of journey-delete-dialog message

- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditInput/InlineEditInput.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/RadioOptionEdit/RadioOptionEdit.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TextResponseEdit/TextResponseEdit.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.spec.tsx
- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
Fix difficulties to edit text field by wrapping input fields by editing-wrapper of its specific block component and disabling input-caret (hiding caret|cursor) whenever the block component is not selected for editing.
Change the color of inline-edit-input to white
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/29689605/todos/5529134774)
Go to journeys-admin panel, create new or select a journey, create or select a card, add new block or select a block on the card.
> fix: difficulties editing text

- apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.tsx
- apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
Controls on android fullscreen are currently not showing. And we've stopped using VideoJS loading icon and created our own instead. This allows us not to import the video js CSS file. 
**Requirements**
- Play any video and click on fullscreen (for android testing)
- Throttle the webpage to use slow3G (general testing)
---------------------
> fix: controls on android and loading icon

- apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.spec.tsx
- apps/watch/src/components/VideoContentPage/AudioLanguageButton/AudioLanguageButton.tsx
- apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
- apps/watch/src/components/VideoContentPage/VideoHero/VideoControls/VideoControls.spec.tsx
- apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.spec.tsx
- apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
- apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
Adds video overlay share / download buttons on mobile website. Languages dropdown button clips using ellipsis for longer language names
> feat: overlay buttons

- apps/watch/next.config.js
Add source maps to prod watch to allow lighthouse to reveal optimization opportunities.
> chore: add source maps to prod watch

- apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
- apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/30278084/todos/5706315181)
> fix: render title only on feature films

- apps/watch/pages/_app.tsx
- apps/watch/pages/videos.tsx
Dependency for John, Jian wei and Nick to allow them to reference the same apollo client cache
[John's PR](https://3.basecamp.com/3105655/buckets/30278084/todos/5711053621)
[Nick's PR](https://3.basecamp.com/3105655/buckets/30278084/todos/5711054440)
[Jian Wei's PR](https://3.basecamp.com/3105655/buckets/30278084/todos/5711232308)
> fix: refactor to use one apollo provider

- apps/api-gateway/project.json
- apps/api-gateway/router.prod.yaml
Two router bugs resolved:
- cannot generate graphql without accepting license
- vercel previews cannot connect to API
> fix: graphql generation and cors vercel error with router

- .github/workflows/main.yml
An incorrect PR title was used in [this commit](https://github.com/JesusFilm/core/commit/732f3cfd06b66a3a5cc140e0544912c49e1bf3f5).
The solution is to force push a good commit title which was done in [this commit](https://github.com/JesusFilm/core/commit/f654382ef8ecaaf07529923ac99dc0afc123ece6).
This PR then points commit lint to the latest good commit.
> fix: update earliest good commit

- apps/api-gateway/schema.graphql
- apps/api-journeys/db/seed.ts
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/app.module.ts
- apps/api-journeys/src/app/modules/userInvite/userInvite.graphql
- apps/api-journeys/src/app/modules/userInvite/userInvite.module.ts
- apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.spec.ts
- apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
- apps/api-journeys/src/app/modules/userInvite/userInvite.service.spec.ts
- apps/api-journeys/src/app/modules/userInvite/userInvite.service.ts
- libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
- libs/nest/common/src/lib/firebaseClient/index.ts
- libs/nest/decorators/src/lib/CurrentUser/CurrentUser.ts
- libs/nest/decorators/src/lib/CurrentUser/index.ts
Creates and updates a userInvite to set journey permissions
[Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245893/todos/5763468706)
Stage graphql correctly returns expected data
> feat: add user invite api

- apps/journeys-admin/__generated__/UserInviteAcceptAll.ts
- apps/journeys-admin/pages/index.tsx
- apps/journeys-admin/pages/journeys/[journeyId].tsx
- apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
- apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
Visiting any of the journey list, detail, edit or report pages after you get invited should let you see the page after refresh.
[Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245893/todos/5763488517)
Create a user invite using apollo or localhost:4000
Or create via adding directly to arrango
{
"journeyId": "dcd0c068-de99-4c45-8775-f4328d042832",
"senderId": "SMNiOX5sL9OwbLFsLznsoMkVn603",
"email": "another@email.com",
"accepted": true,
"expireAt": "2023-03-04T03:42:25.712Z",
"acceptedAt": "2023-02-06T19:47:01.553Z"
}
Log in or sign up using the email in the invite - you should be able to see the journey or journeys you've been invited 
to.
> feat: approve invited user on journey related pages

- .devcontainer/post-create-command.sh
- apps/api-gateway/Dockerfile
- apps/api-gateway/router.prod.yaml
- apps/api-gateway/router.yaml
- apps/api-gateway/routerSchema.json
This PR forces projects to use only nextstep.is and jesusfilm.org domains for deployed main and stage. This also caches cors requests for 24 hours in the browser. This was made available in apollo router 1.10.
> chore: update router cors to match domains and be cacheable

- libs/shared/ui/src/components/Dialog/Dialog.spec.tsx
- libs/shared/ui/src/components/Dialog/Dialog.stories.tsx
- libs/shared/ui/src/components/Dialog/Dialog.tsx
Allow us to pass in a custom component in dialog action section so we can create this for access dialog
](https://3.basecamp.com/3105655/buckets/31245893/todos/5819657286)
> fix: render custom dialog action component

- apps/api-gateway/schema.graphql
- apps/api-journeys/db/seed.ts
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/app.module.ts
- apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.graphql
- apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.module.ts
- apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.spec.ts
- apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.resolver.ts
- apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.service.spec.ts
- apps/api-journeys/src/app/modules/journeyProfile/journeyProfile.service.ts
Add a user profile table for api-journeys. 
[Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245893/todos/5783931883)
- Would need to run locally and comment out "AuthGuard", and manually pass userId (instead of useCurrentUserId) to test.
- Run seed.
> feat: add journeyProfile table

- libs/nest/database/src/lib/BaseService.spec.ts
- libs/nest/database/src/lib/BaseService.ts
Loader expects requested Ids to be returned in the same order.
> fix: loader sort order according to ids

- apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.spec.tsx
- apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx
Changing languages on a video that belongs to a collection should retain collection on changed video page.
e.g changing from afrikaans to english should keep collection:
/watch/lumo/lumo-matthew-1-1-2-23/afrikaans -> /watch/lumo/lumo-matthew-1-1-2-23/english
However current code does this:
/watch/lumo/lumo-matthew-1-1-2-23/afrikaans -> /watch/lumo-matthew-1-1-2-23/english
This PR fixes that issue.
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31485426/todos/5818822944)
> fix: keep collection when changing language

- apps/api-journeys/src/app/modules/block/image/image.graphql
- apps/api-journeys/src/app/modules/block/image/image.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/image/image.resolver.ts
This PR allows unsplash to skip blurhash processing when creating an image block.
https://3.basecamp.com/3105655/buckets/31265497/todos/5844141257
> feat: skip blurhash processing

- apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.stories.tsx
- apps/watch/src/components/AudioLanguageDialog/AudioLanguageDialog.tsx
- apps/watch/src/components/SubtitleDialog/SubtitleDialog.stories.tsx
- apps/watch/src/components/SubtitleDialog/SubtitleDialog.tsx
Opening audio and subtitle language dialogs should show a loaders. Clicking on the dropdown while loading should show "Loading..." instead of "No options". This also makes audio language consistent with subtitle dialog in regards to a close button.
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31485426/todos/5843900928)
> chore: add loaders to language dialog

- apps/watch/src/components/Footer/FooterLink/FooterLink.spec.tsx
- apps/watch/src/components/Footer/FooterLink/FooterLink.tsx
- apps/watch/src/components/Footer/FooterLinks/FooterLinks.spec.tsx
- apps/watch/src/components/Footer/FooterLinks/FooterLinks.tsx
- apps/watch/src/components/Footer/FooterLogos/FooterLogos.spec.tsx
- apps/watch/src/components/Footer/FooterLogos/FooterLogos.tsx
- apps/watch/src/components/Footer/FooterSocials/FooterSocials.spec.tsx
- apps/watch/src/components/Footer/FooterSocials/FooterSocials.tsx
- apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.spec.tsx
- apps/watch/src/components/Header/HeaderMenuPanel/HeaderMenuPanel.tsx
All www.jesusfilm.org links should open in the current window. Everything else should open in a new window/tab.
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31485426/todos/5839080429)
> fix: header and footer links opening in window or new window

- apps/watch/next.config.js
- root url on watch should redirect to base path
- URLs without base path should redirect to the same resource with base path
- [Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31485426/todos/5843982295)
> fix: forward root to base path on watch

- apps/watch/src/components/VideoContentPage/VideoHero/VideoHero.tsx
- apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.spec.tsx
- apps/watch/src/components/VideoContentPage/VideoHero/VideoHeroOverlay/VideoHeroOverlay.tsx
- [hide videojs loaders](https://3.basecamp.com/3105655/buckets/31485426/todos/5848282546)
- [remove mute button from video hero](https://3.basecamp.com/3105655/buckets/31485426/todos/5848273505)
> fix: hide player loader and mute button on hero

- libs/shared/ui/src/components/CopyTextField/CopyTextField.tsx
UX wanted the copy link icon removed. Blocking  https://github.com/JesusFilm/core/pull/1323
> fix: remove start icon from CopyLinkField

- apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
- apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
Fix a bug where userJourney openedAt was not being called for `/journeys/[journeyId]/edit` and `/journeys/[journeyId]/report `
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245472/todos/5859436392)
> fix: opened at mutation call

- apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.spec.tsx
- apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.tsx
Fix big divider render logic on active journeys list
[Link to BaseCamp todo ](https://3.basecamp.com/3105655/buckets/31245472/todos/5864473076)
> fix: big divider render logic

- apps/journeys-admin/src/components/JourneyList/JourneyList.spec.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyList.tsx
Hide journeys summary report behind launch darkly feature flag
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245472/todos/5847006549)
> feat: hide report with flag

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Video/Options/VideoOptions.spec.tsx
- apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.spec.tsx
- apps/journeys-admin/src/components/Editor/VideoBlockEditor/Source/Source.tsx
- apps/journeys-admin/src/components/Editor/VideoBlockEditor/VideoBlockEditor.tsx
Don't open Video Selection tab by default when clicking on the Background property
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245472/todos/5847653659#__recording_5865811300)
> fix: background media selection

- apps/watch/pages/[part1]/[part2].tsx
- apps/watch/pages/[part1]/[part2]/[part3].tsx
- apps/watch/src/components/VideoCard/VideoCard.spec.tsx
- apps/watch/src/components/VideoCard/VideoCard.tsx
- redirect /videoId/languageId to /videoId.html/languageId.html
- redirect /containerId/videoId/languageId to /containerId.html/videoId/languageId.html
- on video card use the correct extensions
- prerendered /videoId/languageId pages should use correct extension
> fix: watch links to use proper extensions

- apps/journeys-admin/src/components/JourneyList/JourneySort/JourneySort.spec.tsx
- apps/journeys-admin/src/components/JourneyList/JourneySort/JourneySort.tsx
Remove the sort-by label and the cancel button from the sort-by pop-up in JourneysList/JourneysSort.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31245472/todos/5846992126)
> refactor: sort by popup in journeys admin

- apps/watch/next.config.js
- apps/watch/pages/api/jf/watch.html/[videoId]/[languageId].ts
Handle /api and /bin redirects to the proper resources on watch.
> fix: redirect bin to api on watch

- apps/journeys-admin/src/components/Editor/Canvas/InlineEditWrapper/TypographyEdit/TypographyEdit.tsx
I broken main :( 
](https://3.basecamp.com/3105655/buckets/31245472/todos/5861894458)
Test in main, it's working on stage and locally.
> fix: keep consistent target for input

- apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
- apps/api-journeys/src/app/modules/journey/journey.resolver.ts
The PR addresses a 500 error edge case where a member record already exists, but is an index collision.
> fix: 500 from members index

- apps/api-journeys/db/seed.ts
- apps/api-journeys/db/seeds/onboarding.ts
Adds a onboarding journey for dev use, with the id and slug matching the real onboarding journey in production
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31822575/todos/5910584578)
> feat: create seed for onboarding journey

- apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
- apps/api-journeys/src/app/modules/journey/journey.resolver.ts
We get "copy 0" whenever we use a template from the template library. 
We want it just to display the template name, or add copy only if another journey with the template name already exists in our journey list.
](https://3.basecamp.com/3105655/buckets/31822575/todos/5909445092)
> fix: title of journey from template

- apps/api-journeys/src/main.ts
- apps/api-languages/src/main.ts
- apps/api-media/src/main.ts
- apps/api-users/src/main.ts
- apps/api-videos/src/main.ts
This PR aims to fix a disconnect between the ALB timeout and nestjs, which may be causing 502s.
> fix: alb 502

- apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
- apps/journeys/src/libs/apolloClient/apolloClient.ts
- apps/watch-admin/src/libs/apolloClient/apolloClient.ts
- apps/watch/src/libs/apolloClient/apolloClient.ts
This is a fix for apollo tls timeout errors. A very obscure, undocumented bug with nextjs, but this seems to resolve it.
> fix: tls timeout in ssr

- apps/journeys-admin/pages/journeys/[journeyId]/edit.tsx
- apps/journeys-admin/pages/journeys/[journeyId]/reports.tsx
Adds the missing fix for the /edit and /report pages.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31739517/todos/5912136746)
Precondition: Make sure you don't have any other journeys that are display the badge
> fix: badge disappears when visiting edit and report pages 

- apps/journeys-admin/src/components/CardPreview/CardPreview.tsx
- apps/journeys-admin/src/components/Editor/ActionDetails/ActionCards/ActionCards.spec.tsx
- apps/journeys-admin/src/components/Editor/ActionDetails/ActionCards/ActionCards.tsx
- apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.spec.tsx
- apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.stories.tsx
- apps/journeys-admin/src/components/Editor/ActionDetails/ActionDetails.tsx
- apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.spec.tsx
- apps/journeys-admin/src/components/Editor/ActionDetails/ActionEditor/ActionEditor.tsx
- apps/journeys-admin/src/components/Editor/ActionDetails/data.ts
- apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.spec.tsx
- apps/journeys-admin/src/components/Editor/ActionsTable/ActionsList/ActionsList.tsx
- apps/journeys-admin/src/components/Editor/ActionsTable/ActionsTable.tsx
- apps/journeys-admin/src/components/Editor/Drawer/Drawer.tsx
This should render the currently selectedURL within the drawer and it should also renders all the cards that's currently using the URL
Any components/files changes that are connected to ActionsTable are due to change. This PR is focused only on ActionDetails
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/31822561/todos/5910004274)
> feat: action details

- apps/api-journeys/src/app/app.module.ts
- apps/api-languages/src/app/app.module.ts
- apps/api-media/src/app/app.module.ts
- apps/api-users/src/app/app.module.ts
- apps/api-videos/src/app/app.module.ts
Ignore health check logs. These should no longer show up in datadog.
> fix: ignore health check logs

- .github/workflows/main.yml
- apps/api-gateway/schema.graphql
- apps/api-journeys/project.json
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/modules/event/journey/journey.graphql
- apps/api-journeys/src/app/modules/journey/journey.graphql
- apps/api-languages/project.json
- apps/api-languages/src/app/app.module.ts
- apps/api-languages/src/app/modules/translation/translation.graphql
- apps/api-media/project.json
- apps/api-media/schema.graphql
- apps/api-users/project.json
- apps/api-users/schema.graphql
- apps/api-videos/project.json
- apps/api-videos/schema.graphql
- apps/api-videos/src/app/modules/video/video.graphql
The following issues occur when defining a federation 2 compatible schema. This fixes that!
```
KEY_FIELDS_MISSING_EXTERNAL
Language -> A @key directive specifies the `id` field which has no matching @external field.
KEY_FIELDS_MISSING_ON_BASE
Language -> A @key selects id, but Language.id was either created or overwritten by api-journeys, not api-videos
```
```
KEY_FIELDS_MISSING_EXTERNAL
Language -> A @key directive specifies the `id` field which has no matching @external field.
KEY_FIELDS_MISSING_ON_BASE
Language -> A @key selects id, but Language.id was either created or overwritten by api-journeys, not api-journeys
```
```
Language.id -> Field "Language.id" already exists in the schema. It cannot also be defined in this type extension. If this is meant to be an external field, add …
```
> fix: schema federation 2 translation import

- apps/journeys-admin/src/components/Editor/ControlPanel/Attributes/blocks/Typography/Variant/Variant.tsx
The selection background color on a toggle button group is `background.default`.  Previously adding the ThemeProvider on the whole toggle button group meant that we use the  journeys theme token which is white and so doesn't show selection at all. 
Refactor so that we just re-theme the label with the journeys theme.
](https://3.basecamp.com/3105655/buckets/31739517/todos/5936194572)
> fix: show selected typography variant when editing block

- apps/watch/src/components/VideoContentPage/VideoContentPage.spec.tsx
- apps/watch/src/components/VideoContentPage/VideoContentPage.tsx
stop calling useVideoChildren. Causing API to crash.
> fix: hide children on video content

- apps/watch/src/components/VideosPage/VideosPage.spec.tsx
Subtitle filter test is timing out. Fix for now is to skip the current test
> fix: subtitle timing out test

- apps/watch/project.json
This should fix the `nx serve watch` command.
> fix: watch serve to use underscore build

- .devcontainer/docker-compose.yml
networking line causing error:
`Error response from daemon: conflicting options: custom host-to-IP mapping and the network mode`
remove as still functions without this line.
> fix: remove network mode line

- apps/journeys-admin/src/components/HelpScoutBeacon/HelpScoutBeacon.tsx
On the login page, helpscout icon should have the dark theme regardless of sizing, making it more contrasted and easier to spot. After login, everything functions normally.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/35391220/todos/6872004087)
> fix: conditional helpscout theme for login

- apps/journeys-admin/src/components/Editor/ImageBlockHeader/ImageBlockHeader.tsx
- apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguagesFilterPopper/LanguagesFilterPopper.tsx
Fixed the issue where the image block header would not drop the author name if the photo was deleted. Also fixed the issue where upon creating a new image block, the header would again say "Selected image" although no image had yet been loaded.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/35391220/todos/6930875869)
> fix: clear photo author

- libs/journeys/ui/src/libs/action/action.spec.ts
- libs/journeys/ui/src/libs/action/action.ts
Fixed an issue where journey links on buttons would open in a new tab. Now, buttons linked to other journeys should open on the same tab for a smoother UX experience.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/35391220/todos/6943261826)
Create / Open a Journey with button block(s) that have urls. Some buttons should be linked to Journeys, and some to other websites.
> feat: substring matching for journey links

- apps/journeys-admin/src/components/TemplateSections/TemplateSections.tsx
"Most relevant" tab should be hidden in templates search when 1 tag is applied. If more tags are applied, section should reappear.
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/35391220/todos/6858629274)
> fix: hide most relevant with one tag

- libs/journeys/ui/src/components/RadioQuestion/RadioQuestion.spec.tsx
- Fixes type error for missing prop `activeStep` on original tests
- Adds test for checking `activeStep` resets the selection when `activeStep` is false
- [Link](https://3.basecamp.com/3105655/buckets/35958767/todos/7065660798) to Basecamp Todo
> test: radio question

- apps/journeys/src/components/Conductor/NavigationButton/NavigationButton.tsx
Centers the Navigation Buttons to the viewport instead of the fixed width between the step header and step footer
- [Link](https://3.basecamp.com/3105655/buckets/35958878/todos/6970068229) to Basecamp Todo
> feat: center navigation button to viewport

- apps/journeys/src/components/Conductor/DynamicCardList/DynamicCardList.tsx
- apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
This should fix the next pre-rendered card causing overflow. `DynamicCardList` was not properly inheriting the height from `SwipeNavigation` due to the missing `max-height` value and absolute positioning. 
> fix: overflow caused by inactive card height

- apps/journeys-admin/next-logger.config.js
[Make pino Log Messages Appear with the Correct Status in Datadog](https://benlimmer.com/2020/10/23/make-pino-log-messages-appear-with-the-correct-status-in-datadog/).
> fix: logging level on datadog

- apps/journeys-admin/src/components/Editor/Slider/Content/Content.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Content/Goals/Goals.tsx
- Adds tests for editor `Content`
[Link](https://3.basecamp.com/3105655/buckets/36562260/todos/7145951569) to Basecamp Todo
> test: add tests for editor Content

- apps/journeys/next.config.js
- apps/journeys/src/libs/apolloClient/apolloClient.ts
Proxy client side GraphQL API requests through the current domain using a rewrite. Server side requests will still go directly to the GraphQL API. This will help hide the jesusfilm.org domain from NextSteps and future custom domains.
> feat: proxy client side graphql requests via rewrite

- libs/journeys/ui/src/components/Video/VideoControls/VideoControls.tsx
- Fixes bug causing videos on the second card of embedded journeys to play automatically when the embedded journey enters fullscreen
> fix: embedded videos playing when not activeStep

- .github/workflows/app-deploy.yml
- apps/journeys/pages/index.tsx
when deploying to stage custom domains were not able to point to stage without requiring a redeploy. This creates a new vercel app called journeys-stage where stage is its production branch. This means custom domains on stage will automatically get access to the most recent production build.
> chore: add journeys-stage app

- apps/journeys-admin/middleware.spec.ts
- apps/journeys-admin/middleware.ts
middleware currently redirects users without accept-language headers from / to /. This causes a redirection loop.
> fix: no redirect for languages when same url

- apps/journeys-admin/pages/templates/index.tsx
Firebase user was used to check if email has been verified, but it was returning the incorrect user. Updated the verification check to look at the database directly using `GetMe`
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562350/todos/7230339257)
> fix: validate of get me

- apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.spec.tsx
- apps/journeys/src/components/Conductor/SwipeNavigation/SwipeNavigation.tsx
Swiping was only being blocked on the `MuiSlider-thumb`, also block on the other slider elements
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562350/todos/7248596429)
> fix: swipe not being blocked on slider

- apps/api-journeys/src/app/modules/customDomain/customDomain.service.spec.ts
- apps/api-journeys/src/app/modules/customDomain/customDomain.service.ts
custom domain verification errors are returning as 400 errors. The bug is that everything that wasn't a 200 threw an exception. This ignores the failures where the verify data is returning with an error existing_project_domain or missing_txt_record.
> fix: custom domain verification

- apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.spec.tsx
- apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
[basecamp link](https://3.basecamp.com/3105655/buckets/36562350/todos/7202436355)
Tags have been added to felt needs without relevant images being added. This allows felt needs to be displayed regardless of the image. Luyba to add images at a later date.
> fix: show felt needs button without images

- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/QuickControls.tsx
[- Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/36562260/todos/7173921592)
Quickaccess panel should display above block
link to deployment: [https://journeys-admin-2619-jesusfilm.vercel.app/](https://journeys-admin-2619-jesusfilm.vercel.app/)
> fix: move icon panel

- apps/api-gateway/router.prod.yaml
allow localhost to connect to api-gateway. This is useful when running stg_dev or prd_dev doppler environments.
> fix: cors localhost for api-gateway

- apps/api-videos/src/app/modules/algolia/algolia.service.spec.ts
- apps/api-videos/src/app/modules/algolia/algolia.service.ts
We were incurring bills on agolia for syncing dev and stg to algolia indexes.
Sync only english video variants on dev and stg to algolia.
Will need to clear out both indexes on algolia on dev and stg when merging this in.
> fix: sync english to algolia on stg and dev

- .github/workflows/app-deploy.yml
These tests were renabled without actually testing to see if they were passing
Disable e2e tests from running. @kiran-redhat I think next time we re-enable these we should first make a minor change to each project to run the e2e tests before merging in.
> revert: e2e tests from running

- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/Button/Button.tsx
plus icon appearing on mobile when tapping as well as broken tooltips
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7292062030)
remove icon and tooltips on mobile resolutions
> fix: remove hover icon

- apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/NavigationDrawer.tsx
- apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.spec.tsx
- apps/journeys-admin/src/components/TemplateGallery/TagCarousels/CollectionButton/CollectionButton.tsx
- apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.spec.tsx
- apps/journeys-admin/src/components/TemplateGallery/TagCarousels/FeltNeedsButton/FeltNeedsButton.tsx
- apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.spec.tsx
- apps/journeys-admin/src/components/TemplateGallery/TagCarousels/TagCarousels.tsx
- apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.spec.tsx
- apps/journeys-admin/src/components/TemplateGallery/data.ts
Filter card buttons (FeltNeedsButton.tsx) should only display if they have a background.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071027/todos/7306953317)
Initially tried to conditionally render the ButtonBase component iff the `tagImageData` variable is defined. However this lead to uneven spacing. 
Instead, let the TagCarousel filter out a fixed set of tags that are known to have valid backgrounds as hard-coded in FeltNeedsButton. 
n/a
UI test added took a long time to debug. Solution: I needed to make another button assertion so that jest would wait for the render to complete.
> fix: hide template filters with no background

- apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
- libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
- libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
When one selects any block that results in the QuickControls to appear, and then navigates to the journey flow slide, the QuickControls remain open. We want the parent card to be focused on and the QuickControls to close.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7292062111)
Add a dispatch on the slider useEffect function that sets the selected block value to the parent card block.
n/a
This fix seems to add some lagging in terms of rendering the canvas when the slider changes but the hope is that this can be resolved in another ticket. https://3.basecamp.com/3105655/buckets/37071143/todos/7307053111
> fix: reset canvas focus when slider to journey flow

- apps/journeys-admin/pages/index.tsx
Team select can be empty on initial load
Refetch Team Provider query on user change if initial load failes
> fix: admin empty team dropdown

- apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsListItem/GoalsListItem.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Video/BackgroundMediaVideo.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Options/VideoOptions.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashGallery.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/Source.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Source/Source.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoLibrary.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoList/VideoListItem/VideoListItem.tsx
- apps/journeys-admin/test/mockReactFlow.ts
Fixes video detail drawer showing incorrectly
The video detail drawer shows when switching tabs in the video source drawer.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7302308859)
There was a useEffect in `VideoLibrary` that was setting the open state for `VideoDetails`. I just moved the logic in the useEffect to the default state value.
N/A
N/A
> fix: video detail drawer

- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/QuickControls.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/QuickControls.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/QuickControls.tsx
- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/SelectableWrapper/SelectableWrapper.tsx
- apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsListItem/GoalsListItem.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNode.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageBlockEditor/UnsplashGallery/UnsplashGallery.tsx
- apps/journeys-admin/test/mockReactFlow.ts
Fixes quick action menu layout shift when unselecting video blocks
The styles for video blocks was being removed in the `SelectableWrapper` component.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7302407694)
Using the block instead does not remove the styles when selecting/unselecting but keeps the styles for the video block. The quick controls also requires the `block` property passed in from the `SelectableWrapper` to apply the styles correctly.
N/A
N/A
> fix: flashing action menu

- apps/api-gateway/schema.graphql
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/block/block.graphql
- apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/block.resolver.ts
- apps/api-journeys/src/app/modules/block/block.service.spec.ts
- apps/api-journeys/src/app/modules/block/block.service.ts
Duplicating a step block should allow you to update the position of the step block on the journey flow
Update blockDuplicate mutation to allow x and y to be passed in, and updates it for step blocks
n/a
n/a
> refactor: duplicate step block positions

- apps/watch/pages/api/jf/watch.html/[videoId]/[languageId].ts
Share links from the app are broken on watch if the url has an special characters. See La Liberté De L’Interieur
https://arc.gt/s/2_0-La-Liberte/529?apiSessionId=7D56842ADC954A4FB5378FA9012042F0
Url encode the link before sending it to redirect to redirect to keep it from being utf-8 endoded.
_Provide any additional information that might be useful to the reviewer in evaluating this pull request. This could include performance considerations,design …
> fix: fix encoding bug with share urls

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeMenu/StepBlockNodeMenu.tsx
Styling of the StepBlockNodeMenu was not matching to design
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7370863138)
Adjust the sx props styling
n/a
Popup used to look like
Popup now looks like
> fix: node menu style

- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/AddBlock/AddBlock.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Button/Button.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Form/Form.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Image.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/ImageOptions.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioOption/RadioOption.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/RadioQuestion/RadioQuestion.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/SignUp/SignUp.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/TextResponse/TextResponse.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Typography/Typography.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Video/Video.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/GoalDetails.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/GoalDetails/GoalDetails.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/SocialDetails.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/SocialDetails/SocialDetails.tsx
Add a close icon onto the settings panel, which takes the user back to the journey map
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7292062706#__recording_7375869126)
Added an onClose method to the settings drawers, which creates the close icon, and sets the activeSlide to JourneyFlow when clicked
Also refactored the properties block stories to include the close icon
> feat: close icon on settings panel

- apps/api-videos/db/migrations/20240508225808_20240508225807/migration.sql
- apps/api-videos/db/schema.prisma
- apps/api-videos/src/app/modules/video/video.resolver.spec.ts
No way to track arclight editions in core
Add edition & subtitle tables to api-videos
Add edition & subtitle tables to api-videos
Existing subtitle tables will be removed in a future PR
> feat: video edition schema

- apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.spec.tsx
- apps/journeys-admin/src/components/Editor/Toolbar/Toolbar.tsx
Add a tooltip on the back button of the journey flow view.
Also change the icon to bullet list.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7292062745)
As above
n/a
Was:
Changed to:
> fix: add back button tooltip

- tools/scripts/check-git-status.sh
Got failed CI/CD step as part of `check-git-status.sh` with no idea how to resolve.
Add a helpful message
Now outputs:
Only temporarily adding blank line change to test that it works.
Note that originally I branched from the wrong parent branch (https://github.com/JesusFilm/core/pull/2726) so I have moved the change to new branch and PR here.
> ci: add helpful message git status check

- apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoLibrary/VideoFromLocal/LocalDetails/LocalDetails.tsx
Local videos continue to play after the drawer is closed.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7380267444)
Added open prop to the dependencies in the videojs useEffect
> fix: stop playing local video after drawer closes

- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/utils/calculateDimensions/calculateDimensions.ts
Issue #1 on the below basecamp ticket. When the user shrinks the screen vertically, the canvas width and height will reduce. However, if you then bring the screen back to normal size, the canvas size does not adjust back to normal. 
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7356029597)
Removed clientWidth from the scale calculations. 
When shrinking the screen vertically, the top of the card(on the canvas) would go up behind the toolbar. To fix this, I added some extra margin height when the scale value has reduced below .65.
> fix: canvas size on journeymap

- apps/api-languages/db/migrations/20240510220947_20240510220946/migration.sql
- apps/api-languages/db/schema.prisma
- apps/api-languages/db/seed.ts
Name field is in a Json Blob array
Incrementally move name to a table relation
Adds new model & relations, as well as seed for new model
Once complete, this should allow us to import languages from BQ.
Additionally it should make for better caching down the line and reduce cpu usage of filtering json. Especially once we if/when we add WESS data
> feat: languages bq import support part 1

- libs/journeys/ui/src/components/SignUp/SignUp.tsx
- libs/journeys/ui/src/components/TextResponse/TextResponse.tsx
An error occurs when submitting text for Text Response or Sign Up blocks while using Google translate. On a technical note, google translate modifies nodes when adding the translations, but React is expecting the original text nodes, causing errors trying to remove or update nodes.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071027/todos/7385327978)
Wrapping the text inside the Mui `LoadingButton` component inside a span element preserves the parent child relation, allowing google translate to update the translations while allowing react to handle the updates correctly.
This is only required for `LoadingButtons` that are used as submit buttons in forms. I tested the other instances of `LoadingButton` and found they worked fine without the span tags.
[github issue …
> fix: google translate error on form blocks

- libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
Catch the "Decoding Firebase ID token failed." error and return null for user trying to authenticate.
> fix: catch firebase decode error

- apps/api-journeys/src/app/modules/customDomain/customDomain.acl.spec.ts
- apps/api-journeys/src/app/modules/customDomain/customDomain.acl.ts
- apps/api-journeys/src/app/modules/customDomain/customDomain.resolver.spec.ts
- apps/api-journeys/src/app/modules/customDomain/customDomain.resolver.ts
team members cannot see custom domain and hence preview button does not work
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071027/todos/7400237676)
added read permissions for team members to see custom
> fix: casl permissions update

- apps/journeys-admin/pages/templates/index.tsx
- apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
- apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/LanguagesFilterPopper/LanguagesFilterPopper.tsx
- apps/journeys-admin/src/components/TemplateGallery/data.ts
Needed more languages for `LanguagesFilterPopper` on templates page.
[Link to Basecamp Todo]()
Languages added:
- Hindi
- Ukrainian
- Arabic, Egyptian Modern Standard
Included a fix for long language names to be truncated with ellipsis.
> fix: add more languages to templates

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
Ultimately the goal is to add a node that lets our users know that a button with a set action goes either towards an email or url. Currently we don't have the time do that.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7380344215)
For now we're adding an icon after the title of the action
> fix: add icons after actions

- .gitignore
`.history/` folder is used by [Local History](https://marketplace.visualstudio.com/items?itemName=xyz.local-history). This should be ignored.
Add to git ignore
n/a
n/a
> build: ignore history folders

- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditWrapper.tsx
- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/QuickControls/DeleteBlock/DeleteBlock.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteOnKeyPress/index.ts
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/useDeleteOnKeyPress/useDeleteOnKeyPress.ts
- apps/journeys-admin/src/libs/useBlockDeleteMutation/index.ts
- apps/journeys-admin/src/libs/useBlockDeleteMutation/useBlockDeleteMutation.mock.ts
- apps/journeys-admin/src/libs/useBlockDeleteMutation/useBlockDeleteMutation.spec.tsx
- apps/journeys-admin/src/libs/useBlockDeleteMutation/useBlockDeleteMutation.ts
Allow users to delete nodes and edges when pressing backspace or delete
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7364539792)
- created a custom hook `useDeleteOnKeyPress` to perform various logic to delete a selected node or edge when pressing the backspace or delete key
N/A
- The original suggestion was to use reactflow's `onEdgesDelete` and `onNodesDelete` functions, but since some edges or nodes should not be deletable I had to use the `useKeyPress` helper as an override.
> feat: delete nodes and edges on keypress

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/ActionButton/ActionButton.tsx
- libs/locales/en/apps-journeys-admin.json
Change the text "Next Step ->" within the action button to become "Default Next Step ->"
Update the text to the desired new text and run extract translations
> fix: next step text

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
edges were not updating properly causing glitching UI when connecting from one handle to another
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7400975158)
employed ReactFlow's in built state manager to update the UI immediately
> fix: update edges immediately

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
Partners have cards that connected to itself. This functionality has been removed now, but is still getting reported as a bug
- Restricts steps and actions that connect to itself from creating edges. 
- Added some minor refactors and tests
n/a
- This only removes the visual representation as we deemed it not worth it to do a full migration removing this. 
- You can still see the NavigateToStepAction still showing the self connection if you manually look at the action update.
> feat: hide self connecting edges

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/libs/transformSteps/transformSteps.ts
The color for edge arrows was missing.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7403576506)
The rgb value returned from the mui `lighten` function did not work with the marker end color property. Updating the value returned from `lighten` using the mui `rgbToHex` function to convert the value into digestible hex value.
N/A
N/A
> fix: edge arrow color

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
Lyuba requested to hide the new step button and the react flow controls when editing a block.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7422849800)
Conditionally render `NewStepButton` and react flow `Controls` when the activeSlide is set to Journeyflow
N/A
N/A
> feat: hide step button and controls

- apps/journeys-admin/src/libs/useBlockActionDeleteMutation/useBlockActionDeleteMutation.spec.tsx
- apps/journeys-admin/src/libs/useNavigateToBlockActionUpdateMutation/useNavigateToBlockActionUpdateMutation.spec.tsx
- apps/journeys-admin/src/libs/useStepAndCardBlockCreateMutation/useStepAndCardBlockCreateMutation.spec.tsx
Normally mutation hook do not need tests, but because of the added logic in for cache updates, tests are now required
[- Action Delete Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7390573979)
[- Action update Basecamp Todo](https://3.basecamp.com/3105655/buckets/37071143/todos/7390574649)
add tests
n/a
Also added missing test for `stepAndCardBlockCreate` hook mutation
> test: add hook tests

- apps/api-gateway/schema.graphql
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/event/textResponse/textResponse.graphql
- apps/journeys-admin/__generated__/GetJourneyVisitors.ts
we need to filter duplicate text response events and return the most recent text response in the front end on a per text response block basis
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663186/todos/7439519537)
add the blockId of the originating text response event
> fix: form block update back end

- apps/watch/pages/index.tsx
- apps/watch/pages/videos.tsx
Urgent request from Melissa
"Is it possible to turn on visibility for the new believer course on the website immediately? Right now it is only searchable and not visible. I'm going into meetings with them Monday evening and all day Tuesday. It's kind of embarrassing that we've had it licensed for over a year and had it up on ArcLight for 6 months but they can't see it"
_If you have made changes to external services, need to add additional values to Doppler, or need to add …
> chore: add new believer course to watch and videos page

- apps/watch/pages/[part1]/[part2].tsx
Watch language switching for videos with non standard characters was broken in production but working locally.
The issue was the videoId string not being properly url encoded when sending the redirect leading to a 400 locally and a 404 redirect on production.
I added the proper encoding before sending the redirect.
None
None
> fix: language switcher encoding for watch

- apps/journeys-admin/src/components/Team/TeamCreateForm/TeamCreateForm.tsx
Fixes issue where team creation did not update journeys list - leading to misleading team journeys
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663057/todos/7475799222)
Run mutation query to update latest team on team create.
> fix: team creation updates journey list

- libs/journeys/ui/src/libs/action/action.ts
Currently navigating from journey to journey is causing an issue. The journey you're going to updates the title and everything else but the blocks doesn't get updated
The quickest fix is to reload the page so that the blockHistory gets a good refresh of data
> fix: reload page after updating url

- apps/journeys-admin/pages/templates/index.tsx
- apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.tsx
- apps/journeys-admin/src/components/TemplateGallery/data.ts
A partner is planning to provide templates in Turkish and need a way to filter for them
Update the query that fetches available languages to filter by
n/a
n/a
> feat: add turkish to template language filter

- apps/api-gateway/schema.graphql
- apps/api-journeys/db/migrations/20240611034043_20240611034041/migration.sql
- apps/api-journeys/db/migrations/20240611215915_20240611215913/migration.sql
- apps/api-journeys/db/schema.prisma
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/eventEmailNotifications/evenEmailNotifications.graphql
- apps/api-journeys/src/app/modules/eventEmailNotifications/eventEmailNotifications.resolver.spec.ts
- apps/api-journeys/src/app/modules/eventEmailNotifications/eventEmailNotifications.resolver.ts
need to be able to delete all the users eventUserNotifications if they get removed from the team
if user is part of the journey's team then the team id can be stored. Then we can delete all by userId and teamId
> feat: event email notification on delete cascade

- apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
Switching languages goes to 404 for videos with special characters inside of a collection.
Encode the contentid in the url
> fix: encode contentid on page 3

- .devcontainer/Dockerfile
- .devcontainer/docker-compose.yml
- .devcontainer/post-create-command.sh
Several user configs and caches are lost on rebuild
Upcoming changes will store even more in the home/node directory
Save All home/node data as a docker volume
Will require a new doppler login
Personal vscode extensions will now persist through rebuild
Also moved several post-install scripts into the docker image for less apt churn on build
Made Docker image Multi-stage to allow for caching layers requiring less rebuild
> feat: devcontainer updates

- libs/locales/en/apps-journeys-admin.json
Currently selecting multiple languages in the templates doesn't get reflected properly in the text
Update text to be representing multiple selected languages
> fix: template languages selected text

- apps/journeys-admin/setupTests.tsx
- apps/journeys-admin/src/components/JourneyList/ActiveJourneyList/ActivePriorityList/ActivePriorityList.spec.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCard.stories.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardInfo/JourneyCardInfo.spec.tsx
- apps/journeys-admin/src/components/JourneyVisitorsList/JourneyVisitorsList.stories.tsx
- apps/journeys-admin/src/components/Team/TeamUpdateDialog/TeamUpdateDialog.spec.tsx
- apps/journeys-admin/src/components/TemplateGallery/HeaderAndLanguageFilter/HeaderAndLanguageFilter.stories.tsx
- apps/journeys-admin/src/components/TemplateGallery/TemplateGallery.stories.tsx
- apps/journeys-admin/src/components/TemplateList/ActiveTemplateList/ActiveTemplateList.stories.tsx
- apps/journeys-admin/src/components/TemplateList/ArchivedTemplateList/ArchivedTemplateList.stories.tsx
- apps/journeys-admin/src/components/TemplateList/TemplateList.stories.tsx
- apps/journeys-admin/src/components/TemplateList/TemplateListItem/TemplateListItem.stories.tsx
- apps/journeys-admin/src/components/TemplateList/TrashedTemplateList/TrashedTemplateList.stories.tsx
- apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/EventsCard.spec.tsx
- apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/EventsCard.stories.tsx
- apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.spec.tsx
- apps/journeys-admin/src/components/VisitorInfo/VisitorJourneysList/EventsCard/TimelineEvent/TimelineEvent.stories.tsx
- libs/journeys/ui/test/i18n.ts
- libs/journeys/ui/tsconfig.json
- tsconfig.base.json
Components needed for the resources hub need refactored out into the shared space to be used by both journeys-admin and watch. 
We need to refactor out i18next query because it is needed by many stories and spec files which will be refactored out in a future PR.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663178/todos/7452920587)
This PR refactors the i18next function into the journeys/ui/ space. 
n/a
Big-bang discovery branch is here https://github.com/JesusFilm/core/pull/2810.
There should be no behavioural impact so ensure application still performs as expected. These components are currently only being used in journeys-admin so regression test as appropriate.
One should be able to use the i18n function in another project.
> refactor: i18next

- apps/api-journeys/src/app/modules/event/event.service.ts
- biome.json
- libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.spec.tsx
- libs/journeys/ui/src/components/StepFooter/ChatButtons/ChatButtons.tsx
Clicking on chat button crashes admin-stage or pretty much the api-journeys server. This is happening because it's trying to create a event but the ID for that event already exists
Use upsert instead of create to support cases when the event already exists
> fix: chat button not crashing on click

- apps/watch/src/components/Header/Header.tsx
Header divider line was showing up on watch page, which meant there was a line going through the background content
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663178/todos/7439735805)
Added a check to only show divider on light theme
> fix: remove header divider on watch

- apps/api-journeys/src/app/modules/journey/journey.module.ts
- apps/api-journeys/src/app/modules/plausible/plausible.module.ts
- apps/api-journeys/src/app/modules/plausible/plausible.resolver.spec.ts
- apps/api-journeys/src/app/modules/plausible/plausible.resolver.ts
plausible resolver get metrics only handled the case if info is type `field`
- getMetrics also handle types `fragment spread` and `inline fragment`
- Remove some redundant module dependencies
n/a
n/a
> fix: plausible resolver fragments

- apps/journeys-admin/pages/templates/[journeyId]/quick.tsx
When a  journey is duplicated using 'quick', the user is not opted in for journey email updates.
Opt in for journey email updates after journey is duplicated on the `templates/:id/quick` page.
> feat: express settings subscribe to journey updates

- apps/api-journeys/src/app/emails/stories/VisitorInteraction.stories.tsx
New date in storybook causing to stories to be regenerated
Make date static
> fix: static date

- apps/watch/src/components/VideoContentPage/VideoHeading/VideoHeading.spec.tsx
- apps/watch/src/components/VideoContentPage/VideoHeading/VideoHeading.tsx
Next links on the sub page of watch a film were leading to 404.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663057/todos/7540358832)
Prepend links with /watch
n/a
n/a
> fix: watch film link

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.spec.tsx
- libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.spec.ts
- libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.ts
Total links clicked and chats started was not being calculated correctly
Update the code that was calculating this
n/a
n/a
> fix: links and chats calc

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
The journey analytics card was blocking the interactivity of journey flow when not active
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663055/todos/7549579156)
Unmounting the journey analytics card when it should not be visible solves the issue
> fix: journeyflow deadspace

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/AnalyticsOverlaySwitch/AnalyticsOverlaySwitch.tsx
Stats default time filter to 30 days unless specified 
specify custom date to when stats were first collected to get all time stats
n/a
n/a
> feat: filter stats by all time

- infrastructure/modules/aws/locals.tf
- infrastructure/modules/aws/main.tf
AWS hosted sites did not offer forwarding from http requests
Open port 80 for ingress on public alb
Add port 80 to 443 forward in public alb listeners
Changes are implemented in AWS
Changes are live, PR is just updating terraform in main
> fix: alb ssl forward

- infrastructure/kube/ingress/deploy.yaml
When Vercel is acting as a proxy between the user and the plausible server the correct client IP address is not being passed to plausible. This is causing every event to plausible to be logged as a unique user due to each event call being executed as a lambda function on vercel. Vercel however is already passing the correct X-Forwarded-* headers.
Add use-forwarded-headers config for nginx ingress controller.
I have already applied this to K8s. This is just so that the repo is up to date.
> fix: use forwarded headers on k8s ingress

- .github/workflows/visual-test.yml
Visual tests are not running during merge queue as it's expecting the chromatic label. We are to add support that it runs without the label only during merge queue
Update the conditional statement which runs the visual test. Run the visual test if it's going to be pushed to main
> ci: update visual test run condition

- apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.spec.tsx
- apps/journeys-admin/src/components/OnboardingPageWrapper/OnboardingDrawer/OnboardingTemplateCard/OnboardingTemplateCard.tsx
The onboarding template preview is not displaying. The template preview is falling back to the skeleton placeholder.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663057/todos/7578126352)
The query to fetch the journey was using the slug instead of the journey id. Just had to query by the journey id and it returns the template properly.
> fix: onboarding template preview

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/OtherReferrer/OtherReferrer.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.tsx
- libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformJourneyAnalytics/transformJourneyAnalytics.spec.ts
- libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformReferrers/transformReferrers.spec.ts
- libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformReferrers/transformReferrers.ts
Long referrer names would overflow outside their container.
Styles for referrer nodes did not match.
[Long referrer names](https://3.basecamp.com/3105655/buckets/37663055/todos/7551057416)
[Referrer styles](https://3.basecamp.com/3105655/buckets/37663055/todos/7556307794)
- Updated the layout for the referrer node so that long names would no longer overflow outside their container. The text should now overflow to ellipsis and a tooltip is available to view the full referrer name.
- Update the styles for the referrer node
- Updated the referrer node layout algorithm
> fix: referrer styles

- libs/journeys/ui/src/components/TemplateGallery/TemplateGallery.tsx
Currently the default when languages are not specified is "All Languages". This is replaced with English as the default here.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7585497434)
_Provide any additional information that might be …
> fix: default english templates

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/BaseReferrer/BaseReferrer.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/OtherReferrer/OtherReferrer.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/OtherReferrer/OtherReferrer.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerNode.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerValue/ReferrerValue.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerValue/ReferrerValue.stories.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerValue/ReferrerValue.tsx
- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/ReferrerNode/ReferrerValue/index.ts
- libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformReferrers/transformReferrers.spec.ts
- libs/journeys/ui/src/libs/useJourneyAnalyticsQuery/transformReferrers/transformReferrers.ts
- libs/locales/en/apps-journeys-admin.json
Needed to update the other referrer component to use an accordion drop down to display the list of other sources rather than a tooltip.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/37663055/todos/7575963029)
Replaced the use of tooltip for displaying other sources with the accordion component
> refactor: other referrers

- apps/api-analytics/src/__generated__/graphql.ts
- apps/api-gateway/schema.graphql
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/__generated__/graphql.ts
- apps/api-journeys/src/app/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/action/action.graphql
The resolvers are already written with journeyId being optional. This makes it so that the graphql side can drop the field.
> chore: make journey id optional on action mutations

- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/Canvas.tsx
The journey flow card preview was not displaying properly on firefox
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7595172063)
Updated the container height inside the iframe to use `vh` instead of `100%`
> fix: card preview not displaying on firefox

- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/Card.tsx
Changing background color on a selected card, changed the background color of the previously selected card instead
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7613969491)
Add key for `BackgroundColor` so it references the currently selected step
n/a
n/a
> fix: add key for background color

- libs/journeys/ui/src/libs/EditorProvider/EditorProvider.spec.tsx
- libs/journeys/ui/src/libs/EditorProvider/EditorProvider.tsx
changing what the editor is primarily focused on requires a number of dispatches to be issued.
Add a new SetEditorFocusAction which uses the existing reducer function to combine actions to manage focus. This solution works down the editor state tree. See [Journeys Admin - Editor](https://www.figma.com/board/etPSAXYPE8pbWcKL9gej19/Journeys-Admin---Editor?node-id=0-1&t=CJuiW95WWVCOKoHn-1) documentation for more details on the state tree.
> feat: add set editor focus to editor provider

- apps/api-analytics/src/schema/site/siteCreate.mutation.spec.ts
- apps/api-analytics/src/schema/site/siteCreate.mutation.ts
- apps/api-journeys/src/app/modules/plausible/plausible.service.ts
When seed is ran, plausible attempts to create sites for the seeded teams and journeys. Since the teams and journeys still exist, the code enters into an infinite loop.
- Remove while loop that was causing the infinite loop issue with a chunked array.
- siteCreation returns the existing site when the owner tries to create a site with an existing domain
n/a
n/a
> fix: plausible site creation

- apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
- package-lock.json
- package.json
Undos and redos can be undone and redone in any order! Chaos! This should be fixed.
use mutationQueueLink from @adobe/apollo-link-mutation-queue to execute mutations in the order they were received.
> feat: use mutation link

- apps/api-journeys/src/app/modules/journey/journey.resolver.ts
Journeys were failing to duplicate properly
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7612339832)
Soft deleted blocks were not being properly handled in the duplication logic
> fix: duplicate journey error

- apps/api-journeys/src/app/modules/block/image/transformInput.spec.ts
- apps/api-journeys/src/app/modules/block/image/transformInput.ts
blurhash is super slow because we are using a fullsize image to calculate the blurhash.
resize image to 32x32 before calculating the blurhash.
> fix: resize image used for blurhash

- apps/api-videos/src/app/modules/importer/importerVideoSubtitle/importerVideoSubtitle.service.spec.ts
- apps/api-videos/src/app/modules/importer/importerVideoSubtitle/importerVideoSubtitle.service.ts
Primary is not properly filled in bq data, but easy to ascertain
Make 529 primary on import
> fix: video subtitle primary field

- apps/journeys-admin/next.config.js
The public env plausible url and the plausible url needs to be different
should be the plausible url in the config
Requires doppler changes to update the env first
n/a
> refactor: plausible env

- apps/journeys-admin/pages/templates/[journeyId].tsx
The back button on the templates page redirects to previous history rather than the templates page
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7594990078)
Updated the back button so it will redirect to the templates page instead of previous history
> refactor: redirect to templates

- apps/watch/pages/_app.tsx
- apps/watch/pages/watch/[part1]/[part2].tsx
- apps/watch/src/components/VideoCard/VideoCard.spec.tsx
- apps/watch/src/components/VideoCard/VideoCard.tsx
Need insights turned on for algolia searches
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213804/todos/7634025419)
Add send event call on each video card
Note that an event now sends for viewing a hit on any page, and when one is clicked.
Fixed a bug in ID of strategy
Should have hits viewed and video clicked events in algolia dashboard
> feat: insights watch

- apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/block.resolver.ts
returning the correct parent order of siblings of the restored block along with its descendants 
this is needed to automatically set correct parent order in the fe cache along with making sure the optimistic update parent order is not overridden
> fix: restore resolver should also return siblings

- apps/api-languages/src/bigquery/importers/languageNames/languageNames.ts
- apps/api-languages/src/schema/language/language.spec.ts
- apps/api-languages/src/schema/language/language.ts
- apps/api-languages/src/schema/language/languages.spec.ts
Language name primary was calculated incorrectly in the new seed
Row ordering changed the output of language names
correct importer primary calculation
add a default resolver for native and english
> fix: language name for selector

- apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/block.resolver.ts
actions need to be included so that the edges do not get overwritten incorrectly in the cache for a block restore
> fix: include action in children block restore

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/nodes/StepBlockNode/StepBlockNodeCard/StepBlockNodeCard.tsx
For the step block node card, the title of the node would cut off partially if it was long enough. This has been fixed now by slightly tweaking the padding and line heights.
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7586174799) …
> fix: step block node second line clipped

- libs/journeys/ui/src/components/VideoTrigger/VideoTrigger.tsx
https://3.basecamp.com/3105655/buckets/38213939/todos/7686470036
activeBlock can be undefined on page initialization.
Don't run useEffect when activeBlock is undefined.
> fix: video trigger when on first step

- apps/api-journeys/src/app/modules/block/block.resolver.spec.ts
- apps/api-journeys/src/app/modules/block/block.resolver.ts
block restore can now handle blocks that has a null parentOrder
> fix: handle null parentorder on block restore

- libs/journeys/ui/src/components/TemplateView/TemplateView.spec.tsx
- libs/journeys/ui/src/components/TemplateView/TemplateView.tsx
loading templates view is really slow! This is being caused by some tags having over 100 templates. 
This limits the related templates to 10.
> fix: limit related templates

- apps/journeys-admin/src/components/Editor/Slider/JourneyFlow/JourneyFlow.tsx
When block has no x or y the page throws an error
Edges and nodes should be set when use effect runs not when position data returns. They should only be set when there are positions for all the visible steps.
> fix: rely on use effect to populate positions

- .eslintrc.json
- .github/workflows/autofix.ci.yml
- .prettierignore
- apps/api-videos/src/app/modules/importer/importerVideos/importerVideos.service.ts
- apps/journeys-admin/src/components/Editor/Editor.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CanvasFooter.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Card/BackgroundMedia/Image/BackgroundMediaImage.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/blocks/Image/Options/ImageOptions.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/ImageSource/ImageSource.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/Drawer/VideoBlockEditor/Settings/Poster/Library/VideoBlockEditorSettingsPosterLibrary.spec.tsx
- apps/journeys-admin/src/components/PageWrapper/PageWrapper.spec.tsx
- apps/journeys-admin/src/components/Team/TeamCreateDialog/TeamCreateDialog.spec.tsx
- apps/journeys-admin/src/components/Team/TeamMenu/TeamMenu.spec.tsx
- apps/watch/src/components/VideoContentPage/VideoHero/VideoPlayer/VideoControls/VideoControls.spec.tsx
- libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/TemplateCardPreview/TemplateCardPreview.spec.tsx
- libs/journeys/ui/src/components/Video/VideoControls/VideoControls.spec.tsx
- libs/journeys/ui/src/libs/transformer/transformer.spec.ts
- libs/journeys/ui/src/libs/transformer/transformer.ts
all our logic expects steps to be of type StepBlock. I am pretty surprised tbh this hasn't caused more issues. There are some journeys with orphaned blocks. This stops them from being visible on the frontend and admin sites.
Also quick lint fix.
> fix: filter invalid root block types

- apps/journeys-admin/src/components/Editor/Slider/Content/Goals/GoalsList/GoalsList.tsx
Goals list was not scrollable causing some goals to not be viewable
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7683170757)
Corrected the styles for the goals list table to switch to overflow scroll instead of overflowing the parent container
N/A
N/A
> fix: goals overflow to scroll

- apps/watch/pages/strategies/index.tsx
Https referrers don't exists during build. Added a new API key that doesn't have https referrers to only be used during build
> fix: add api key for build time

- apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Could not swipe up on the card preview for mobile devices. Caused by the logic to set the swiper `allowTouchMove` property not handling the undefined case for `showAnalytics`
[Link to Basecamp Todo](https://3.basecamp.com/3105655/buckets/38213939/todos/7700139780)
Updated the logic for the swiper property to properly handle the necessary `showAnalytics` cases
> fix: editor mobile swipe

- apps/api-videos/src/schema/video/video.ts
if two video blocks existed it would make the video variant selected be in the same language.
> fix: video match right language

- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Footer/Footer.tsx
Needed to show the different drawer properties based on journey or website mode
- Updated `Footer` component to conditionally render drawer properties by journey or website mode
- Update `Footer` tests
> feat: add chat buttons to drawer

- apps/api-journeys/src/app/modules/block/block.service.ts
Omit card slug when duplicating
> fix: card duplicate

- libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.tsx
Each column's width is currently defined by their content. We are to generalise the width of each column in the language tab
> fix: refinement groups to be using grid

- libs/journeys/ui/src/components/SearchBar/SearchDropdown/SearchbarDropdown.tsx
Some of the dependencies within the useEffect triggers the default language selection function. Removed those dependencies and have made the useEffect to only call the default function depending on `refinements`
> fix: remove dependencies that triggers default selection

- apps/watch/middleware.spec.ts
- apps/watch/middleware.ts
- apps/watch/setupTests.tsx
The purpose of this middleware is to figure out the country the user is in. We are to later use this information to render necessary information within the watch client
Create a middleware in watch where we save the users country as a cookie. We're using the geo property that we can call from `NextRequest`. 
Things to keep in mind is that geo property comes out of the box for projects hosted on Vercel. If by any point we choose to run watch on a different hosting platform we are to update the configuration accordingly. Read more here: https://nextjs.org/docs/pages/api-reference/functions/next-request#geo
> feat: watch middleware

- apps/journeys-admin/__generated__/GetCountry.ts
- apps/journeys/__generated__/GetCountry.ts
- apps/watch/__generated__/GetCountry.ts
- libs/journeys/ui/src/libs/useCountryQuery/__generated__/GetCountry.ts
- libs/journeys/ui/src/libs/useCountryQuery/data.ts
- libs/journeys/ui/src/libs/useCountryQuery/index.ts
- libs/journeys/ui/src/libs/useCountryQuery/useCountryQuery.mock.ts
- libs/journeys/ui/src/libs/useCountryQuery/useCountryQuery.spec.tsx
- libs/journeys/ui/src/libs/useCountryQuery/useCountryQuery.ts
We need the ability to grab a country information, this information would be used to render the languages a user can choose from in the CountryLanguageSelector
Created the a useCountryQuery hook that enables us to call data for a country
it should return the following details: 
- flagPngSrc - image link to country flag
- countryLanguages
- returns the language(s) spoken by that country
- returns the amount of speakers of that language
> feat: use country query

- apps/journeys-admin/src/components/Editor/Fab/Fab.tsx
Add block is still enabled for steps that are video blocks when the user is on the JourneyFlow view. This allows the user to keep adding other blocks ontop of the video block.
Disable the add block fab when the user is on JourneyFlow view for video blocks.
> fix: disable add block fab for video block steps

- .github/workflows/danger.yml
Github danger keeps failing
Add recommended permissions to danger workflow
> fix: github danger workflow

- libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.spec.tsx
- libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.tsx
It takes up to 2 seconds to load the languages and sort the refinements into continents in the languages dropdown.
[Link to Linear Todo](https://linear.app/jesus-film-project/issue/ENG-873/languages-loading)
When languages are empty, display a loading state
- Should show a loading state when a user first opens the dropdown in languages tab
- Should still show no refinements state when a user has too specific a search
- Should still show refinements when they have loaded
> feat: add a loading state to languages dropdown

- apps/watch/next-env.d.ts
- libs/journeys/ui/src/components/SearchBar/LanguageButtons/LanguageButtons.tsx
On developer environment, we're getting a hydration error for Language Buttons
Update the Box that's causing the error, from Material UI to stick with being a `div` but have a role of a `button`
> fix: language buttons hydration error

- libs/journeys/ui/src/components/SearchBar/SearchBar.spec.tsx
- libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
Users want the dropdown to disapear on enter key
[Link to Linear Todo](https://linear.app/jesus-film-project/issue/ENG-817/enter-on-searchbar)
Should close on desktop keyboard enter
Should close on mobil keyboard enter
Should open on searchbar click
> feat: enter key closes the dropdown

- libs/journeys/ui/src/components/SearchBar/SearchBar.tsx
- libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.spec.tsx
- libs/journeys/ui/src/components/SearchBar/SearchDropdown/RefinementGroups/RefinementGroups.tsx
Currently we set a limit for the languageEnglishName refinement to only return 5 at the start, this doesn't reflect all the languages that we currently have
Up the limit of the refinement to be 1000 and update RefinementGroup to show the rest of the languages through CSS
> feat: grab all the languages from algolia

- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/CanvasFooter/CardAnalytics/CardAnalytics.tsx
Chat widget analytics order is not the same as on the card.
Swap them around
> fix: swap analytics chat widget icon order

- apps/watch/next-env.d.ts
- apps/watch/src/components/StrategiesView/StrategySections/StrategySection/data.ts
- apps/watch/src/libs/algolia/useAlgoliaStrategies/useAlgoliaStrategies.spec.ts
- apps/watch/src/libs/algolia/useAlgoliaStrategies/useAlgoliaStrategies.ts
Strategy card items are currently consuming all of the content for description. This won't do as it's not very descriptive
Update the hook useAlgoliaStrategies to be consuming the excerpt from Wordpress. The value comes with `p` tags we are to ensure the tag doesn't get renderd in strategies
> fix: update strategies to consume excerpt

- libs/shared/ui/src/libs/defaultVideoJsOptions/defaultVideoJsOptions.spec.ts
- libs/shared/ui/src/libs/defaultVideoJsOptions/defaultVideoJsOptions.ts
- package-lock.json
- package.json
Brightcove videos are lower resolution than possible and often start with the lowest resolution
Change vhs & hls settings to set and remember bandwidth
Use browser bandwidth calculation where possible
Don't limit resolution based on player size, but rather on bandwidth
Switch from webfont to svg to reduce package size
Enable new smoothseeking feature
> feat: videojs image improvements

- apps/journeys-admin/pages/users/verify.tsx
- libs/locales/en/apps-journeys-admin.json
There needs to be an appropriate title for the verify email page.
Add 'Email Verification' to the title using `NextSeo`
> fix: page title verify email

- apps/watch/next.config.js
- apps/watch/src/components/StrategiesView/StrategySections/StrategySections.tsx
It looks like that we might not be using the dev indices in the near future or not at all
Drop the use of dev indices and enable it to be used in all environments
> fix: drop dev indices strategy sections

- apps/watch/pages/api/geolocation.ts
Using `x-vercel-ip-country` returns inconsistent results when it comes to detecting the users location. This is due to 
Instead we are to use `x-vercel-ip-country` as a fallback and use `cf-ipcountry` to detect the users location or users country. `cf-ipcountry` returns a more consistent result in terms of location.
> fix: support cf country header

- apps/watch/src/components/PageWrapper/PageWrapper.tsx
- apps/watch/src/components/ResourcesView/ResourcesView.tsx
Entire resources page is able to scroll to the right
[Link to Linear Todo](https://linear.app/jesus-film-project/issue/ENG-976/disable-x-scroll-resources-page)
Use overflow-x: clip on all watch page wrapper containers
* Ensure the carousels overflow right to the edge of the screen
* Ensure the resources page cannot be scrolled to the right or left
* Ensure all other watch pages look and scroll as expected
> fix: disable page side scroll

- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/Properties/Properties.tsx
- Options for select inputs are not displaying in the properties drawer
- Add the swiper class to prevent event capture for the drawer
> fix: select options not displaying

- apps/api-languages/src/workers/bigQuery/importers/languageSlugs/languageSlugs.ts
Language slugs are not getting populated causing some videoVariants to not get imported.
fix the prisma call to use name instead of nameLanguage
> fix: use name instead of namelanguage in slug filter

- apps/journeys-admin/src/libs/apolloClient/apolloClient.ts
- apps/journeys/src/libs/apolloClient/apolloClient.ts
- apps/videos-admin/src/app/[locale]/_ApolloProvider/ApolloProvider.tsx
- apps/videos-admin/src/app/[locale]/users/unauthorized/page.tsx
- apps/videos-admin/src/libs/apollo/apolloClient.ts
- apps/videos-admin/src/middleware.ts
- apps/watch/src/libs/apolloClient/apolloClient.ts
This pull request updates the authorization headers in multiple Apollo Client configurations to use JWT tokens. The changes ensure that the `Authorization` header is correctly formatted as a JWT token string.
Authorization header updates:
* [`apps/journeys-admin/src/libs/apolloClient/apolloClient.ts`](diffhunk://#diff-5623b21681bed5ef22e6a41f3d69a4a8ee99d0addc268e3d051276f9ab22adc2L36-R36): Changed `Authorization` header to use `JWT ${firebaseToken}`.
* [`apps/journeys/src/libs/apolloClient/apolloClient.ts`](diffhunk://#diff-7b2e1ab77fe34d2e404a989dea996285fe9c8aca582f7f9ccf325e33f7d9fd4dL30-R30): Updated `Authorization` header to use `JWT ${token}` if `token` is not null.
* `apps/videos-admin/src/app/[locale]/_ApolloProvider/ApolloProvider.tsx`: Modified `Authorization` header to use …
> chore: add jwt to authorization header

- apps/journeys-admin-e2e/src/pages/journey-page.ts
- apps/journeys-admin/src/components/Editor/Toolbar/Items/Item/Item.spec.tsx
- apps/journeys-admin/src/components/Editor/Toolbar/Items/Item/Item.tsx
- apps/journeys-admin/src/components/Editor/Toolbar/Items/PreviewItem/PreviewItem.spec.tsx
- apps/journeys-admin/src/components/Editor/Toolbar/Items/PreviewItem/PreviewItem.tsx
If a button is to always be displayed, we need to at least disable it during loading states.
If you load the journey flow, and you are quick, you can click the preview button before the journey loads which sends you to an undefined url.
[Link to Linear Todo](https://linear.app/jesus-film-project/issue/ENG-1121/preview-button-undefined)
Disable the button if the href is undefined.
Added a span around the IconButton because tooltips cannot take disabled buttons.
Refactored out href string building into named const's for code cleanliness.
Open a large journey and try to click the preview button as soon as it shows. You may try using network throttling or use on a mobile. At no point should you be able to click the preview button until the journey has loaded. 
When clicking the preview …
> fix: disable preview button if no href

- libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
- libs/yoga/src/firebaseClient/firebaseClient.ts
This pull request includes changes to the payload schema in two different files to improve consistency and handle null values more flexibly. The most important changes include replacing the `.nullable()` method with `.nullish()` for the `picture` field.
Schema updates for consistency:
* [`libs/nest/common/src/lib/firebaseClient/firebaseClient.ts`](diffhunk://#diff-2cb825a00ad967c021e9b36e02a8f9b87795b7b13f95efc07f89666221ea4703L33-R33): Changed the `picture` field from `z.string().nullable()` to `z.string().nullish()` to handle null values more flexibly.
* [`libs/yoga/src/firebaseClient/firebaseClient.ts`](diffhunk://#diff-f705e44b0588a69d6e742f65bf921a01a74c4eb41a07837f00c8b557227b8057L29-R29): Updated the `picture` field from `z.string().nullable()` to `z.string().nullish()` for …
> fix: pic needs to be nullish

- apps/api-journeys/src/app/emails/templates/JourneyAccessRequest/JourneyAccessRequest.tsx
- apps/api-journeys/src/app/emails/templates/JourneyShared/JourneyShared.tsx
- apps/api-journeys/src/app/emails/templates/TeamInvite/TeamInvite.tsx
- apps/api-journeys/src/app/emails/templates/TeamInviteAccepted/TeamInviteAccepted.tsx
- apps/api-journeys/src/app/emails/templates/TeamRemoved/TeamRemoved.tsx
- apps/api-journeys/src/app/emails/templates/VisitorInteraction/VisitorInteraction.tsx
- apps/api-journeys/src/app/modules/mailChimp/mailChimp.service.ts
- apps/api-journeys/src/app/modules/userInvite/userInvite.resolver.ts
- apps/api-journeys/src/app/modules/userTeamInvite/userTeamInvite.resolver.ts
- apps/api-users/src/schema/user/user.ts
- libs/nest/common/src/lib/firebaseClient/firebaseClient.ts
- libs/yoga/src/firebaseClient/firebaseClient.ts
This pull request includes several changes to handle cases where a user's email might be null or undefined. The changes ensure that the application gracefully handles these scenarios without causing errors.
* Updated `UnsubscribeLink` components to handle cases where `recipient.email` might be null or undefined in various email templates. (`JourneyAccessRequest.tsx` [[1]](diffhunk://#diff-28c71da0aa1853a9ea32d92706fe2afb9c367e72f1730aa3e08dbc403a45804eL90-R90) `JourneyShared.tsx` [[2]](diffhunk://#diff-a18a43cb6c86b62ea53c56ba7e519e67cf1549dd8269b68de35f875a581bfc80L86-R86) `TeamInvite.tsx` [[3]](diffhunk://#diff-268d5fcec0e44c408eb67cc1eb5e8615245d1c0a6fb86df1baae97e1fdbd8d8dL73-R73) `TeamInviteAccepted.tsx` [[4]](diffhunk://#diff-e230b6da7520ac990e54906f99d7fd9a882d28573f0496e32407f27e99 …
> fix: nullish email address

- apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.spec.tsx
- apps/journeys-admin/src/components/PageWrapper/NavigationDrawer/UserNavigation/UserMenu/UserMenu.tsx
`resetStore` refetches the active queries. changed function to `clearStore` which removes cache without refetch of queries
> fix: clear cache on logout

- apps/api-media/db/schema.prisma
Deprecate unused prisma video image fields
add deprecated jsdoc tag to alert that the fields are deprecated
> feat: deprecate video image prisma fields

- apps/api-journeys/src/app/modules/event/event.service.spec.ts
- apps/api-journeys/src/app/modules/event/event.service.ts
- apps/api-journeys/src/app/modules/journey/journey.resolver.spec.ts
- apps/api-journeys/src/app/modules/journey/journey.resolver.ts
- apps/api-journeys/src/app/modules/plausible/plausible.service.ts
- apps/api-media/src/workers/server.ts
Our bullmq redis servers are filling with completed junk, causing the volatile lru to handle deletions.
Remove completed tasks and add expiration to failed ones
> feat: add expiration to completed bullmq jobs-no-qa

- apps/api-media/src/workers/bigQuery/importers/videoImages/videoImages.spec.ts
- apps/api-media/src/workers/bigQuery/importers/videoImages/videoImages.ts
Video image fields are no longer needed on bq import
Change importer to create cloudflare images and not require video image fields
> chore: bq video image fields to cf

- apps/api-media/src/schema/video/video.spec.ts
- apps/api-media/src/schema/video/video.ts
This pull request introduces error handling for cases where a video is not found in the database. The changes include importing necessary libraries, adding error handling in the video query resolver, and updating tests to cover the new error scenario.
Error handling improvements:
* [`apps/api-media/src/schema/video/video.ts`](diffhunk://#diff-7333027db0b1ac5a75be38f49d0b888174a854e4ac103b154fe9f228d7fe6fc4R404): Added error handling in the video query resolver to throw a `GraphQLError` when a video is not found. This involves catching `PrismaClientKnownRequestError` and rethrowing it as a `GraphQLError` with a specific message. [[1]](diffhunk://#diff-7333027db0b1ac5a75be38f49d0b888174a854e4ac103b154fe9f228d7fe6fc4R404) [[2]](diffhunk://#diff-7333027db0b1ac5a75be38f49d0b888174a854e4ac103b15 …
> fix: catch error when no video found

- .github/workflows/app-deploy.yml
- .github/workflows/ecs-frontend-deploy-prod-worker.yml
- .github/workflows/ecs-frontend-deploy-stage-worker.yml
- apps/arclight/project.json
- apps/docs/project.json
- apps/journeys-admin/project.json
- apps/journeys-admin/src/libs/firebaseClient/initAuth.ts
- apps/journeys/project.json
- apps/videos-admin/project.json
- apps/watch/project.json
This pull request includes updates to environment variables and deployment configurations across multiple files to standardize and ensure consistency in the deployment process.
* [`.github/workflows/app-deploy.yml`](diffhunk://#diff-9e0c9c0f4afe54c489ddc47b38619a84a911c7fdae64ac8e5a48dd7bde43b95cL109-R109): Changed `NEXT_PUBLIC_VERCEL_ENV` values from `preview` to `stage` and from `production` to `prod` for different deployment jobs. [[1]](diffhunk://#diff-9e0c9c0f4afe54c489ddc47b38619a84a911c7fdae64ac8e5a48dd7bde43b95cL109-R109) [[2]](diffhunk://#diff-9e0c9c0f4afe54c489ddc47b38619a84a911c7fdae64ac8e5a48dd7bde43b95cL261-R261)
* [`.github/workflows/ecs-frontend-deploy-prod-worker.yml`](diffhunk://#diff-ea1f935e5945a5982d5434211256fd1e5d9167c7fba02333cb7b633cfbf83548R120-R121): Added …
> fix: update vercel environment variables for deployments

- apps/api-gateway/Dockerfile
- package-lock.json
- package.json
This pull request includes updates to the Docker image version and the removal of an unused package from `package.json`. These changes aim to keep dependencies up-to-date and clean up the project.
Dependency updates:
* [`apps/api-gateway/Dockerfile`](diffhunk://#diff-948323ae264c213f9ef92d63425f2f77b495ad8804cf520ebaf4f8153f883b40L5-R5): Updated the Docker image version from `ghcr.io/ardatan/hive-gateway:1.0.5` to `ghcr.io/ardatan/hive-gateway:1.2.0`.
Code cleanup:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L154): Removed the unused `node-libcurl` package to clean up dependencies.
> chore: update to hive gateway 1-2-0

- apps/watch-e2e/src/monitoring/watch-redirection.monitor.ts
- apps/watch-e2e/src/monitoring/watch.monitor.ts
- package-lock.json
- package.json
Running watch monitoring redirect separately. So, we can identify which test failed during alert.
_Provide any additional information that might be …
> test: run watch monitoring redirect test separately

- apps/api-media/src/workers/bigQuery/importers/videoImages/videoImages.ts
Video image seed takes about 45 minutes in dev, even though stage and prod handle the actual cloudflare portion
Only run cloudflare check/upload in prod environments
> feat: fake cloudflare video images in dev

- apps/watch/__generated__/GetVideoContainerAndVideoContent.ts
- apps/watch/pages/watch/[part1]/[part2]/[part3].tsx
This pull request includes changes to the GraphQL query and debugging improvements in the `apps/watch/pages/watch/[part1]/[part2]/[part3].tsx` file. The most important changes include swapping the `container` and `content` fields in the GraphQL query and adding console logs for debugging purposes.
GraphQL Query Changes:
* `apps/watch/pages/watch/[part1]/[part2]/[part3].tsx`: Swapped the `container` and `content` fields in the `GET_VIDEO_CONTAINER_AND_VIDEO_CONTENT` GraphQL query. (`[apps/watch/pages/watch/[part1]/[part2]/[part3].tsxL28-R31](diffhunk://#diff-3d9a5bd894937ba419a23bf72d1927fdeedf18d46d31c8ff0fba30f8205ec7e5L28-R31)`)
Debugging Improvements:
* `apps/watch/pages/watch/[part1]/[part2]/[part3].tsx`: Added console logs to print `containerId` and `contentId` with `languageId` for …
> fix: part3 container error on watch

- apps/journeys/pages/[hostname]/[journeySlug]/[stepSlug].tsx
- apps/journeys/pages/home/[journeySlug]/[stepSlug].tsx
This pull request to `apps/journeys/pages/home/[journeySlug]/[stepSlug].tsx` includes changes to improve the handling of invalid step slugs and to add revalidation for static props. The most important changes include moving the step block validation to `getStaticProps` and adding revalidation logic.
Improvements to step block validation:
* `apps/journeys/pages/home/[journeySlug]/[stepSlug].tsx`: Removed the step block validation from the `StepPage` component. ([apps/journeys/pages/home/[journeySlug]/[stepSlug].tsxL42-L45](diffhunk://#diff-ec3d15b9703e427a4d071e770d0ddacd02fabd900324a43a787d9a90ff02dba8L42-L45))
* `apps/journeys/pages/home/[journeySlug]/[stepSlug].tsx`: Added step block validation in `getStaticProps` to redirect to the journey's main page if the step block is not found. …
> fix: detect step not found on ssr

- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/ButtonEdit/ButtonEdit.tsx
- apps/journeys-admin/src/components/Editor/Slider/Content/Canvas/InlineEditWrapper/InlineEditInput/InlineEditInput.tsx
tapping on a button element is zooming in on the button. Editing it's properties keeps bringing up the keyboard
remove unnecessary ref.focus() as focus i already being controlled by autofocus prop. this programmatic focus was bringing up the keyboard on every state change.
on IOS - set the font-size to be relative to the document, preventing safari from zooming in on focus
> fix: prevent zoom when editing blocks on ios safari

- apps/api-media/src/workers/bigQuery/importers/videoSubtitles/videoSubtitles.spec.ts
- apps/api-media/src/workers/bigQuery/importers/videoSubtitles/videoSubtitles.ts
- apps/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.spec.ts
- apps/api-media/src/workers/bigQuery/importers/videoVariants/videoVariants.ts
- apps/api-media/src/workers/seed/service/edition/edition.spec.ts
- apps/api-media/src/workers/seed/service/edition/edition.ts
Edition seed could miss outliers or prevent new biquery insertions
Fix edition seed for upcoming prisma references
> fix: edition seed

- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Chat/ChatOption/Details/Details.spec.tsx
- apps/journeys-admin/src/components/Editor/Slider/Settings/CanvasDetails/JourneyAppearance/Chat/ChatOption/Details/Details.tsx
Adding URLs to the chat platforms accepts the string as is and doesn't support adding the HTTPS protocol. Causing the user to visit your.nextstep.is/[chat link]
Add a protocol check before Chat button link update. If it already has a protocol proceed to update. Otherwise we are to append the HTTPS protocol to the URL
> fix: add protocol check

- libs/shared/ui/src/components/LanguageAutocomplete/defaultRenderOption/defaultRenderOption.tsx
recent update to MUI has broken Mui Box components using component="li" props styling. 
Change such components to MUI list items
> fix: li components after mui update

- .storybook/static/mockServiceWorker.js
- apps/journeys/src/components/WebView/WebView.tsx
Analytics incorrect after menu card
Refactor a useEffect to update the blockHistory so the page changes are detected for analytics
> fix: page view events after menu card

- apps/videos-admin/src/app/[locale]/_ApolloProvider/ApolloProvider.tsx
- apps/videos-admin/src/app/[locale]/layout.tsx
anonymous user token were being passed to gql endpoints instead of actual user token, causing forbidden error.
[Link to Linear Todo](https://linear.app/jesus-film-project/issue/ENG-1318/jwt-token-not-being-passed-to-backend-properly)
removed signInAnonymously function and replaced with getting the user from auth context and passing to apollo provider context to be sent as headers on every request.
> fix: pass  jwt to backend

- apps/watch/pages/watch/[part1]/[part2].tsx
- apps/watch/src/components/VideoCard/VideoCard.tsx
- apps/watch/src/components/VideoGrid/AlgoliaVideoGrid/AlgoliaVideoGrid.tsx
- apps/watch/src/components/VideoGrid/VideoGrid.tsx
The Single Video/Container page SEO is impacted due to the recent Algolia changes. The issue arises because VideoCard uses `sendEvent` (from Algolia) for tracking video selections, requiring pages that uses VideoCard to be wrapped in `InstantSearchProvider` - even non-search pages.
Added an `onClick` prop to VideoCard to handle tracking externally, removing the direct dependency on Algolia's provider. This preserves analytics on search page while fixing SEO in the Single Video/Container Page.
> fix: seo issues on videos page

- apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Metadata/StudyQuestionsList/StudyQuestionsList.tsx
- apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
- apps/videos-admin/src/components/OrderedList/OrderedItem/Actions/Actions.tsx
- apps/videos-admin/src/components/OrderedList/OrderedItem/DropDown/DropDown.tsx
- apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.tsx
- apps/videos-admin/src/components/OrderedList/OrderedList.tsx
study questions are editable at all times 
ran dispatch to change state on edit button click
add disabled states to interactive buttons
stripped ui in view only mode
> fix: disable study questions when not in edit mode

- apps/api-media/src/schema/cloudflare/image/image.spec.ts
- apps/api-media/src/schema/cloudflare/image/image.ts
- apps/api-media/src/schema/cloudflare/video/video.spec.ts
- apps/api-media/src/schema/cloudflare/video/video.ts
- apps/api-media/src/schema/mux/video/video.spec.ts
- apps/api-media/src/schema/mux/video/video.ts
Publishers need to be able to change media assets
Allow deletion of cloudflare images/videos in db for publishers (due to cf mixing environments. will be later addressed with custom ids)
Allow deletion of mux videos by publishers
> feat: allow publishers to delete media items 

- apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.spec.tsx
- apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.tsx
- apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.tsx
- apps/videos-admin/src/components/OrderedList/OrderedList.stories.tsx
- apps/videos-admin/src/components/OrderedList/OrderedList.tsx
lists need to be converted to list item component
children cards need a clean up
styles of the drag handle need adjusting
converted all lists to list items
dropped unnecessary buttons from children cards and made the onClick function handle what the buttons were doing
fixed the styles of the drag handle
> fix: change components to list items and clean up children

- apps/videos-admin/src/components/SaveButton/SaveButton.tsx
save button is too big
remove width from css styles and added size=small prop
> fix: make save button smaller

- apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Children/Children.tsx
- apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.tsx
- apps/videos-admin/src/components/OrderedList/OrderedItem/OrderedItem.tsx
- apps/videos-admin/src/components/OrderedList/OrderedList.tsx
drag handle sizing was too small - was being overriden by list item styles
study questions need to be left aligned properly
added important rule to width and property styles to stop them from being overridden by list item styles at run time
removed left and right padding from list items
adding padding to boxes where the sx prop was overriden, thus removing default styles in the component
> fix: icon sizing

- apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/Variants/Variants.spec.tsx
- apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.spec.tsx
- apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
- libs/locales/en/apps-videos-admin.json
No need for the "Editing:" label.
- Removed "Editing:" from the video title
- Fixed broken test in `Variants.spec.tsx`
> fix: remove editing label

- apps/journeys-admin/src/components/MediaListItem/MediaListItem.tsx
Fixed broken overflow for onboarding journeys using caption font.
> fix: set description text to block

- apps/api-gateway/schema.graphql
- apps/api-journeys/schema.graphql
- apps/api-journeys/src/__generated__/graphql.ts
- apps/api-journeys/src/app/modules/block/video/video.graphql
- apps/journeys/__generated__/JourneyViewEventCreate.ts
Video field is no longer the correct field for videoblocks
Deprecate video field in favor of mediaVideo
> chore: deprecate video field

- apps/api-journeys/src/app/modules/block/video/video.resolver.ts
Mux upload needs to return id for upcoming background uploader instead of error
Return id
> fix: mux background api

- apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.spec.tsx
- apps/videos-admin/src/app/[locale]/(dashboard)/videos/[videoId]/_VideoView/VideoView.tsx
- apps/videos-admin/src/components/PublishedChip/PublishedChip.tsx
Requested to hide the status label while the data is loading
- Conditionally render video header while data is loading
- Add test for loading ui
> feat: hide published label while data is loading

- apps/watch/src/libs/slugMap.ts
Ache and A Che are routing to same video but are two seperate videos.
Remove slug mapping so languages have seperate slugs.
> fix: remove ache slug mapping

- libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPlayer/TemplateVideoPlayer.tsx
- libs/journeys/ui/src/components/TemplateView/TemplatePreviewTabs/TemplateVideoPreview/TemplateVideoPreview.tsx
It looks like a mux player type was missed for templates. Will be needed after mux migrations
Add missing lines from other video template
> fix: fix missing mux video type for video templates

- infrastructure/environments/prod/main.tf
core.arclight.org target is a typo
> fix: core arclight dns

- apps/videos-admin/src/app/(dashboard)/videos/[videoId]/children/add/_ExistingVideoByIdSelector/ExistingVideoByIdSelector.spec.tsx
- apps/videos-admin/src/app/(dashboard)/videos/[videoId]/children/add/_ExistingVideoByIdSelector/ExistingVideoByIdSelector.tsx
- apps/videos-admin/src/app/(dashboard)/videos/[videoId]/children/add/_ExistingVideoByIdSelector/index.ts
- apps/videos-admin/src/app/(dashboard)/videos/[videoId]/children/add/_ExistingVideoSelector/ExistingVideoSelector.spec.tsx
- apps/videos-admin/src/app/(dashboard)/videos/[videoId]/children/add/_ExistingVideoSelector/ExistingVideoSelector.tsx
- apps/videos-admin/src/app/(dashboard)/videos/[videoId]/children/add/_ExistingVideoSelector/index.ts
- apps/videos-admin/src/app/(dashboard)/videos/[videoId]/children/add/page.tsx
…n methods
- Introduced a selection mechanism for adding child videos, allowing users to choose between creating a new video, finding an existing video by title, or adding an existing video by ID.
- Updated the dialog title to reflect the new functionality.
- Integrated new components for selecting existing videos and handling their addition as children.
> feat: add existing child

- apps/journeys-admin/src/components/Editor/Toolbar/Items/ShareItem/ShareItem.tsx
- apps/journeys-admin/src/components/JourneyList/JourneyCard/JourneyCardMenu/DefaultMenu/DefaultMenu.tsx
This PR provides a fix to keep the journey card menu mounted when the share dialog opens.
> fix: keep share dialog mounted

- apps/journeys-admin/next.config.js
- package.json
- pnpm-lock.yaml
This PR updates the Next.js configuration and adds a new dependency for React transitions.
- Removed `fallbackNodePolyfills: false` from experimental config in `apps/journeys-admin/next.config.js`
- This simplifies the Next.js configuration by removing an experimental feature
- Added `react-transition-group: ^4.4.5` to package.json
- This dependency provides transition components for React applications
- `apps/journeys-admin/next.config.js`
- `package.json`
- `pnpm-lock.yaml` (auto-generated)
✅ **Already Compatible**: After thorough analysis, all CSSTransition components in the codebase already have proper `nodeRef` implementation:
- `Content.tsx`: Uses `const nodeRef = useRef(null)` and `nodeRef={nodeRef}` ✅
- `Canvas.tsx`: Uses `const nodeRef = useRef(null)` and `nodeRef={nodeRef}` ✅
- …
> feat: update journeys-admin config and add react-transition-group dependency

- apps/journeys-admin/next.config.js
- apps/journeys/pages/_app.tsx
- apps/journeys/src/app/globals.css
Fixed build issue with journeys-admin.
**Problem Analysis**
The build was failing because the streamdown package (used for AI chat responses) has KaTeX as a dependency for math rendering. The package was trying to import `katex/dist/katex.min.css `as an ES module, but Next.js was treating it as a JavaScript import, causing the "Unknown file extension .css" error.
**Solution**
The issue is fixed by adding `streamdown` to the `transpilePackages` array in the Next.js configuration. This tells Next.js to transpile the `streamdown` package and handle its CSS imports properly.
Changes made to /workspaces/core/apps/journeys-admin/next.config.js:
> fix: transpile streamdown

- apps/journeys-admin/src/components/Editor/Fab/Fab.spec.tsx
- apps/journeys-admin/src/components/Editor/Fab/Fab.tsx
- apps/journeys-admin/src/components/Editor/Slider/Slider.tsx
Disable the ability to drag the window when analytics overlay is on
> fix: disable dragging of window when analytics overlay is on
